<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.26100.7705" />
    <PackageVersion Include="Microsoft.WindowsAppSDK.Runtime" Version="1.8.260710003" />
    <PackageVersion Include="Microsoft.WindowsAppSDK.WinUI" Version="1.8.260709004" />
  </ItemGroup>
</Project>
