import Foundation

extension AppLocalization {
    static let frenchPhraseTable: [AppLocalizedPhrase: String] = [
        .idleStatus: "Inactif",
        .settingsDiskTab: "Disque",
        .diskLocationICloud: "iCloud",
        .diskLocationDesktop: "Bureau",
        .diskLocationSpecificFolder: "Dossier",
        .diskLocationCustom: "Personnalisé",
        .settingsScanTab: "Numérisation",
        .settingsDefaultScanRotationPicker: "Rotation de numérisation par défaut",
        .settingsDefaultScanRotationHelp: "Appliquée aux nouvelles numérisations sans orientation définie. Le brut du scanner est généralement stocké à l'envers (180°).",
        .diskRootFolderLabel: "Dossier negaflow",
        .diskThumbnailsFolderLabel: "Dossier des vignettes",
        .diskImportedSourcesFolderLabel: "Dossier de déplacement des sources importées",
        .diskCleanedRawFolderLabel: "Dossier du cache des images corrigées",
        .diskScanPreviewFolderLabel: "Dossier du cache des aperçus de numérisation",
        .diskExportFolderLabel: "Dossier d'exportation",
        .diskResetPathsButton: "Réinitialiser les chemins par défaut",
        .diskFolderStructureHelp: "Les originaux numérisés sont classés par date, type de film et nom du film.",
        .diskThumbnailCacheLabel: "Cache des vignettes",
        .diskClearThumbnailCache: "Vider le cache des vignettes",
        .diskThumbnailCacheClearedStatus: "Cache des vignettes vidé",
        .diskCacheSizeCalculating: "Calcul",
        .diskLibraryBackupLabel: "Sauvegardes du catalogue",
        .diskLibraryBackupNow: "Sauvegarder la bibliothèque maintenant",
        .diskLibraryBackupCreatedStatus: "Sauvegarde de la bibliothèque créée",
        .diskLibraryBackupFailedStatus: "Échec de la sauvegarde de la bibliothèque",
        .libraryRestoredFormat: "Bibliothèque restaurée : %d photos",
        .libraryRecoveredFromBackupFormat: "Bibliothèque récupérée depuis la sauvegarde : %d photos",
        .libraryCatalogMigratedFormat: "Bibliothèque mise à niveau depuis la version de catalogue %d : %d photos",
        .libraryCatalogBlockedStatus: "Le catalogue n’a pas pu être ouvert en toute sécurité et a été conservé sans modification.",
        .libraryCatalogLockedStatus: "Cette bibliothèque est déjà ouverte dans un autre processus Negaflow.",
        .libraryCatalogLockUnavailableStatus: "Negaflow n’a pas pu obtenir le verrou d’écriture. Le catalogue n’a pas été modifié.",
        .libraryCatalogNewerVersionFormat: "Cette bibliothèque utilise la version de catalogue plus récente %d et a été conservée sans modification.",
        .libraryCatalogMissingAuthoritativeDataStatus: "Les recettes de correction sont incomplètes et aucune sauvegarde valide n’a été trouvée. Le catalogue a été conservé sans modification.",
        .librarySelectedBackupAppliedFormat: "Sauvegarde sélectionnée restaurée : %d photos",
        .libraryPendingRestoreFailedStatus: "La restauration planifiée n’a pas pu être appliquée et reste en attente.",
        .diskLibraryBackupBrowse: "Afficher les sauvegardes",
        .libraryBackupEmpty: "Aucune sauvegarde",
        .libraryBackupLoadFailed: "Impossible de charger les sauvegardes",
        .libraryBackupRefresh: "Actualiser",
        .libraryBackupUnknownDate: "Date inconnue",
        .libraryBackupChecksummed: "Somme de contrôle vérifiée",
        .libraryBackupLegacy: "Ancien format",
        .libraryBackupIncompatible: "Incompatible",
        .libraryBackupDamaged: "Endommagée",
        .libraryBackupCountsFormat: "%d photos · %d recettes de correction",
        .libraryBackupRestoreSelected: "Restaurer la sauvegarde sélectionnée",
        .libraryBackupRestoreConfirmationTitle: "Restaurer cette sauvegarde ?",
        .libraryBackupRestoreConfirmationMessage: "La bibliothèque actuelle sera conservée séparément. La restauration sera appliquée au prochain lancement.",
        .libraryBackupScheduleRestore: "Planifier la restauration",
        .libraryBackupRestorePending: "Restauration au prochain lancement",
        .libraryBackupCancelPending: "Annuler la restauration planifiée",
        .libraryBackupRestoreScheduleFailed: "Impossible de planifier la restauration",
        .done: "Terminé",
        .noScannerStatus: "Aucun scanner",
        .autoWhiteBalanceStatus: "Balance des blancs automatique",
        .autoToneStatus: "Tonalité automatique",
        .filmBaseSampleFailed: "Échec de la mesure de la base du film — l'image source n'est pas chargée",
        .filmBasePickedFormat: "Base du film définie : %.3f %.3f %.3f",
        .noFramesToSync: "Aucune image à synchroniser",
        .whiteBalanceSyncedFormat: "Balance des blancs synchronisée : %d images",
        .grainMendBrushEditTitleFormat: "GrainMend · Pinceau · %d coups",
        .grainMendAutoEditTitleFormat: "GrainMend · Auto · %d défauts",
        .grainMendGuidedEditTitleFormat: "GrainMend · Guidé · %d zones",
        .brushEditSummary: "Détection et réparation précises de la zone sélectionnée",
        .defectsClearedStatus: "Suppression des défauts réinitialisée",
        .removingDefectsStatus: "Suppression des défauts en cours",
        .removingDefectsFailedStatus: "Échec de la suppression des défauts",
        .imageLoadFailedFormat: "Échec du chargement de l'image : %@",
        .historyNameFormat: "Historique %d",
        .historyRecordedFormat: "Historique enregistré : %@",
        .historyAppliedFormat: "Historique appliqué : %@",
        .developSettingsCopiedFormat: "Paramètres de développement copiés : %@",
        .noDevelopSettingsToPaste: "Aucun paramètre de développement à coller",
        .chooseDevelopPasteScope: "Choisissez les paramètres de développement à coller",
        .developSettingsPasted: "Paramètres de développement collés",
        .developSettingsPartiallyPastedFormat: "Paramètres de développement partiellement collés (%@)",
        .developSettingsPasteStatusFormat: "%@ : %@ -> %@",
        .snapshotSavedFormat: "Instantané enregistré : %@",
        .snapshotAppliedFormat: "Instantané appliqué : %@",
        .snapshotCompareEnded: "Comparaison A/B terminée : réglages actuels",
        .snapshotComparingFormat: "Comparaison A/B : %@",
        .snapshotNameFormat: "Instantané %d",
        .exportingStatus: "Exportation en cours",
        .exportCompleteFormat: "Exportation terminée -> %@",
        .exportCompleteWithPairsFormat: "Exportation terminée -> %@",
        .exportDestinationConflict: "L’exportation a été arrêtée, car un fichier de sortie existe déjà.",
        .exportFailedFormat: "Échec de l'exportation : %@",
        .importPanelPrompt: "Importer",
        .importPanelMessage: "Choisissez les images à développer (RAW/DNG/TIFF/PNG/JPG)",
        .noImportableImages: "Aucune image importable (formats pris en charge : RAW/DNG/TIFF/PNG/JPG)",
        .importLibraryRegistrationFailedStatus: "Impossible d’ajouter les images importées à la photothèque",
        .importCompleteFormat: "%d images importées",
        .importCompleteUnsupportedFormat: "%d images importées (%d fichiers non pris en charge ignorés)",
        .importCompleteDuplicatesFormat: "%d images importées (%d doublons ignorés)",
        .importCompleteUnsupportedDuplicatesFormat: "%d images importées (%d non prises en charge, %d doublons ignorés)",
        .importFolder: "Importer un dossier",
        .importImageShort: "Image",
        .importFolderShort: "Dossier",
        .folderImportPanelMessage: "Choisissez les dossiers à ajouter à la bibliothèque. Les images qu'ils contiennent seront importées.",
        .folderImportCompleteFormat: "%d images importées depuis %d dossier(s)",
        .folderImportCompleteEmptyFormat: "%d dossier(s) vide(s) ajouté(s)",
        .detectingDefectsStatus: "Détection des défauts en cours",
        .detectingDefectsFailedStatus: "Échec de la détection des défauts",
        .noDefectsStatus: "Aucun défaut",
        .automaticDefectSafetyStoppedStatus: "Arrêt automatique de sécurité · Sélectionnez une zone en mode Guidé",
        .defectsCountFormat: "%d défauts",
        .confidenceSummaryFormat: "%@ · confiance %.0f%%",
        .grainMendIREditTitleFormat: "GrainMend · IR · %d défauts",
        .infraredCleanDetectingStatus: "Détection des défauts via le canal infrarouge",
        .infraredCleanAppliedFormat: "%d défauts supprimés grâce au canal infrarouge",
        .infraredCleanNoDefectsStatus: "Aucun défaut trouvé dans le canal infrarouge",
        .infraredCleanSkippedBWStatus: "Nettoyage IR ignoré : le film N&B argentique bloque l'infrarouge",
        .infraredCleanCoverageAbortStatus: "Nettoyage IR interrompu : masque trop étendu (vérifiez le type de film ou l'alignement IR)",
        .infraredCleanFailedStatus: "Échec de la détection des défauts IR",
        .demoModeStatus: "Mode démo",
        .scannerWaitingStatus: "En attente de la connexion du scanner",
        .scannerPluginMissingStartImportStatus: "Aucun module scanner — commencez par importer des images",
        .scannerPluginMissingStatus: "Aucun module scanner",
        .scannerPluginApprovalRequiredStatus: "Approbation du module scanner requise",
        .scannerPluginTrustStoreUnavailableStatus: "Le stockage des approbations de modules est indisponible",
        .scannerPluginApprovedStatus: "Module scanner approuvé",
        .scannerPluginApprovalFailedStatus: "Échec de l’approbation du module scanner",
        .scannerPluginApprovalRevokedStatus: "Approbation du module scanner révoquée",
        .scannerAppConflictWarningFormat: "%@ est ouvert — fermez-le avant de rechercher les scanners.",
        .noScannerUseDemoStatus: "Aucun scanner — connectez le câble USB ou activez le mode démo.",
        .previewScanPreparing: "Préparation de l'aperçu de numérisation",
        .filmScanPreparing: "Préparation de la numérisation du film",
        .frameScanCompleteFormat: "Image %d numérisée : %d x %d%@",
        .frameScanErrorFormat: "Erreur de numérisation de l'image %d : %@",
        .framesScanCompleteFormat: "%d images numérisées",
        .scanCanceled: "Numérisation annulée",
        .scanWorkflowPersistenceFailed: "L’état de numérisation n’a pas pu être enregistré dans le catalogue.",
        .scanWorkflowInvalidState: "L’état du flux de numérisation n’est pas valide.",
        .scanInterruptedFailureReason: "L’app s’est fermée avant de pouvoir confirmer la fin de la capture matérielle.",
        .scanDeviceUnavailable: "Le scanner sélectionné n’a pas pu être vérifié.",
        .scanOutputFolderFailedFormat: "Le dossier des originaux numérisés n’a pas pu être créé : %@",
        .scanRollFilmMismatch: "Le type de film du Roll actif ne correspond pas aux réglages de numérisation.",
        .scanNumberRangeExceeded: "La limite de numérotation des images numérisées a été dépassée.",
        .noActiveScanner: "Aucun scanner actif.",
        .noInstalledPlugins: "(aucun module installé)",
        .scanProgressIdle: "Inactif",
        .scanProgressConnecting: "Connexion au scanner",
        .scanProgressWarmingLamp: "Préchauffage de la lampe",
        .scanProgressReady: "Prêt à numériser",
        .scanProgressPreviewScanning: "Aperçu en cours de numérisation",
        .scanProgressWaitingForFilmHolder: "En attente du porte-film",
        .scanProgressScanningRGB: "Numérisation du film",
        .scanProgressScanningIR: "Numérisation du canal infrarouge",
        .scanProgressProcessingNegative: "Traitement des données de numérisation",
        .scanProgressRenderingLook: "Rendu de l'aperçu de développement",
        .scanProgressExporting: "Exportation en cours",
        .scanProgressComplete: "Numérisation terminée",
        .scanProgressScannerBusy: "Scanner occupé",
        .scanProgressDisconnected: "Scanner déconnecté",
        .scanProgressError: "Erreur de numérisation",
        .scanProgressBackendFallbackActive: "Backend de secours actif",
        .userPresetNameFormat: "Paramètre prédéfini %d",
        .userPresetSavedFormat: "Paramètre prédéfini utilisateur enregistré : %@",
        .userPresetAppliedFormat: "Paramètre prédéfini utilisateur appliqué : %@",
        .userPresetDeletedFormat: "Paramètre prédéfini utilisateur supprimé : %@",
        .virtualCopyCreatedFormat: "Copie virtuelle créée : %@",
        .proofCopyCreatedFormat: "Copie d’épreuve créée : %@",
        .proofCopyNameFormat: "%@ — Épreuve : %@",
        .noSelection: "Aucune sélection",
        .none: "Aucun",
        .baseSection: "Base",
        .inspectorTabBasic: "Base",
        .inspectorTabEdit: "Édition",
        .inspectorTabDefect: "GrainMend",
        .filmStock: "Pellicule",
        .densitySourceFormat: "Source de densité : %@ · la base mesurée (bord/pipette) est toujours prioritaire.",
        .lightSource: "Source lumineuse",
        .lightSourceFallbackNote: "Ignoré lorsque la base du film est mesurée à partir du scan (mesure en priorité). Appliqué uniquement quand aucune base ne peut être mesurée.",
        .autoMatch: "Correspondance auto",
        .autoMatchRequiresValidatedProfile: "La correspondance automatique exige un profil validé avec des scans de référence appariés.",
        .scannerProfileStatusDraft: "Brouillon",
        .scannerProfileStatusRealOnly: "Scans réels",
        .scannerProfileStatusPairedSmoke: "Test apparié",
        .scannerProfileStatusPairedValidated: "Validation appariée",
        .profile: "Profil",
        .pick: "Prélever",
        .pickBase: "Pipette de base",
        .pickBaseOnCanvas: "Cliquez sur la base dans le canevas",
        .pickBaseHelp: "Cliquez sur la base non exposée du film, sur les données brutes avant inversion, pour mesurer le Dmin.",
        .baseRed: "Base R",
        .baseGreen: "Base V",
        .baseBlue: "Base B",
        .autoLevels: "Niveaux auto",
        .autoColor: "Couleur auto",
        .baseModeAuto: "Auto",
        .baseModeFilm: "Film",
        .baseModeManual: "Manuel",
        .before: "Avant",
        .unedited: "Sans corrections",
        .after: "Après",
        .currentImage: "Image actuelle",
        .beforeSourceHelp: "Choisir la source de l'état Avant",
        .raw: "Brut",
        .developed: "Développée",
        .compareSplitVertical: "Avant/Après côte à côte",
        .compareSplitHorizontal: "Avant/Après haut/bas",
        .zoomOut: "Zoom arrière",
        .zoomIn: "Zoom avant",
        .zoomPercentHelp: "Saisissez le pourcentage de zoom",
        .fitToScreen: "Ajuster",
        .actualSize: "Taille réelle",
        .apply: "Appliquer",
        .mode: "Mode",
        .strength: "Intensité",
        .shadowHue: "Teinte des ombres",
        .highlightHue: "Teinte des hautes lumières",
        .shadows: "Ombres",
        .midtones: "Tons moyens",
        .highlights: "Hautes lumières",
        .hue: "Teinte",
        .saturationAbbrev: "Sat.",
        .luminance: "Luminance",
        .blending: "Fusion",
        .balance: "Balance",
        .canvasBackgroundMenu: "Couleur d'arrière-plan",
        .debugBadgeFormat: "Débogage · %@",
        .basePickerOverlayPrompt: "Cliquez sur la base non exposée du film (entre les vues ou sur le bord) · Échap pour annuler",
        .scannerLabel: "Scanner",
        .resolution: "Résolution",
        .preview: "Aperçu",
        .bitDepth: "Profondeur de bits",
        .colorMode: "Mode",
        .perforation: "Perforations",
        .filmFrameFormat: "Format d’image",
        .hardwareScanArea: "Zone de numérisation matérielle",
        .scanAreaWidth: "Largeur",
        .scanAreaHeight: "Hauteur",
        .framesFormat: "Images : %d",
        .flatbedFramesFormat: "Sélection : %d",
        .flatbedFrameFormat: "Image %d",
        .flatbedAddFrame: "Ajouter une image",
        .flatbedPreviewRequired: "Lancez un aperçu et sélectionnez au moins une image.",
        .flatbedGeometryMismatch: "Le scanner a renvoyé une image dont les proportions diffèrent de la zone sélectionnée.",
        .multiExposure: "Multi-exposition",
        .infrared: "Infrarouge (IR)",
        .infraredHelp: "Numérise le canal infrarouge pour détecter poussières et rayures. Affiché uniquement sur les appareils compatibles IR.",
        .scanSection: "Numérisation",
        .cancel: "Annuler",
        .scan: "Numériser",
        .importSource: "Importer",
        .scanNext: "Numériser la suivante",
        .scanCountFormat: "Numériser x%d",
        .scannerSearching: "Recherche du scanner — vérifiez la connexion USB.",
        .scannerPluginMissingTitle: "Aucun module scanner n'est installé.",
        .scannerPluginMissingBody: "Les scanners de film sont fournis sous forme de modules séparés pour des raisons de licence. Une fois le module installé, vous pourrez numériser ici. En attendant, commencez le développement en important des images.",
        .scannerPluginApprovalTitle: "Approbation des modules scanner",
        .scannerPluginVersion: "Version",
        .scannerPluginLicense: "Licence",
        .scannerPluginManifestPath: "Chemin du manifest",
        .scannerPluginManifestHash: "SHA-256 du manifest",
        .scannerPluginExecutableHash: "SHA-256 de l’exécutable",
        .scannerPluginApprove: "Approuver",
        .scannerPluginRevokeApproval: "Révoquer l’approbation",
        .scannerPluginApproved: "Approuvé",
        .scannerPluginApprovalRequired: "Approbation requise",
        .scannerPluginChangedApprovalRequired: "Modifié · Nouvelle approbation requise",
        .scannerPluginInvalidIdentity: "Identité non valide",
        .scannerPluginTrustStoreUnavailable: "Stockage des approbations indisponible",
        .scannerPluginNotReported: "Non indiqué",
        .scannerSimulator: "Simulateur de scanner",
        .scannerSimulatorHelp: "Simulateur intégré pour découvrir le flux de numérisation sans module.",
        .scannerTruth: "Informations scanner",
        .transparency: "Transparence",
        .brightness: "Luminosité",
        .contrast: "Contraste",
        .capabilityUnavailable: "Indisponible",
        .capabilityAvailable: "Disponible",
        .capabilityWaiting: "En attente de la réponse du scanner.",
        .multiExposurePreviewHelp: "La multi-exposition n'est pas utilisée pour les aperçus.",
        .multiExposureUnsupportedHelp: "Le backend actuel n'expose pas de véritable contrôle d'exposition matériel ; cette option est donc désactivée.",
        .multiExposureSupportedHelp: "Combine plusieurs numérisations uniquement sur les appareils dont le backend prend en charge le contrôle de l'exposition.",
        .exportMainFlatMaster: "Master MAIN non corrigé",
        .exportOriginalRawTIFF: "TIFF de numérisation original",
        .exportSidecar: "Fichiers annexes (JSON + XMP)",
        .colorScannerInput: "Émulation scanner",
        .colorWorking: "Espace de travail",
        .colorMonitor: "Moniteur",
        .colorExport: "Exportation",
        .colorSoftProof: "Épreuve écran",
        .colorGamutWarning: "Avertissement de gamme",
        .colorSampler: "Échantillonneur RVB/Lab/HSV",
        .colorClippingOverlay: "Incrustation d'écrêtage",
        .choose: "Choisir",
        .all: "Tout",
        .red: "Rouge",
        .orange: "Orange",
        .yellow: "Jaune",
        .green: "Vert",
        .aqua: "Turquoise",
        .blue: "Bleu",
        .purple: "Violet",
        .magenta: "Magenta",
        .basicTone: "Réglages de base",
        .exposure: "Exposition",
        .toneHighlights: "Hautes lumières",
        .whites: "Blancs",
        .blacks: "Noirs",
        .density: "Densité",
        .toneCurve: "Courbe des tonalités",
        .lights: "Tons clairs",
        .darks: "Tons foncés",
        .color: "Couleur",
        .warmth: "Température",
        .tint: "Teinte",
        .vibrance: "Vibrance",
        .saturation: "Saturation",
        .colorDepth: "Profondeur des couleurs",
        .colorMixer: "Mélangeur de couleurs",
        .colorGrading: "Étalonnage des couleurs",
        .bwToning: "Virage N&B",
        .calibration: "Calibrage",
        .redPrimary: "Primaire rouge",
        .greenPrimary: "Primaire vert",
        .bluePrimary: "Primaire bleu",
        .detailEffects: "Détails et effets",
        .noiseReduction: "Réduction du bruit",
        .noiseReductionStrength: "Débruitage : intensité",
        .noiseReductionLuminance: "Débruitage : luminance",
        .noiseReductionColor: "Débruitage : couleur",
        .noiseReductionDarkTones: "Débruitage : tons sombres",
        .noiseReductionDetail: "Débruitage : détail",
        .noiseReductionGrainProtect: "Protection du grain",
        .grain: "Grain",
        .sharpness: "Netteté",
        .clarity: "Clarté",
        .halation: "Halation",
        .vignette: "Vignettage",
        .developerDebug: "Débogage développeur",
        .developerMode: "Mode développeur",
        .debugOverlay: "Incrustation de débogage",
        .stage: "Étape",
        .full: "Plein cadre",
        .undoLastStroke: "Annuler le dernier tracé",
        .clearPaintedStrokes: "Effacer les tracés",
        .resetAppliedDefects: "Réinitialiser toutes les corrections de défauts",
        .removeDefects: "Supprimer les défauts",
        .resetAdjustmentsHelp: "Réinitialise tous les réglages, à l'exception de la géométrie (rotation/recadrage).",
        .autoToneHelp: "Tonalité automatique Cmd-U — ajuste l'exposition, le contraste, les hautes lumières, les ombres, les blancs, les noirs et la vibrance d'après l'histogramme.",
        .autoWhiteBalanceHelp: "Balance des blancs automatique Maj-Cmd-U — neutralise la température et la teinte selon l'hypothèse du monde gris.",
        .copy: "Copier",
        .paste: "Coller",
        .copyDevelopSettingsHelp: "Copie les paramètres de développement de l'image actuelle.",
        .pasteDevelopSettingsHelp: "Colle les paramètres de développement copiés.",
        .pasteScope: "Portée du collage",
        .pasteScopeHelp: "Choisissez les paramètres de développement à coller.",
        .allSettings: "Tous les paramètres",
        .copyPaste: "Copier / Coller",
        .snapshot: "Instantané",
        .noSnapshots: "Aucun instantané",
        .save: "Enregistrer",
        .saveSnapshotHelp: "Enregistre l'état de développement actuel comme instantané.",
        .applySnapshotHelp: "Applique l'instantané sélectionné.",
        .compareSnapshotHelp: "Compare temporairement les réglages actuels avec l'instantané sélectionné.",
        .current: "Actuel",
        .noHistory: "Aucun historique",
        .history: "Historique",
        .record: "Enregistrer",
        .recordHistoryHelp: "Enregistre l'état de développement actuel dans l'historique.",
        .applyHistoryHelp: "Applique l'état d'historique sélectionné.",
        .intensity: "Intensité",
        .geometry: "Géométrie",
        .original: "Original",
        .custom: "Personnalisé",
        .aspectRatio: "Proportions",
        .unlockCropAspect: "Déverrouiller les proportions du recadrage",
        .lockCropAspect: "Verrouiller les proportions du recadrage",
        .cropAspectLocked: "Proportions du recadrage verrouillées",
        .cropAspectUnlocked: "Proportions du recadrage déverrouillées",
        .angle: "Angle",
        .cropArea: "Zone de recadrage",
        .rotateLeft: "Rotation de 90° vers la gauche",
        .rotateRight: "Rotation de 90° vers la droite",
        .resetTransform: "Réinitialiser la transformation",
        .resetPhotoAngle: "Réinitialiser l’angle",
        .brushDefect: "Pinceau",
        .guidedDefect: "Guidé",
        .brushDefectHelp: "Pinceau — peignez sur les poussières ou rayures, puis appuyez sur Entrée ou « Supprimer les défauts ».",
        .guidedDefectHelp: "Guidé — tracez une zone, puis appuyez sur Entrée ou « Supprimer les défauts ».",
        .cloneStamp: "Tampon de clonage",
        .cloneStampHelp: "Tampon de clonage — ⌥-clic pour définir la source, puis faites glisser pour peindre.",
        .cloneStampSourceHint: "⌥-clic pour définir la source du clonage",
        .cloneStampSize: "Taille",
        .cloneStampHardness: "Dureté",
        .cloneStampEditTitleFormat: "Tampon %dpx",
        .cloneStampEditSummary: "Duplique les pixels de la source choisie",
        .flipHorizontal: "Symétrie horizontale",
        .flipVertical: "Symétrie verticale",
        .baseReadoutFormat: "base %.2f %.2f %.2f",
        .batchFrameProgressFormat: "Image %d/%d",
        .rating: "Note",
        .resetRating: "Effacer la note",
        .ratingAccessibilityFormat: "Note %d",
        .histogram: "Histogramme",
        .shadowTone: "Ombres",
        .highlightTone: "Hautes lumières",
        .rgbChannelOverlay: "Incrustation des canaux RVB",
        .redChannel: "Canal rouge",
        .greenChannel: "Canal vert",
        .blueChannel: "Canal bleu",
        .clippingChannelsFormat: "Écrêtage %@",
        .resetSectionFormat: "Réinitialiser %@",
        .sliderKeyboardHelp: "Les flèches ajustent de 0,01 ; Maj+flèche de 0,10.",
        .baseMetricsFormat: "dmin %@ · dmax %@",
        .notAvailableAbbrev: "n/d",
        .softProofSummaryFormat: "%@, %@",
        .softProofProfileOnly: "Profil",
        .softProofPaperAndBlack: "Papier + encre noire",
        .softProofInvalidICC: "Le profil ICC sélectionné ne peut pas être utilisé pour l’épreuve écran RVB.",
        .printOutputProfileRequired: "L’export PRINT nécessite un profil ICC d’imprimante RVB valide.",
        .developingFramesFormat: "Développement de %d images",
        .generatingPreviewFormat: "Génération de l'aperçu (%dpx)",
        .generatingSettledPreviewFormat: "Génération de l'aperçu final (%dpx)",
        .defectLayers: "Calques GrainMend",
        .disableLayer: "Désactiver le calque (voir avant réparation)",
        .enableLayer: "Activer le calque (appliquer la réparation)",
        .hideMask: "Masquer le masque",
        .showMask: "Afficher le masque",
        .deleteLayer: "Supprimer le calque",
        .defectDust: "Poussière",
        .defectPinhole: "Trou d'épingle",
        .defectScratchHorizontal: "Rayure horizontale",
        .defectScratchVertical: "Rayure verticale",
        .defectScratchDiagonal: "Rayure diagonale",
        .defectEmulsionDamage: "Émulsion endommagée",
        .defectMicroSpeck: "Micro-particules",
        .autoDefect: "Auto",
        .autoDefectHelp: "Auto — détecte toute l'image automatiquement, puis supprime les défauts",
        .frameCountFormat: "%d images",
        .frameDisplayFormat: "Image %d",
        .frameCopyDisplayFormat: "Image %d copie %d",
        .frameCompactCopyDisplayFormat: "Image %d C%d",
        .namedFrameCopyDisplayFormat: "%@ copie %d",
        .dpiUnspecified: "DPI non spécifié",
        .ratingStarFormat: "%d étoile(s)",
        .unrated: "Sans note",
        .unflagged: "Non marquée",
        .picked: "Retenue",
        .rejected: "Rejetée",
        .selectionSummaryFormat: "%@ · %@",
        .selectionCountsFormat: "%d retenues · %d rejetées",
        .starHelpFormat: "%d étoile(s)",
        .clearPick: "Retirer la marque Retenue",
        .clearReject: "Retirer la marque Rejetée",
        .quickExportHelpFormat: "%@ — %@ · %d dpi -> %@",
        .target: "Cible",
        .filmProfile: "Profil de film",
        .look: "Rendu",
        .film: "Film",
        .process: "Procédé",
        .filmName: "Nom du film",
        .scanFolderName: "Nom du dossier",
        .chooseScanFolder: "Choisir le dossier de numérisation",
        .untitledFilm: "Film sans titre",
        .userPreset: "Paramètre prédéfini utilisateur",
        .noUserPresets: "Aucun paramètre prédéfini utilisateur",
        .saveUserPresetHelp: "Enregistre les paramètres de développement actuels comme paramètre prédéfini utilisateur",
        .applyUserPresetHelp: "Applique le paramètre prédéfini utilisateur sélectionné",
        .deleteUserPresetHelp: "Supprime le paramètre prédéfini utilisateur sélectionné",
        .delete: "Supprimer",
        .removeFromLibrary: "Retirer",
        .libraryRemovalUndoAvailableFormat: "%d élément(s) retiré(s) du catalogue · Annulation disponible",
        .libraryRemovalRestoredFormat: "%d élément(s) restauré(s) dans le catalogue",
        .scanProvenanceProtectedStatus: "Cet original numérisé fait partie du journal de capture et ne peut pas encore être déplacé ou retiré.",
        .sourceDeletionPlanChangedStatus: "L’ensemble des sources a changé. Vérifiez à nouveau la suppression.",
        .sourceDeletionUnavailableStatus: "La suppression des sources est indisponible tant que le catalogue n’est pas prêt.",
        .sourceDeletionMoveFailedStatus: "Les sources n’ont pas pu être placées dans la corbeille. Le catalogue n’a pas été modifié.",
        .sourceDeletionCatalogFailedStatus: "Le catalogue n’a pas pu être validé. Les sources ont été restaurées.",
        .sourceDeletionRollbackFailedStatus: "Le catalogue n’a pas été modifié, mais certaines sources n’ont pas pu être restaurées. Récupérez-les dans la corbeille.",
        .moveSourceToTrash: "Placer le fichier source dans la corbeille",
        .sourceOffline: "Hors ligne",
        .locateOriginal: "Localiser l’original",
        .locateMissingFolder: "Localiser le dossier manquant",
        .newFolder: "Nouveau dossier",
        .create: "Créer",
        .showInFinder: "Afficher dans le Finder",
        .renameFolder: "Renommer",
        .moveToFolder: "Déplacer vers un dossier",
        .moveItemsHere: "Déplacer ici",
        .sourceMoveCompleteFormat: "%d fichier(s) source déplacé(s).",
        .sourceMoveFailedStatus: "Impossible de déplacer les fichiers source. Les modifications ont été annulées.",
        .sourceMoveCatalogFailedStatus: "Impossible d’enregistrer le catalogue. Les fichiers source ont été restaurés.",
        .sourceMoveCollisionStatus: "Un fichier ou dossier du même nom existe déjà dans la destination.",
        .folderCreatedStatusFormat: "Dossier créé : %@",
        .folderCreateFailedStatus: "Impossible de créer le dossier.",
        .locateSourcePanelMessageFormat: "Dernier emplacement connu : %@",
        .locateFolderPanelMessageFormat: "Dernier dossier connu : %@",
        .sourceRelinkInvalid: "Le fichier sélectionné n’est pas une image prise en charge et lisible.",
        .sourceRelinkedFormat: "%d élément(s) du catalogue reconnecté(s).",
        .deleteSourceConfirmationTitle: "Placer le fichier source dans la corbeille ?",
        .deleteSourceConfirmationMessageFormat: "%d éléments du catalogue partagent %d fichier(s) source. Ils seront tous retirés de Negaflow. %@",
        .virtualCopy: "Copie virtuelle",
        .virtualCopyHelp: "Crée une copie non destructive qui partage la même image brute",
        .proofCopy: "Copie d’épreuve",
        .proofCopyHelp: "Crée une copie non destructive liée au profil d’épreuve sélectionné",
        .dragDefectRegion: "Tracez un rectangle sur la zone du défaut",
        .undo: "Annuler",
        .undoDefectRemovalHelp: "Annule la dernière correction de défaut",
        .defectsCountExcludedFormat: "%d défauts (%d exclus)",
        .toneCurveEditorHelp: "Cliquez pour ajouter un point · glissez pour déplacer · double-cliquez pour supprimer",
        .reset: "Réinitialiser",
        .previousFrame: "Image précédente",
        .nextFrame: "Image suivante",
        .noImages: "Aucune image",
        .libraryFiles: "Fichiers",
        .libraryAllPhotos: "Toutes les photos",
        .libraryAllShort: "Toutes",
        .libraryFolders: "Dossiers",
        .libraryFilmType: "Type de film",
        .libraryOffline: "Hors ligne",
        .libraryCollections: "Collections",
        .librarySmartCollections: "Collections dynamiques",
        .librarySavedSearches: "Recherches enregistrées",
        .libraryNewCollection: "Nouvelle collection",
        .libraryNewSmartCollection: "Nouvelle collection dynamique",
        .librarySaveCurrentSearch: "Enregistrer la recherche actuelle",
        .libraryCollectionName: "Nom de la collection",
        .librarySearchName: "Nom de la recherche",
        .libraryAddToCollection: "Ajouter à la collection",
        .libraryRemoveFromCollection: "Retirer de la collection",
        .libraryInvalidStoredSearch: "Recherche enregistrée illisible",
        .librarySearchPlaceholder: "Rechercher des photos",
        .libraryClearSearch: "Effacer la recherche",
        .libraryResultCountFormat: "%d photos sur %d",
        .filterCurrentRoll: "Pellicule actuelle",
        .filterMinimumRatingFormat: "%d étoiles et plus",
        .filterInfrared: "Infrarouge",
        .filterDefectRecipe: "Recette de correction",
        .filterUnvalidatedProfile: "Profil non validé",
        .filterMetadataUnknown: "État des métadonnées inconnu",
        .libraryFilters: "Filtres",
        .clearFilters: "Effacer les filtres",
        .exportFileSettings: "Fichier",
        .exportQualitySettings: "Qualité",
        .exportSourceSettings: "Source",
        .noMatchingPhotos: "Aucune photo correspondante",
        .noLibraryFolders: "Aucun dossier",
        .libraryRefreshStatusFormat: "Bibliothèque actualisée : %d nouveau(x) · %d reconnecté(s) · %d hors ligne",
        .sortBy: "Trier par",
        .ascending: "Croissant",
        .descending: "Décroissant",
        .sortInputOrder: "Ordre d'import",
        .sortTime: "Heure",
        .sortName: "Nom",
        .sortFlag: "Marqueur",
        .sortRating: "Note",
        .sortSize: "Taille",
        .renamePhoto: "Renommer la photo",
        .photoName: "Nom de la photo",
        .rename: "Renommer",
        .filmstripHeightHelp: "Ajuster la hauteur du film fixe",
        .frameCardSizeHelp: "Taille des vignettes",
        .developTargetMain: "MAIN",
        .developTargetPrint: "PRINT",
        .filmTypeColorNegative: "Négatif couleur",
        .filmTypeSlide: "Diapositive",
        .filmTypeBWNegative: "Négatif N&B",
        .filmTypeBWPositive: "Positif N&B",
        .targetFilmSummaryFormat: "%@ · %@",
        .frameAccessibilityFormat: "%@, %@, %@",
        .dynamicRangeChannel: "DR",
        .rgb: "RVB",
        .redChannelShort: "R",
        .greenChannelShort: "V",
        .blueChannelShort: "B",
    ]


}
