import Foundation

extension AppLocalization {
    static let koreanPhraseTable: [AppLocalizedPhrase: String] = [
            .idleStatus: "대기",
            .settingsDiskTab: "디스크",
            .diskLocationICloud: "아이 클라우드",
            .diskLocationDesktop: "데스크탑",
            .diskLocationSpecificFolder: "특정 폴더",
            .diskLocationCustom: "커스텀",
            .settingsScanTab: "스캔",
            .settingsDefaultScanRotationPicker: "스캔 기본 방향",
            .settingsDefaultScanRotationHelp: "방향이 지정되지 않은 새 스캔에 적용됩니다. 스캐너 원본은 보통 180° 뒤집혀 저장됩니다.",
            .diskRootFolderLabel: "negaflow 폴더",
            .diskThumbnailsFolderLabel: "썸네일 폴더",
            .diskImportedSourcesFolderLabel: "가져온 원본 이동 기본 폴더",
            .diskCleanedRawFolderLabel: "보정 이미지 캐시 폴더",
            .diskScanPreviewFolderLabel: "스캔 프리뷰 캐시 폴더",
            .diskExportFolderLabel: "내보내기 폴더",
            .diskResetPathsButton: "경로를 기본값으로 재설정",
            .diskFolderStructureHelp: "스캔 원본은 날짜/필름 종류/필름명 폴더로 정리됩니다.",
            .diskThumbnailCacheLabel: "썸네일 캐시",
            .diskClearThumbnailCache: "썸네일 캐시 지우기",
            .diskThumbnailCacheClearedStatus: "썸네일 캐시를 지웠습니다",
            .diskCacheSizeCalculating: "계산 중",
            .diskLibraryBackupLabel: "카탈로그 백업",
            .diskLibraryBackupNow: "지금 라이브러리 백업",
            .diskLibraryBackupCreatedStatus: "라이브러리 백업을 생성했습니다",
            .diskLibraryBackupFailedStatus: "라이브러리 백업에 실패했습니다",
            .libraryRestoredFormat: "라이브러리 복원: 사진 %d장",
            .libraryRecoveredFromBackupFormat: "백업에서 라이브러리 복구: 사진 %d장",
            .libraryCatalogMigratedFormat: "카탈로그 버전 %d에서 라이브러리 업그레이드: 사진 %d장",
            .libraryCatalogBlockedStatus: "라이브러리 카탈로그를 안전하게 열 수 없어 변경하지 않았습니다.",
            .libraryCatalogLockedStatus: "이 라이브러리는 다른 negaflow 프로세스에서 이미 열려 있습니다.",
            .libraryCatalogLockUnavailableStatus: "라이브러리 쓰기 잠금을 얻지 못해 카탈로그를 변경하지 않았습니다.",
            .libraryCatalogNewerVersionFormat: "이 라이브러리는 더 새로운 카탈로그 버전 %d을 사용하므로 변경하지 않았습니다.",
            .libraryCatalogMissingAuthoritativeDataStatus: "라이브러리 결함 보정 레시피가 불완전하고 유효한 백업도 없어 카탈로그를 변경하지 않았습니다.",
            .librarySelectedBackupAppliedFormat: "선택한 라이브러리 백업 복원: 사진 %d장",
            .libraryPendingRestoreFailedStatus: "예약한 라이브러리 복원을 적용하지 못해 예약 상태를 유지했습니다.",
            .diskLibraryBackupBrowse: "백업 보기",
            .libraryBackupEmpty: "백업 없음",
            .libraryBackupLoadFailed: "백업을 불러올 수 없습니다",
            .libraryBackupRefresh: "새로고침",
            .libraryBackupUnknownDate: "날짜 알 수 없음",
            .libraryBackupChecksummed: "체크섬 확인",
            .libraryBackupLegacy: "이전 형식",
            .libraryBackupIncompatible: "호환되지 않음",
            .libraryBackupDamaged: "손상됨",
            .libraryBackupCountsFormat: "사진 %d장 · 보정 레시피 %d개",
            .libraryBackupRestoreSelected: "선택한 백업 복원",
            .libraryBackupRestoreConfirmationTitle: "선택한 백업을 복원하시겠습니까?",
            .libraryBackupRestoreConfirmationMessage: "현재 라이브러리는 별도로 보존되며 다음 실행에 복원이 적용됩니다.",
            .libraryBackupScheduleRestore: "복원 예약",
            .libraryBackupRestorePending: "다음 실행에 복원됩니다",
            .libraryBackupCancelPending: "복원 예약 취소",
            .libraryBackupRestoreScheduleFailed: "복원을 예약할 수 없습니다",
            .done: "완료",
            .noScannerStatus: "스캐너 없음",
            .autoWhiteBalanceStatus: "자동 화이트 밸런스",
            .autoToneStatus: "자동 톤",
            .filmBaseSampleFailed: "필름 베이스 샘플 실패 — 원본을 불러올 수 없습니다",
            .filmBasePickedFormat: "필름 베이스 지정: %.3f %.3f %.3f",
            .noFramesToSync: "동기화할 사진 없음",
            .whiteBalanceSyncedFormat: "WB 동기화 완료: %d장",
            .grainMendBrushEditTitleFormat: "GrainMend · 브러시 · %d획",
            .grainMendAutoEditTitleFormat: "GrainMend · 자동 · %d개",
            .grainMendGuidedEditTitleFormat: "GrainMend · 가이드 · %d개",
            .brushEditSummary: "사용자 지정 영역 정밀 검출·복원",
            .defectsClearedStatus: "결함 제거 초기화",
            .removingDefectsStatus: "결함 제거 중",
            .removingDefectsFailedStatus: "결함 제거 실패",
            .imageLoadFailedFormat: "이미지 로드 실패: %@",
            .historyNameFormat: "기록 %d",
            .historyRecordedFormat: "기록 저장됨: %@",
            .historyAppliedFormat: "기록 적용됨: %@",
            .developSettingsCopiedFormat: "현상 설정 복사됨: %@",
            .noDevelopSettingsToPaste: "붙여넣을 현상 설정 없음",
            .chooseDevelopPasteScope: "붙여넣을 현상 설정 범위를 선택하세요",
            .developSettingsPasted: "현상 설정 붙여넣음",
            .developSettingsPartiallyPastedFormat: "현상 설정 부분 붙여넣음(%@)",
            .developSettingsPasteStatusFormat: "%@: %@ -> %@",
            .snapshotSavedFormat: "스냅샷 저장됨: %@",
            .snapshotAppliedFormat: "스냅샷 적용됨: %@",
            .snapshotCompareEnded: "A/B 비교 종료: 현재 설정",
            .snapshotComparingFormat: "A/B 비교 중: %@",
            .snapshotNameFormat: "스냅샷 %d",
            .exportingStatus: "내보내는 중",
            .exportCompleteFormat: "내보내기 완료 -> %@",
            .exportCompleteWithPairsFormat: "내보내기 완료 -> %@",
            .exportDestinationConflict: "내보내기 파일이 이미 있어 작업을 중단했습니다.",
            .exportFailedFormat: "내보내기 실패: %@",
            .importPanelPrompt: "가져오기",
            .importPanelMessage: "현상할 이미지를 선택하세요 (RAW/DNG/TIFF/PNG/JPG)",
            .noImportableImages: "가져올 수 있는 이미지가 없습니다 (지원: RAW/DNG/TIFF/PNG/JPG)",
            .importLibraryRegistrationFailedStatus: "가져온 이미지를 라이브러리에 등록하지 못했습니다",
            .importCompleteFormat: "%d장 가져오기 완료",
            .importCompleteUnsupportedFormat: "%d장 가져오기 완료 (%d장 미지원 형식 제외)",
            .importCompleteDuplicatesFormat: "%d장 가져오기 완료 (%d장 중복 제외)",
            .importCompleteUnsupportedDuplicatesFormat: "%d장 가져오기 완료 (%d장 미지원, %d장 중복 제외)",
            .importFolder: "폴더 가져오기",
            .importImageShort: "이미지",
            .importFolderShort: "폴더",
            .folderImportPanelMessage: "라이브러리에 추가할 폴더를 선택하세요. 폴더 안의 이미지 파일을 가져옵니다.",
            .folderImportCompleteFormat: "%d장을 %d개 폴더에서 가져오기 완료",
            .folderImportCompleteEmptyFormat: "빈 폴더 %d개 추가됨",
            .detectingDefectsStatus: "결함 검출 중",
            .detectingDefectsFailedStatus: "결함 검출 실패",
            .noDefectsStatus: "결함 없음",
            .automaticDefectFalsePositiveRiskStatus: "오탐지가 발생할 위험이 높습니다.",
            .settingsMemoryCacheSection: "메모리 캐시",
            .settingsMemoryCacheModeAutomatic: "자동",
            .settingsMemoryCacheModeManual: "수동",
            .settingsMemoryCacheInstalledMemoryFormat: "이 Mac의 메모리 %@",
            .settingsMemoryCacheCleanedRawLabel: "결함 제거 원본",
            .settingsMemoryCacheDevelopedLabel: "현상 결과",
            .settingsMemoryCacheFramesFormat: "%d장",
            .settingsMemoryCacheEstimateFormat: "최대 상주 약 %@ · 메모리의 %d%%",
            .settingsMemoryCacheAutomaticHelp: "설치 메모리에 맞춰 상한을 정합니다. 한도를 넘으면 오래된 프레임부터 내려놓고, 다시 열 때 재현상합니다.",
            .settingsMemoryCacheManualHelp: "직접 정한 값을 씁니다. 상한은 설치 메모리의 70%%입니다.",
            .settingsMemoryCacheResetToAutomatic: "자동값으로 되돌리기",
            .defectsCountFormat: "결함 %d개",
            .confidenceSummaryFormat: "%@ · 신뢰도 %.0f%%",
            .grainMendIREditTitleFormat: "GrainMend · IR · %d개",
            .infraredCleanDetectingStatus: "적외선 채널에서 결함 검출 중",
            .infraredCleanAppliedFormat: "적외선 채널로 결함 %d개를 제거했습니다",
            .infraredCleanNoDefectsStatus: "적외선 채널에서 결함이 발견되지 않았습니다",
            .infraredCleanSkippedBWStatus: "IR 결함 제거 건너뜀: 은염 흑백 필름은 적외선을 차단합니다",
            .infraredCleanCoverageAbortStatus: "IR 결함 제거 중단: 마스크가 과대합니다(필름 종류/IR 정렬 확인)",
            .infraredCleanFailedStatus: "IR 결함 검출에 실패했습니다",
            .demoModeStatus: "데모 모드",
            .scannerWaitingStatus: "스캐너 연결 대기 중",
            .scannerPluginMissingStartImportStatus: "스캐너 플러그인 없음 — 이미지 가져오기로 시작하세요",
            .scannerPluginMissingStatus: "스캐너 플러그인 없음",
            .scannerPluginApprovalRequiredStatus: "스캐너 플러그인 승인이 필요합니다",
            .scannerPluginTrustStoreUnavailableStatus: "스캐너 플러그인 승인 저장소를 사용할 수 없습니다",
            .scannerPluginApprovedStatus: "스캐너 플러그인을 승인했습니다",
            .scannerPluginApprovalFailedStatus: "스캐너 플러그인 승인에 실패했습니다",
            .scannerPluginApprovalRevokedStatus: "스캐너 플러그인 승인을 취소했습니다",
            .scannerAppConflictWarningFormat: "%@ 실행 중 — 종료한 뒤 스캐너를 다시 찾으세요.",
            .noScannerUseDemoStatus: "스캐너가 없습니다 — USB를 연결하거나 데모 모드를 켜세요.",
            .previewScanPreparing: "프리뷰 스캔 준비 중",
            .filmScanPreparing: "필름 스캔 준비 중",
            .frameScanCompleteFormat: "사진 %d 스캔 완료: %d x %d%@",
            .frameScanErrorFormat: "사진 %d 스캔 오류: %@",
            .framesScanCompleteFormat: "%d장 스캔 완료",
            .scanCanceled: "스캔 취소됨",
            .scanWorkflowPersistenceFailed: "스캔 상태를 라이브러리 카탈로그에 저장하지 못했습니다.",
            .scanWorkflowInvalidState: "스캔 작업 상태가 올바르지 않습니다.",
            .scanInterruptedFailureReason: "앱이 종료되어 하드웨어 캡처 완료를 확인하지 못했습니다.",
            .scanDeviceUnavailable: "선택한 스캐너를 확인할 수 없습니다.",
            .scanOutputFolderFailedFormat: "스캔 원본 폴더를 만들 수 없습니다: %@",
            .scanRollFilmMismatch: "활성 Roll의 필름 종류와 스캔 설정이 다릅니다.",
            .scanNumberRangeExceeded: "스캔 프레임 번호 한도를 초과했습니다.",
            .noActiveScanner: "활성 스캐너가 없습니다.",
            .noInstalledPlugins: "(설치된 플러그인 없음)",
            .scanProgressIdle: "대기 중",
            .scanProgressConnecting: "스캐너 연결 중",
            .scanProgressWarmingLamp: "램프 예열 중",
            .scanProgressReady: "스캔 준비됨",
            .scanProgressPreviewScanning: "프리뷰 스캔 중",
            .scanProgressWaitingForFilmHolder: "필름 홀더 대기 중",
            .scanProgressScanningRGB: "필름 스캔 중",
            .scanProgressScanningIR: "IR 채널 스캔 중",
            .scanProgressProcessingNegative: "스캔 데이터 처리 중",
            .scanProgressRenderingLook: "미리보기 현상 중",
            .scanProgressExporting: "내보내는 중",
            .scanProgressComplete: "스캔 완료",
            .scanProgressScannerBusy: "스캐너 사용 중",
            .scanProgressDisconnected: "스캐너 연결 끊김",
            .scanProgressError: "스캔 오류",
            .scanProgressBackendFallbackActive: "대체 백엔드 사용 중",
            .userPresetNameFormat: "프리셋 %d",
            .userPresetSavedFormat: "사용자 프리셋 저장됨: %@",
            .userPresetAppliedFormat: "사용자 프리셋 적용됨: %@",
            .userPresetDeletedFormat: "사용자 프리셋 삭제됨: %@",
            .virtualCopyCreatedFormat: "가상 사본 생성됨: %@",
            .proofCopyCreatedFormat: "프루프 사본 생성됨: %@",
            .proofCopyNameFormat: "%@ — 프루프: %@",
            .noSelection: "선택 안 함",
            .none: "없음",
            .baseSection: "베이스",
            .inspectorTabBasic: "기본",
            .inspectorTabEdit: "편집",
            .inspectorTabDefect: "GrainMend",
            .filmStock: "필름 스톡",
            .densitySourceFormat: "밀도 출처: %@ · 실측 베이스(가장자리/스포이드)가 있으면 항상 실측이 우선합니다",
            .lightSource: "광원",
            .lightSourceFallbackNote: "스캔에서 베이스가 실측되면 광원 프로파일은 무시됩니다(실측 우선). 베이스를 실측할 수 없는 컷에만 적용됩니다.",
            .autoMatch: "자동 매칭",
            .autoMatchRequiresValidatedProfile: "자동 매칭에는 기준 스캔 쌍으로 검증된 프로파일이 필요합니다.",
            .scannerProfileStatusDraft: "초안",
            .scannerProfileStatusRealOnly: "실제 스캔",
            .scannerProfileStatusPairedSmoke: "쌍 비교 시험",
            .scannerProfileStatusPairedValidated: "쌍 비교 검증 완료",
            .profile: "프로파일",
            .pick: "찍기",
            .pickBase: "베이스 스포이드",
            .pickBaseOnCanvas: "캔버스에서 베이스 클릭",
            .pickBaseHelp: "반전 전 원본에서 미노광 필름 베이스를 클릭해 Dmin을 실측합니다.",
            .baseRed: "베이스 R",
            .baseGreen: "베이스 G",
            .baseBlue: "베이스 B",
            .autoLevels: "자동 레벨",
            .autoColor: "자동 색상",
            .baseModeAuto: "자동",
            .baseModeFilm: "필름",
            .baseModeManual: "수동",
            .before: "이전",
            .unedited: "무보정",
            .after: "이후",
            .currentImage: "현재 이미지",
            .beforeSourceHelp: "이전 보기 소스 선택",
            .raw: "원본",
            .developed: "현상본",
            .compareSplitVertical: "좌우 이전/이후",
            .compareSplitHorizontal: "상하 이전/이후",
            .zoomOut: "축소",
            .zoomIn: "확대",
            .zoomPercentHelp: "확대율 입력",
            .fitToScreen: "맞춤",
            .actualSize: "원본 크기",
            .apply: "적용",
            .mode: "모드",
            .strength: "강도",
            .shadowHue: "어두운 영역 색조",
            .highlightHue: "밝은 영역 색조",
            .shadows: "어두운 영역",
            .midtones: "중간 톤",
            .highlights: "밝은 영역",
            .hue: "색조",
            .saturationAbbrev: "채도",
            .luminance: "광도",
            .blending: "혼합",
            .balance: "균형",
            .canvasBackgroundMenu: "배경색",
            .debugBadgeFormat: "디버그 · %@",
            .basePickerOverlayPrompt: "미노광 필름 베이스(사진 사이/가장자리)를 클릭하세요 · Esc 취소",
            .scannerLabel: "스캐너",
            .resolution: "해상도",
            .preview: "프리뷰",
            .bitDepth: "심도",
            .colorMode: "모드",
            .perforation: "퍼포레이션",
            .filmFrameFormat: "프레임 규격",
            .hardwareScanArea: "하드웨어 스캔 영역",
            .scanAreaWidth: "너비",
            .scanAreaHeight: "높이",
            .framesFormat: "사진: %d",
            .flatbedFramesFormat: "선택: %d",
            .flatbedFrameFormat: "프레임 %d",
            .flatbedAddFrame: "프레임 추가",
            .flatbedPreviewRequired: "프리뷰를 실행하고 프레임을 하나 이상 선택하세요.",
            .flatbedGeometryMismatch: "스캐너가 선택한 영역과 다른 비율의 이미지를 반환했습니다.",
            .multiExposure: "다중 노출",
            .infrared: "적외선(IR)",
            .infraredHelp: "먼지·스크래치 감지를 위해 적외선 채널로 스캔합니다. IR 지원 기기에서만 표시됩니다.",
            .scanSection: "스캔",
            .cancel: "취소",
            .scan: "스캔",
            .importSource: "가져오기",
            .scanNext: "다음 스캔",
            .scanCountFormat: "스캔 x%d",
            .scannerSearching: "스캐너를 찾는 중 — USB 연결을 확인하세요.",
            .scannerPluginMissingTitle: "스캐너 플러그인이 설치되지 않았습니다.",
            .scannerPluginMissingBody: "필름 스캐너는 라이선스 분리를 위해 별도 플러그인으로 제공됩니다. 설치하면 여기에서 스캔할 수 있습니다. 지금은 이미지 가져오기로 현상을 시작할 수 있습니다.",
            .scannerPluginApprovalTitle: "스캐너 플러그인 승인",
            .scannerPluginVersion: "버전",
            .scannerPluginLicense: "라이선스",
            .scannerPluginManifestPath: "Manifest 경로",
            .scannerPluginManifestHash: "Manifest SHA-256",
            .scannerPluginExecutableHash: "실행 파일 SHA-256",
            .scannerPluginApprove: "승인",
            .scannerPluginRevokeApproval: "승인 취소",
            .scannerPluginApproved: "승인됨",
            .scannerPluginApprovalRequired: "승인 필요",
            .scannerPluginChangedApprovalRequired: "변경됨 · 재승인 필요",
            .scannerPluginInvalidIdentity: "신뢰 ID 오류",
            .scannerPluginTrustStoreUnavailable: "승인 저장소 사용 불가",
            .scannerPluginNotReported: "보고되지 않음",
            .scannerSimulator: "스캐너 시뮬레이터",
            .scannerSimulatorHelp: "플러그인 없이 스캔 워크플로우를 시연하는 내장 시뮬레이터",
            .scannerTruth: "스캐너 정보",
            .transparency: "투과 원고",
            .brightness: "밝기",
            .contrast: "대비",
            .capabilityUnavailable: "사용 불가",
            .capabilityAvailable: "사용 가능",
            .capabilityWaiting: "기능 응답을 아직 받지 못했습니다.",
            .multiExposurePreviewHelp: "프리뷰 스캔에서는 다중 노출을 사용하지 않습니다.",
            .multiExposureUnsupportedHelp: "현재 백엔드가 실제 하드웨어 노출 제어를 지원하지 않아 비활성화되었습니다.",
            .multiExposureSupportedHelp: "백엔드가 노출 제어를 지원하는 장치에서만 여러 스캔을 결합합니다.",
            .exportMainFlatMaster: "MAIN 무보정본",
            .exportOriginalRawTIFF: "원본 TIFF",
            .exportSidecar: "사이드카 (JSON + XMP)",
            .colorScannerInput: "스캐너 에뮬레이션",
            .colorWorking: "작업 공간",
            .colorMonitor: "모니터",
            .colorExport: "내보내기",
            .colorSoftProof: "소프트 프루프",
            .colorGamutWarning: "색역 경고",
            .colorSampler: "RGB/Lab/HSV 샘플러",
            .colorClippingOverlay: "클리핑 오버레이",
            .choose: "선택",
            .all: "모두",
            .red: "빨강",
            .orange: "주황",
            .yellow: "노랑",
            .green: "초록",
            .aqua: "바다색",
            .blue: "파랑",
            .purple: "자주",
            .magenta: "자홍",
            .basicTone: "기본 톤",
            .exposure: "노출",
            .toneHighlights: "밝은 영역",
            .whites: "흰색 계열",
            .blacks: "검정 계열",
            .density: "농도",
            .toneCurve: "톤 곡선",
            .lights: "밝은 톤",
            .darks: "어두운 톤",
            .color: "색상",
            .warmth: "색온도",
            .tint: "틴트",
            .vibrance: "생동감",
            .saturation: "채도",
            .colorDepth: "색 깊이",
            .colorMixer: "컬러 믹서",
            .colorGrading: "컬러 그레이딩",
            .bwToning: "흑백 토닝",
            .calibration: "캘리브레이션",
            .redPrimary: "빨강 원색",
            .greenPrimary: "초록 원색",
            .bluePrimary: "파랑 원색",
            .detailEffects: "디테일 및 효과",
            .noiseReduction: "노이즈 감소",
            .noiseReductionStrength: "NR 강도",
            .noiseReductionLuminance: "NR 명도",
            .noiseReductionColor: "NR 색상",
            .noiseReductionDarkTones: "NR 어두운 톤",
            .noiseReductionDetail: "NR 디테일",
            .noiseReductionGrainProtect: "NR 그레인 보호",
            .grain: "그레인",
            .sharpness: "선명도",
            .clarity: "부분 대비",
            .halation: "할레이션",
            .vignette: "비네트",
            .developerDebug: "개발자 디버그",
            .developerMode: "개발자 모드",
            .debugOverlay: "디버그 오버레이",
            .stage: "단계",
            .full: "전체",
            .undoLastStroke: "마지막 스트로크 취소",
            .clearPaintedStrokes: "칠한 스트로크 지우기",
            .resetAppliedDefects: "적용된 결함 제거 전체 초기화",
            .removeDefects: "결함 제거",
            .resetAdjustmentsHelp: "편집(회전/크롭)을 제외한 모든 보정 값을 초기화합니다.",
            .autoToneHelp: "자동 톤 Command-U — 히스토그램으로 노출, 대비, 밝은 영역, 어두운 영역, 흰색 계열, 검정 계열, 생동감을 보정합니다.",
            .autoWhiteBalanceHelp: "자동 화이트 밸런스 Shift-Command-U — 그레이 월드 방식으로 색온도와 틴트를 중립화합니다.",
            .copy: "복사",
            .paste: "붙여넣기",
            .copyDevelopSettingsHelp: "현재 사진 현상 설정 복사",
            .pasteDevelopSettingsHelp: "복사한 현상 설정 붙여넣기",
            .pasteScope: "붙여넣기 범위",
            .pasteScopeHelp: "붙여넣을 현상 설정 범위 선택",
            .allSettings: "모든 설정",
            .copyPaste: "복사 / 붙여넣기",
            .snapshot: "스냅샷",
            .noSnapshots: "스냅샷 없음",
            .save: "저장",
            .saveSnapshotHelp: "현재 현상 상태를 스냅샷으로 저장",
            .applySnapshotHelp: "선택한 스냅샷 적용",
            .compareSnapshotHelp: "현재 설정과 선택한 스냅샷 임시 비교",
            .current: "현재",
            .noHistory: "기록 없음",
            .history: "기록",
            .record: "기록",
            .recordHistoryHelp: "현재 현상 상태를 기록으로 저장",
            .applyHistoryHelp: "선택한 기록 상태 적용",
            .intensity: "강도",
            .geometry: "편집",
            .original: "원본",
            .custom: "사용자 정의",
            .aspectRatio: "종횡비",
            .unlockCropAspect: "크롭 비율 잠금 해제",
            .lockCropAspect: "크롭 비율 잠금",
            .cropAspectLocked: "크롭 비율 잠김",
            .cropAspectUnlocked: "크롭 비율 해제",
            .angle: "각도",
            .cropArea: "크롭 영역",
            .rotateLeft: "왼쪽으로 90도 회전",
            .rotateRight: "오른쪽으로 90도 회전",
            .resetTransform: "변형 초기화",
            .resetPhotoAngle: "사진 각도 초기화",
            .brushDefect: "브러시",
            .guidedDefect: "가이드",
            .brushDefectHelp: "브러시 — 먼지/스크래치 위를 칠한 뒤 Enter 또는 결함 제거",
            .guidedDefectHelp: "가이드 — 영역 드래그 후 Enter 또는 결함 제거",
            .cloneStamp: "복제 도장",
            .cloneStampHelp: "복제 도장 — ⌥ 클릭으로 소스를 지정한 뒤 드래그해 복제",
            .cloneStampSourceHint: "⌥ 클릭으로 복제 소스 지정",
            .cloneStampSize: "크기",
            .cloneStampHardness: "경도",
            .cloneStampEditTitleFormat: "복제 도장 %dpx",
            .cloneStampEditSummary: "지정한 소스 픽셀 복제",
            .flipHorizontal: "좌우 반전",
            .flipVertical: "상하 반전",
            .baseReadoutFormat: "base %.2f %.2f %.2f",
            .batchFrameProgressFormat: "사진 %d/%d",
            .rating: "별점",
            .resetRating: "별점 초기화",
            .ratingAccessibilityFormat: "별점 %d",
            .histogram: "히스토그램",
            .shadowTone: "어두운 영역",
            .highlightTone: "밝은 영역",
            .rgbChannelOverlay: "RGB 채널 오버레이",
            .redChannel: "빨강 채널",
            .greenChannel: "초록 채널",
            .blueChannel: "파랑 채널",
            .clippingChannelsFormat: "클리핑 %@",
            .resetSectionFormat: "%@ 초기화",
            .sliderKeyboardHelp: "방향키로 0.01, Shift+방향키로 0.10 조정",
            .baseMetricsFormat: "dmin %@ · dmax %@",
            .notAvailableAbbrev: "n/a",
            .softProofSummaryFormat: "%@, %@",
            .softProofProfileOnly: "프로파일",
            .softProofPaperAndBlack: "용지 + 검정 잉크",
            .softProofInvalidICC: "선택한 ICC 프로파일은 RGB 소프트 프루프에 사용할 수 없습니다.",
            .printOutputProfileRequired: "PRINT 내보내기에는 유효한 RGB 프린터 ICC 프로파일이 필요합니다.",
            .developingFramesFormat: "현상 중 %d장",
            .generatingPreviewFormat: "프리뷰 생성 중 (%dpx)",
            .generatingSettledPreviewFormat: "정착 프리뷰 생성 중 (%dpx)",
            .defectLayers: "GrainMend 레이어",
            .disableLayer: "레이어 끄기(복원 전 보기)",
            .enableLayer: "레이어 켜기(복원 적용)",
            .hideMask: "마스크 숨기기",
            .showMask: "마스크 표시",
            .deleteLayer: "레이어 삭제",
            .defectDust: "먼지",
            .defectPinhole: "핀홀",
            .defectScratchHorizontal: "가로 스크래치",
            .defectScratchVertical: "세로 스크래치",
            .defectScratchDiagonal: "대각 스크래치",
            .defectEmulsionDamage: "유제 손상",
            .defectMicroSpeck: "미세 입자",
            .autoDefect: "자동",
            .autoDefectHelp: "자동 — 전체 프레임을 자동 검출 후 결함 제거",
            .frameCountFormat: "%d장",
            .frameDisplayFormat: "사진 %d",
            .frameCopyDisplayFormat: "사진 %d 사본 %d",
            .frameCompactCopyDisplayFormat: "사진 %d 사본%d",
            .namedFrameCopyDisplayFormat: "%@ 사본 %d",
            .dpiUnspecified: "DPI 미지정",
            .ratingStarFormat: "별 %d개",
            .unrated: "별점 없음",
            .unflagged: "플래그 없음",
            .picked: "선택",
            .rejected: "제외",
            .selectionSummaryFormat: "%@ · %@",
            .selectionCountsFormat: "%d 선택 · %d 제외",
            .starHelpFormat: "별 %d개",
            .clearPick: "선택 해제",
            .clearReject: "제외 해제",
            .quickExportHelpFormat: "%@ — %@ · %d dpi -> %@",
            .target: "타깃",
            .filmProfile: "필름 프로필",
            .look: "룩",
            .film: "필름",
            .process: "프로세스",
            .filmName: "필름명",
            .scanFolderName: "폴더명",
            .chooseScanFolder: "스캔 폴더 선택",
            .untitledFilm: "무제 필름",
            .userPreset: "사용자 프리셋",
            .noUserPresets: "사용자 프리셋 없음",
            .saveUserPresetHelp: "현재 현상 설정을 사용자 프리셋으로 저장",
            .applyUserPresetHelp: "선택한 사용자 프리셋 적용",
            .deleteUserPresetHelp: "선택한 사용자 프리셋 삭제",
            .delete: "삭제",
            .removeFromLibrary: "제거",
            .libraryRemovalUndoAvailableFormat: "카탈로그 항목 %d개 제거 · 되돌리기 가능",
            .libraryRemovalRestoredFormat: "카탈로그 항목 %d개 복원",
            .scanProvenanceProtectedStatus: "이 스캔 원본은 캡처 기록에 포함되어 있어 아직 이동하거나 제거할 수 없습니다.",
            .sourceDeletionPlanChangedStatus: "원본 연결 상태가 변경되었습니다. 삭제 대상을 다시 확인해 주세요.",
            .sourceDeletionUnavailableStatus: "카탈로그가 준비될 때까지 원본 파일을 삭제할 수 없습니다.",
            .sourceDeletionMoveFailedStatus: "원본 파일을 휴지통으로 이동하지 못했습니다. 카탈로그는 변경하지 않았습니다.",
            .sourceDeletionCatalogFailedStatus: "카탈로그를 커밋하지 못해 원본 파일을 복원했습니다.",
            .sourceDeletionRollbackFailedStatus: "카탈로그는 변경하지 않았지만 일부 원본 파일을 복원하지 못했습니다. 휴지통에서 복구해 주세요.",
            .moveSourceToTrash: "원본 파일을 휴지통으로 이동",
            .sourceOffline: "오프라인",
            .locateOriginal: "원본 찾기",
            .locateMissingFolder: "누락 폴더 찾기",
            .newFolder: "새 폴더",
            .create: "생성",
            .showInFinder: "Finder에서 보기",
            .renameFolder: "이름 변경",
            .moveToFolder: "폴더로 이동",
            .moveItemsHere: "여기로 이동",
            .sourceMoveCompleteFormat: "원본 파일 %d개를 이동했습니다.",
            .sourceMoveFailedStatus: "원본 파일을 이동하지 못했습니다. 변경 사항을 되돌렸습니다.",
            .sourceMoveCatalogFailedStatus: "카탈로그를 커밋하지 못해 원본 파일을 원래 위치로 복원했습니다.",
            .sourceMoveCollisionStatus: "대상 폴더에 같은 이름의 파일 또는 폴더가 있습니다.",
            .folderCreatedStatusFormat: "폴더를 생성했습니다: %@",
            .folderCreateFailedStatus: "폴더를 생성하지 못했습니다.",
            .locateSourcePanelMessageFormat: "마지막 원본 위치: %@",
            .locateFolderPanelMessageFormat: "마지막 폴더 위치: %@",
            .sourceRelinkInvalid: "선택한 파일은 읽을 수 있는 지원 이미지가 아닙니다.",
            .sourceRelinkedFormat: "카탈로그 항목 %d개를 다시 연결했습니다.",
            .deleteSourceConfirmationTitle: "원본 파일을 휴지통으로 이동할까요?",
            .deleteSourceConfirmationMessageFormat: "카탈로그 항목 %d개가 원본 파일 %d개를 공유합니다. 모두 negaflow에서 제거됩니다. %@",
            .virtualCopy: "가상 사본",
            .virtualCopyHelp: "현재 원본 사진을 공유하는 비파괴 사본 생성",
            .proofCopy: "프루프 사본",
            .proofCopyHelp: "선택한 프루프 프로파일에 연결된 비파괴 사본 생성",
            .dragDefectRegion: "결함 영역을 드래그하세요",
            .undo: "되돌리기",
            .undoDefectRemovalHelp: "마지막 결함 제거 편집 취소",
            .defectsCountExcludedFormat: "결함 %d개 (제외 %d)",
            .toneCurveEditorHelp: "클릭으로 점 추가 · 드래그로 이동 · 더블클릭으로 삭제",
            .reset: "초기화",
            .previousFrame: "이전 사진",
            .nextFrame: "다음 사진",
            .noImages: "이미지 없음",
            .libraryFiles: "파일",
            .libraryAllPhotos: "전체 보기",
            .libraryAllShort: "전체",
            .libraryFolders: "폴더별",
            .libraryFilmType: "필름 종류",
            .libraryOffline: "오프라인",
            .libraryCollections: "컬렉션",
            .librarySmartCollections: "스마트 컬렉션",
            .librarySavedSearches: "저장된 검색",
            .libraryNewCollection: "새 컬렉션",
            .libraryNewSmartCollection: "새 스마트 컬렉션",
            .librarySaveCurrentSearch: "현재 검색 저장",
            .libraryCollectionName: "컬렉션 이름",
            .librarySearchName: "검색 이름",
            .libraryAddToCollection: "컬렉션에 추가",
            .libraryRemoveFromCollection: "컬렉션에서 제거",
            .libraryInvalidStoredSearch: "저장된 검색을 읽을 수 없음",
            .librarySearchPlaceholder: "사진 검색",
            .libraryClearSearch: "검색 지우기",
            .libraryResultCountFormat: "사진 %d장 / 전체 %d장",
            .filterCurrentRoll: "현재 롤",
            .filterMinimumRatingFormat: "별점 %d 이상",
            .filterInfrared: "적외선",
            .filterDefectRecipe: "보정 레시피",
            .filterUnvalidatedProfile: "미검증 프로파일",
            .filterMetadataUnknown: "메타데이터 상태 미확인",
            .libraryFilters: "필터",
            .clearFilters: "필터 지우기",
            .exportFileSettings: "파일",
            .exportQualitySettings: "품질",
            .exportSourceSettings: "소스",
            .noMatchingPhotos: "일치하는 사진 없음",
            .noLibraryFolders: "폴더 없음",
            .libraryRefreshStatusFormat: "라이브러리 새로고침: 신규 %d개 · 재연결 %d개 · 오프라인 %d개",
            .sortBy: "정렬",
            .ascending: "오름차순",
            .descending: "내림차순",
            .sortInputOrder: "입력순",
            .sortTime: "시간순",
            .sortName: "이름순",
            .sortFlag: "플래그",
            .sortRating: "별점",
            .sortSize: "크기순",
            .renamePhoto: "이름 변경",
            .photoName: "사진명",
            .rename: "변경",
            .filmstripHeightHelp: "필름스트립 높이 조절",
            .frameCardSizeHelp: "사진 카드 크기",
            .developTargetMain: "MAIN",
            .developTargetPrint: "PRINT",
            .filmTypeColorNegative: "컬러 네거티브",
            .filmTypeSlide: "슬라이드",
            .filmTypeBWNegative: "흑백 네거티브",
            .filmTypeBWPositive: "흑백 포지티브",
            .targetFilmSummaryFormat: "%@ · %@",
            .frameAccessibilityFormat: "%@, %@, %@",
            .dynamicRangeChannel: "DR",
            .rgb: "RGB",
            .redChannelShort: "R",
            .greenChannelShort: "G",
            .blueChannelShort: "B",
    ]
}
