import Foundation

extension AppLocalization {
    static let japanesePhraseTable: [AppLocalizedPhrase: String] = [
        .idleStatus: "待機中",
        .settingsDiskTab: "ディスク",
        .diskLocationICloud: "iCloud",
        .diskLocationDesktop: "デスクトップ",
        .diskLocationSpecificFolder: "フォルダー",
        .diskLocationCustom: "カスタム",
        .settingsScanTab: "スキャン",
        .settingsDefaultScanRotationPicker: "スキャンの既定の向き",
        .settingsDefaultScanRotationHelp: "向きが未設定の新規スキャンに適用されます。スキャナー原稿は通常180°反転して保存されます。",
        .diskRootFolderLabel: "negaflowフォルダー",
        .diskThumbnailsFolderLabel: "サムネイルフォルダー",
        .diskImportedSourcesFolderLabel: "読み込んだ元ファイルの移動先",
        .diskCleanedRawFolderLabel: "補正画像キャッシュフォルダー",
        .diskScanPreviewFolderLabel: "スキャンプレビューキャッシュフォルダー",
        .diskExportFolderLabel: "書き出しフォルダー",
        .diskResetPathsButton: "パスをデフォルトに戻す",
        .diskFolderStructureHelp: "スキャンした元画像は日付/フィルム種類/フィルム名で整理されます。",
        .diskThumbnailCacheLabel: "サムネイルキャッシュ",
        .diskClearThumbnailCache: "サムネイルキャッシュを消去",
        .diskThumbnailCacheClearedStatus: "サムネイルキャッシュを消去しました",
        .diskCacheSizeCalculating: "計算中",
        .diskLibraryBackupLabel: "カタログのバックアップ",
        .diskLibraryBackupNow: "今すぐライブラリをバックアップ",
        .diskLibraryBackupCreatedStatus: "ライブラリのバックアップを作成しました",
        .diskLibraryBackupFailedStatus: "ライブラリのバックアップに失敗しました",
        .libraryRestoredFormat: "ライブラリを復元: %d枚",
        .libraryRecoveredFromBackupFormat: "バックアップからライブラリを復元: %d枚",
        .libraryCatalogMigratedFormat: "カタログバージョン%dからライブラリを更新: %d枚",
        .libraryCatalogBlockedStatus: "ライブラリカタログを安全に開けなかったため、変更せずに保持しました。",
        .libraryCatalogLockedStatus: "このライブラリは別のnegaflowプロセスですでに開かれています。",
        .libraryCatalogLockUnavailableStatus: "ライブラリの書き込みロックを取得できなかったため、カタログは変更されていません。",
        .libraryCatalogNewerVersionFormat: "このライブラリは新しいカタログバージョン%dを使用しているため、変更せずに保持しました。",
        .libraryCatalogMissingAuthoritativeDataStatus: "ライブラリの修復レシピが不足しており、有効なバックアップも見つからないため、カタログは変更せずに保持しました。",
        .librarySelectedBackupAppliedFormat: "選択したライブラリのバックアップを復元: %d枚",
        .libraryPendingRestoreFailedStatus: "予約したライブラリの復元を適用できなかったため、予約状態を保持しました。",
        .diskLibraryBackupBrowse: "バックアップを表示",
        .libraryBackupEmpty: "バックアップなし",
        .libraryBackupLoadFailed: "バックアップを読み込めません",
        .libraryBackupRefresh: "再読み込み",
        .libraryBackupUnknownDate: "日付不明",
        .libraryBackupChecksummed: "チェックサム確認済み",
        .libraryBackupLegacy: "旧形式",
        .libraryBackupIncompatible: "互換性なし",
        .libraryBackupDamaged: "破損",
        .libraryBackupCountsFormat: "%d枚 · 修復レシピ%d件",
        .libraryBackupRestoreSelected: "選択したバックアップを復元",
        .libraryBackupRestoreConfirmationTitle: "選択したバックアップを復元しますか？",
        .libraryBackupRestoreConfirmationMessage: "現在のライブラリは別途保存され、次回起動時に復元が適用されます。",
        .libraryBackupScheduleRestore: "復元を予約",
        .libraryBackupRestorePending: "次回起動時に復元",
        .libraryBackupCancelPending: "復元予約を取り消す",
        .libraryBackupRestoreScheduleFailed: "復元を予約できません",
        .done: "完了",
        .noScannerStatus: "スキャナーなし",
        .autoWhiteBalanceStatus: "自動ホワイトバランス",
        .autoToneStatus: "自動トーン",
        .filmBaseSampleFailed: "フィルムベースを取得できません — 元画像が読み込まれていません",
        .filmBasePickedFormat: "フィルムベースを設定: %.3f %.3f %.3f",
        .noFramesToSync: "同期するコマがありません",
        .whiteBalanceSyncedFormat: "ホワイトバランスを同期しました: %dコマ",
        .grainMendBrushEditTitleFormat: "GrainMend · ブラシ · %dストローク",
        .grainMendAutoEditTitleFormat: "GrainMend · 自動 · %d件",
        .grainMendGuidedEditTitleFormat: "GrainMend · ガイド · %d範囲",
        .brushEditSummary: "指定した範囲を精密に検出して修復",
        .defectsClearedStatus: "ゴミ・キズ除去をリセットしました",
        .removingDefectsStatus: "ゴミ・キズを除去中",
        .removingDefectsFailedStatus: "ゴミ・キズ除去に失敗しました",
        .imageLoadFailedFormat: "画像を読み込めませんでした: %@",
        .historyNameFormat: "履歴 %d",
        .historyRecordedFormat: "履歴に記録しました: %@",
        .historyAppliedFormat: "履歴を適用しました: %@",
        .developSettingsCopiedFormat: "現像設定をコピーしました: %@",
        .noDevelopSettingsToPaste: "ペーストできる現像設定がありません",
        .chooseDevelopPasteScope: "ペーストする現像設定の範囲を選択してください",
        .developSettingsPasted: "現像設定をペーストしました",
        .developSettingsPartiallyPastedFormat: "現像設定を一部ペーストしました (%@)",
        .developSettingsPasteStatusFormat: "%@: %@ -> %@",
        .snapshotSavedFormat: "スナップショットを保存しました: %@",
        .snapshotAppliedFormat: "スナップショットを適用しました: %@",
        .snapshotCompareEnded: "A/B 比較を終了: 現在の設定",
        .snapshotComparingFormat: "A/B 比較中: %@",
        .snapshotNameFormat: "スナップショット %d",
        .exportingStatus: "書き出し中",
        .exportCompleteFormat: "書き出しが完了しました -> %@",
        .exportCompleteWithPairsFormat: "書き出しが完了しました -> %@",
        .exportDestinationConflict: "出力ファイルがすでに存在するため、書き出しを中止しました。",
        .exportFailedFormat: "書き出しに失敗しました: %@",
        .importPanelPrompt: "読み込む",
        .importPanelMessage: "現像する画像を選択してください (RAW/DNG/TIFF/PNG/JPG)",
        .noImportableImages: "読み込める画像がありません (対応形式: RAW/DNG/TIFF/PNG/JPG)",
        .importLibraryRegistrationFailedStatus: "読み込んだ画像をライブラリに登録できませんでした",
        .importCompleteFormat: "%d枚の画像を読み込みました",
        .importCompleteUnsupportedFormat: "%d枚の画像を読み込みました (未対応の %d ファイルをスキップ)",
        .importCompleteDuplicatesFormat: "%d枚の画像を読み込みました (重複 %d 件をスキップ)",
        .importCompleteUnsupportedDuplicatesFormat: "%d枚の画像を読み込みました (未対応 %d 件、重複 %d 件をスキップ)",
        .importFolder: "フォルダーを読み込む",
        .importImageShort: "画像",
        .importFolderShort: "フォルダー",
        .folderImportPanelMessage: "ライブラリに追加するフォルダーを選択してください。中の画像ファイルを読み込みます。",
        .folderImportCompleteFormat: "%d枚の画像を%d個のフォルダーから読み込みました",
        .folderImportCompleteEmptyFormat: "空のフォルダーを%d個追加しました",
        .detectingDefectsStatus: "ゴミ・キズを検出中",
        .detectingDefectsFailedStatus: "ゴミ・キズの検出に失敗しました",
        .noDefectsStatus: "ゴミ・キズは見つかりませんでした",
        .automaticDefectFalsePositiveRiskStatus: "誤検出が発生する可能性が高いです。",
        .settingsMemoryCacheSection: "メモリキャッシュ",
        .settingsMemoryCacheModeAutomatic: "自動",
        .settingsMemoryCacheModeManual: "手動",
        .settingsMemoryCacheInstalledMemoryFormat: "この Mac のメモリ %@",
        .settingsMemoryCacheCleanedRawLabel: "傷除去済みオリジナル",
        .settingsMemoryCacheDevelopedLabel: "現像結果",
        .settingsMemoryCacheFramesFormat: "%d 枚",
        .settingsMemoryCacheEstimateFormat: "最大約 %@ 常駐 · メモリの %d%%",
        .settingsMemoryCacheAutomaticHelp: "搭載メモリに合わせて上限を決めます。上限を超えたフレームは古いものから解放し、再度開いたときに再現像します。",
        .settingsMemoryCacheManualHelp: "指定した値を使います。上限は搭載メモリの 70%% です。",
        .settingsMemoryCacheResetToAutomatic: "自動値に戻す",
        .defectsCountFormat: "ゴミ・キズ %d件",
        .confidenceSummaryFormat: "%@ · 確度 %.0f%%",
        .grainMendIREditTitleFormat: "GrainMend · IR · %d件",
        .infraredCleanDetectingStatus: "赤外線チャンネルからゴミ・キズを検出中",
        .infraredCleanAppliedFormat: "赤外線チャンネルでゴミ・キズを %d件除去しました",
        .infraredCleanNoDefectsStatus: "赤外線チャンネルにゴミ・キズは見つかりませんでした",
        .infraredCleanSkippedBWStatus: "赤外線クリーニングをスキップ: 銀塩モノクロフィルムは赤外線を透過しません",
        .infraredCleanCoverageAbortStatus: "赤外線クリーニングを中止: マスクが大きすぎます（フィルムタイプまたは IR 位置合わせを確認）",
        .infraredCleanFailedStatus: "赤外線でのゴミ・キズ検出に失敗しました",
        .demoModeStatus: "デモモード",
        .scannerWaitingStatus: "スキャナーの接続を待機中",
        .scannerPluginMissingStartImportStatus: "スキャナープラグインがありません — 画像の読み込みから始めてください",
        .scannerPluginMissingStatus: "スキャナープラグインなし",
        .scannerPluginApprovalRequiredStatus: "スキャナープラグインの承認が必要です",
        .scannerPluginTrustStoreUnavailableStatus: "スキャナープラグインの承認ストレージを使用できません",
        .scannerPluginApprovedStatus: "スキャナープラグインを承認しました",
        .scannerPluginApprovalFailedStatus: "スキャナープラグインを承認できませんでした",
        .scannerPluginApprovalRevokedStatus: "スキャナープラグインの承認を取り消しました",
        .scannerAppConflictWarningFormat: "%@ が実行中です — 終了してからスキャナーを再検出してください。",
        .noScannerUseDemoStatus: "スキャナーが見つかりません — USB を接続するか、デモモードをオンにしてください。",
        .previewScanPreparing: "プレビュースキャンを準備中",
        .filmScanPreparing: "フィルムスキャンを準備中",
        .frameScanCompleteFormat: "コマ %d のスキャンが完了: %d x %d%@",
        .frameScanErrorFormat: "コマ %d のスキャンエラー: %@",
        .framesScanCompleteFormat: "%dコマをスキャンしました",
        .scanCanceled: "スキャンをキャンセルしました",
        .scanWorkflowPersistenceFailed: "スキャン状態をライブラリカタログに保存できませんでした。",
        .scanWorkflowInvalidState: "スキャンワークフローの状態が正しくありません。",
        .scanInterruptedFailureReason: "アプリが終了したため、ハードウェアキャプチャの完了を確認できませんでした。",
        .scanDeviceUnavailable: "選択したスキャナーを確認できませんでした。",
        .scanOutputFolderFailedFormat: "スキャン原本フォルダを作成できませんでした: %@",
        .scanRollFilmMismatch: "有効なRollのフィルム種類とスキャン設定が一致しません。",
        .scanNumberRangeExceeded: "スキャンフレーム番号の上限を超えました。",
        .noActiveScanner: "使用中のスキャナーがありません。",
        .noInstalledPlugins: "（インストール済みのプラグインなし）",
        .scanProgressIdle: "待機中",
        .scanProgressConnecting: "スキャナーに接続中",
        .scanProgressWarmingLamp: "ランプを予熱中",
        .scanProgressReady: "スキャン準備完了",
        .scanProgressPreviewScanning: "プレビュースキャン中",
        .scanProgressWaitingForFilmHolder: "フィルムホルダーを待機中",
        .scanProgressScanningRGB: "フィルムをスキャン中",
        .scanProgressScanningIR: "赤外線チャンネルをスキャン中",
        .scanProgressProcessingNegative: "スキャンデータを処理中",
        .scanProgressRenderingLook: "プレビュー現像を生成中",
        .scanProgressExporting: "書き出し中",
        .scanProgressComplete: "スキャン完了",
        .scanProgressScannerBusy: "スキャナーは使用中です",
        .scanProgressDisconnected: "スキャナーの接続が解除されました",
        .scanProgressError: "スキャンエラー",
        .scanProgressBackendFallbackActive: "代替バックエンドを使用中",
        .userPresetNameFormat: "プリセット %d",
        .userPresetSavedFormat: "ユーザープリセットを保存しました: %@",
        .userPresetAppliedFormat: "ユーザープリセットを適用しました: %@",
        .userPresetDeletedFormat: "ユーザープリセットを削除しました: %@",
        .virtualCopyCreatedFormat: "仮想コピーを作成しました: %@",
        .proofCopyCreatedFormat: "校正コピーを作成しました: %@",
        .proofCopyNameFormat: "%@ — 校正: %@",
        .noSelection: "選択なし",
        .none: "なし",
        .baseSection: "ベース",
        .inspectorTabBasic: "基本",
        .inspectorTabEdit: "編集",
        .inspectorTabDefect: "GrainMend",
        .filmStock: "フィルム銘柄",
        .densitySourceFormat: "濃度ソース: %@ · 実測ベース（コマ間/スポイト）が常に優先されます。",
        .lightSource: "光源",
        .lightSourceFallbackNote: "スキャンからベースを実測できた場合、光源プロファイルは無視されます(実測優先)。ベースを実測できないカットにのみ適用されます。",
        .autoMatch: "自動マッチング",
        .autoMatchRequiresValidatedProfile: "自動マッチングには、参照スキャンのペアで検証済みのプロファイルが必要です。",
        .scannerProfileStatusDraft: "下書き",
        .scannerProfileStatusRealOnly: "実スキャン",
        .scannerProfileStatusPairedSmoke: "ペア試験",
        .scannerProfileStatusPairedValidated: "ペア検証済み",
        .profile: "プロファイル",
        .pick: "採取",
        .pickBase: "ベーススポイト",
        .pickBaseOnCanvas: "キャンバス上でベースをクリック",
        .pickBaseHelp: "反転前の元データで未露光のフィルムベースをクリックし、Dmin を実測します。",
        .baseRed: "ベース R",
        .baseGreen: "ベース G",
        .baseBlue: "ベース B",
        .autoLevels: "自動レベル補正",
        .autoColor: "自動カラー補正",
        .baseModeAuto: "自動",
        .baseModeFilm: "フィルム",
        .baseModeManual: "手動",
        .before: "補正前",
        .unedited: "補正なし",
        .after: "補正後",
        .currentImage: "現在の画像",
        .beforeSourceHelp: "補正前のソースを選択",
        .raw: "元画像",
        .developed: "現像後",
        .compareSplitVertical: "左右で補正前/補正後を比較",
        .compareSplitHorizontal: "上下で補正前/補正後を比較",
        .zoomOut: "縮小",
        .zoomIn: "拡大",
        .zoomPercentHelp: "表示倍率を入力",
        .fitToScreen: "全体表示",
        .actualSize: "実際のサイズ",
        .apply: "適用",
        .mode: "モード",
        .strength: "適用量",
        .shadowHue: "シャドウの色相",
        .highlightHue: "ハイライトの色相",
        .shadows: "シャドウ",
        .midtones: "中間調",
        .highlights: "ハイライト",
        .hue: "色相",
        .saturationAbbrev: "彩度",
        .luminance: "輝度",
        .blending: "ブレンド",
        .balance: "バランス",
        .canvasBackgroundMenu: "背景色",
        .debugBadgeFormat: "デバッグ · %@",
        .basePickerOverlayPrompt: "未露光のフィルムベース（コマ間または端）をクリック · Esc でキャンセル",
        .scannerLabel: "スキャナー",
        .resolution: "解像度",
        .preview: "プレビュー",
        .bitDepth: "ビット深度",
        .bitDepthUnavailable: "このスキャナーはビット深度オプションを報告しないためスキャンできません。",
        .colorMode: "モード",
        .perforation: "パーフォレーション",
        .filmFrameFormat: "フレーム形式",
        .hardwareScanArea: "ハードウェアスキャン範囲",
        .scanAreaWidth: "幅",
        .scanAreaHeight: "高さ",
        .framesFormat: "コマ数: %d",
        .flatbedFramesFormat: "選択中: %d",
        .flatbedFrameFormat: "コマ %d",
        .flatbedAddFrame: "コマを追加",
        .flatbedPreviewRequired: "プレビューを実行し、1コマ以上選択してください。",
        .flatbedGeometryMismatch: "スキャナーが選択範囲と異なる縦横比の画像を返しました。",
        .multiExposure: "多重露光",
        .infrared: "赤外線 (IR)",
        .infraredHelp: "赤外線チャンネルをスキャンしてゴミやキズを検出します。赤外線対応機のみに表示されます。",
        .scanSection: "スキャン",
        .cancel: "キャンセル",
        .scan: "スキャン",
        .importSource: "読み込み",
        .scanNext: "次をスキャン",
        .scanCountFormat: "スキャン x%d",
        .scannerSearching: "スキャナーを検索中 — USB 接続を確認してください。",
        .scannerPluginMissingTitle: "スキャナープラグインがインストールされていません。",
        .scannerPluginMissingBody: "フィルムスキャナーはライセンス分離のため別プラグインとして提供されます。インストールするとここでスキャンできます。まずは画像の読み込みから現像を始められます。",
        .scannerPluginApprovalTitle: "スキャナープラグインの承認",
        .scannerPluginVersion: "バージョン",
        .scannerPluginLicense: "ライセンス",
        .scannerPluginManifestPath: "Manifestのパス",
        .scannerPluginManifestHash: "Manifest SHA-256",
        .scannerPluginExecutableHash: "実行ファイル SHA-256",
        .scannerPluginApprove: "承認",
        .scannerPluginRevokeApproval: "承認を取り消す",
        .scannerPluginApproved: "承認済み",
        .scannerPluginApprovalRequired: "承認が必要",
        .scannerPluginChangedApprovalRequired: "変更済み · 再承認が必要",
        .scannerPluginInvalidIdentity: "無効な識別情報",
        .scannerPluginTrustStoreUnavailable: "承認ストレージを使用不可",
        .scannerPluginNotReported: "報告なし",
        .scannerSimulator: "スキャナーシミュレーター",
        .scannerSimulatorHelp: "プラグインなしでスキャンワークフローを試せる内蔵シミュレーターです。",
        .scannerTruth: "スキャナー情報",
        .transparency: "透過原稿",
        .brightness: "明るさ",
        .contrast: "コントラスト",
        .capabilityUnavailable: "非対応",
        .capabilityAvailable: "対応",
        .capabilityWaiting: "機能情報の応答を待っています。",
        .multiExposurePreviewHelp: "プレビュースキャンでは多重露光は使用しません。",
        .multiExposureUnsupportedHelp: "現在のバックエンドはハードウェアの露光制御に対応していないため、無効になっています。",
        .multiExposureSupportedHelp: "バックエンドが露光制御に対応する機種でのみ、複数のスキャンを合成します。",
        .exportMainFlatMaster: "MAIN 無調整マスター",
        .exportOriginalRawTIFF: "元スキャン TIFF",
        .exportSidecar: "サイドカー (JSON + XMP)",
        .colorScannerInput: "スキャナーエミュレーション",
        .colorWorking: "作業用スペース",
        .colorMonitor: "ディスプレイ",
        .colorExport: "書き出し",
        .colorSoftProof: "ソフト校正",
        .colorGamutWarning: "色域外警告",
        .colorSampler: "RGB/Lab/HSV サンプラー",
        .colorClippingOverlay: "クリッピング表示",
        .choose: "選択",
        .all: "すべて",
        .red: "レッド",
        .orange: "オレンジ",
        .yellow: "イエロー",
        .green: "グリーン",
        .aqua: "アクア",
        .blue: "ブルー",
        .purple: "パープル",
        .magenta: "マゼンタ",
        .basicTone: "基本補正",
        .exposure: "露光量",
        .toneHighlights: "ハイライト",
        .whites: "白レベル",
        .blacks: "黒レベル",
        .density: "濃度",
        .toneCurve: "トーンカーブ",
        .lights: "ライト",
        .darks: "ダーク",
        .color: "カラー",
        .warmth: "色温度",
        .tint: "色かぶり補正",
        .vibrance: "自然な彩度",
        .saturation: "彩度",
        .colorDepth: "色の深み",
        .colorMixer: "カラーミキサー",
        .colorGrading: "カラーグレーディング",
        .bwToning: "モノクロ調色",
        .calibration: "キャリブレーション",
        .redPrimary: "レッド原色",
        .greenPrimary: "グリーン原色",
        .bluePrimary: "ブルー原色",
        .detailEffects: "ディテールと効果",
        .noiseReduction: "ノイズ軽減",
        .noiseReductionStrength: "NR 適用量",
        .noiseReductionLuminance: "NR 輝度",
        .noiseReductionColor: "NR カラー",
        .noiseReductionDarkTones: "NR 暗部",
        .noiseReductionDetail: "NR ディテール",
        .noiseReductionGrainProtect: "NR 粒状性保護",
        .grain: "粒子",
        .sharpness: "シャープ",
        .clarity: "明瞭度",
        .halation: "ハレーション",
        .vignette: "周辺光量",
        .developerDebug: "開発者向けデバッグ",
        .developerMode: "開発者モード",
        .defaultDefectMicroSpecks: "微細粒子を既定で検出",
        .defaultDefectMicroSpecksHelp: "新しいコマの初期値で、自動とガイドを別々に覚えます。コマごとにチェックボックスがあるので、写真ごとに切り替えられます。",
        .debugOverlay: "デバッグオーバーレイ",
        .stage: "ステージ",
        .full: "全体",
        .undoLastStroke: "直前のストロークを取り消す",
        .clearPaintedStrokes: "描いたストロークを消去",
        .resetAppliedDefects: "適用済みのゴミ・キズ除去をすべてリセット",
        .removeDefects: "ゴミ・キズを除去",
        .resetAdjustmentsHelp: "ジオメトリ（回転/切り抜き）以外のすべての補正値をリセットします。",
        .autoToneHelp: "自動トーン Command-U — ヒストグラムに基づいて露光量、コントラスト、ハイライト、シャドウ、白レベル、黒レベル、自然な彩度を補正します。",
        .autoWhiteBalanceHelp: "自動ホワイトバランス Shift-Command-U — グレーワールド法で色温度と色かぶりを中和します。",
        .copy: "コピー",
        .paste: "ペースト",
        .copyDevelopSettingsHelp: "現在のコマの現像設定をコピーします。",
        .pasteDevelopSettingsHelp: "コピーした現像設定をペーストします。",
        .pasteScope: "ペースト範囲",
        .pasteScopeHelp: "ペーストする現像設定を選択します。",
        .allSettings: "すべての設定",
        .copyPaste: "コピー / ペースト",
        .snapshot: "スナップショット",
        .noSnapshots: "スナップショットなし",
        .save: "保存",
        .saveSnapshotHelp: "現在の現像状態をスナップショットとして保存します。",
        .applySnapshotHelp: "選択したスナップショットを適用します。",
        .compareSnapshotHelp: "現在の設定と選択したスナップショットを一時的に比較します。",
        .current: "現在",
        .noHistory: "履歴なし",
        .history: "履歴",
        .record: "記録",
        .recordHistoryHelp: "現在の現像状態を履歴に記録します。",
        .applyHistoryHelp: "選択した履歴の状態を適用します。",
        .intensity: "強さ",
        .geometry: "ジオメトリ",
        .original: "オリジナル",
        .custom: "カスタム",
        .aspectRatio: "縦横比",
        .unlockCropAspect: "切り抜きの縦横比のロックを解除",
        .lockCropAspect: "切り抜きの縦横比をロック",
        .cropAspectLocked: "縦横比をロックしました",
        .cropAspectUnlocked: "縦横比のロックを解除しました",
        .angle: "角度",
        .cropArea: "切り抜き範囲",
        .rotateLeft: "左に 90° 回転",
        .rotateRight: "右に 90° 回転",
        .resetTransform: "変形をリセット",
        .resetPhotoAngle: "写真の角度をリセット",
        .brushDefect: "ブラシ",
        .guidedDefect: "ガイド",
        .brushDefectHelp: "ブラシ — ゴミやキズをなぞってから、Enter または「ゴミ・キズを除去」を押します。",
        .guidedDefectHelp: "ガイド — 範囲をドラッグしてから、Enter または「ゴミ・キズを除去」を押します。",
        .cloneStamp: "クローンスタンプ",
        .cloneStampHelp: "クローンスタンプ — ⌥クリックでソースを指定し、ドラッグして複製します。",
        .cloneStampSourceHint: "⌥クリックで複製ソースを指定",
        .cloneStampSize: "サイズ",
        .cloneStampHardness: "硬さ",
        .cloneStampEditTitleFormat: "クローンスタンプ %dpx",
        .cloneStampEditSummary: "指定したソースのピクセルを複製",
        .flipHorizontal: "左右反転",
        .flipVertical: "上下反転",
        .baseReadoutFormat: "ベース %.2f %.2f %.2f",
        .batchFrameProgressFormat: "コマ %d/%d",
        .rating: "評価",
        .resetRating: "評価を解除",
        .ratingAccessibilityFormat: "評価 %d",
        .histogram: "ヒストグラム",
        .shadowTone: "シャドウ",
        .highlightTone: "ハイライト",
        .rgbChannelOverlay: "RGB チャンネル表示",
        .redChannel: "レッドチャンネル",
        .greenChannel: "グリーンチャンネル",
        .blueChannel: "ブルーチャンネル",
        .clippingChannelsFormat: "クリッピング %@",
        .resetSectionFormat: "%@をリセット",
        .sliderKeyboardHelp: "矢印キーで 0.01、Shift+矢印キーで 0.10 ずつ調整します。",
        .baseMetricsFormat: "dmin %@ · dmax %@",
        .notAvailableAbbrev: "n/a",
        .softProofSummaryFormat: "%@、%@",
        .softProofProfileOnly: "プロファイル",
        .softProofPaperAndBlack: "用紙 + 黒インク",
        .softProofInvalidICC: "選択した ICC プロファイルは RGB ソフト校正に使用できません。",
        .printOutputProfileRequired: "PRINT 書き出しには、有効な RGB プリンター ICC プロファイルが必要です。",
        .developingFramesFormat: "%dコマを現像中",
        .generatingPreviewFormat: "プレビューを生成中 (%dpx)",
        .generatingSettledPreviewFormat: "確定プレビューを生成中 (%dpx)",
        .defectLayers: "GrainMend レイヤー",
        .disableLayer: "レイヤーをオフ（修復前を表示）",
        .enableLayer: "レイヤーをオン（修復を適用）",
        .hideMask: "マスクを隠す",
        .showMask: "マスクを表示",
        .deleteLayer: "レイヤーを削除",
        .defectDust: "ゴミ",
        .defectPinhole: "ピンホール",
        .defectScratchHorizontal: "横キズ",
        .defectScratchVertical: "縦キズ",
        .defectScratchDiagonal: "斜めキズ",
        .defectEmulsionDamage: "乳剤面の損傷",
        .defectMicroSpeck: "微細粒子",
        .autoDefect: "自動",
        .autoDefectHelp: "自動 — フレーム全体を自動検出してゴミ・キズを除去",
        .frameCountFormat: "%dコマ",
        .frameDisplayFormat: "コマ %d",
        .frameCopyDisplayFormat: "コマ %d コピー %d",
        .frameCompactCopyDisplayFormat: "コマ %d C%d",
        .namedFrameCopyDisplayFormat: "%@ コピー %d",
        .dpiUnspecified: "DPI 未指定",
        .ratingStarFormat: "%dつ星",
        .unrated: "評価なし",
        .unflagged: "フラグなし",
        .picked: "採用",
        .rejected: "除外",
        .selectionSummaryFormat: "%@ · %@",
        .selectionCountsFormat: "採用 %d · 除外 %d",
        .starHelpFormat: "%dつ星",
        .clearPick: "採用フラグを解除",
        .clearReject: "除外フラグを解除",
        .quickExportHelpFormat: "%@ — %@ · %d dpi -> %@",
        .target: "ターゲット",
        .filmProfile: "フィルムプロファイル",
        .look: "ルック",
        .film: "フィルム",
        .process: "プロセス",
        .filmName: "フィルム名",
        .scanFolderName: "フォルダ名",
        .chooseScanFolder: "スキャンフォルダを選択",
        .untitledFilm: "名称未設定のフィルム",
        .userPreset: "ユーザープリセット",
        .noUserPresets: "ユーザープリセットなし",
        .saveUserPresetHelp: "現在の現像設定をユーザープリセットとして保存します",
        .applyUserPresetHelp: "選択したユーザープリセットを適用します",
        .deleteUserPresetHelp: "選択したユーザープリセットを削除します",
        .delete: "削除",
        .removeFromLibrary: "取り除く",
        .libraryRemovalUndoAvailableFormat: "カタログ項目%d件を削除 · 取り消し可能",
        .libraryRemovalRestoredFormat: "カタログ項目%d件を復元",
        .scanProvenanceProtectedStatus: "このスキャン原本はキャプチャ記録に含まれているため、まだ移動または削除できません。",
        .sourceDeletionPlanChangedStatus: "原本の関連付けが変更されました。削除対象をもう一度確認してください。",
        .sourceDeletionUnavailableStatus: "カタログの準備が完了するまで元ファイルを削除できません。",
        .sourceDeletionMoveFailedStatus: "元ファイルをゴミ箱に移動できませんでした。カタログは変更されていません。",
        .sourceDeletionCatalogFailedStatus: "カタログを確定できなかったため、元ファイルを復元しました。",
        .sourceDeletionRollbackFailedStatus: "カタログは変更されていませんが、一部の元ファイルを復元できませんでした。ゴミ箱から復元してください。",
        .moveSourceToTrash: "元ファイルをゴミ箱に移動",
        .sourceOffline: "オフライン",
        .locateOriginal: "オリジナルを指定",
        .locateMissingFolder: "見つからないフォルダーを指定",
        .newFolder: "新規フォルダー",
        .create: "作成",
        .showInFinder: "Finderで表示",
        .renameFolder: "名前を変更",
        .moveToFolder: "フォルダーへ移動",
        .moveItemsHere: "ここへ移動",
        .sourceMoveCompleteFormat: "元ファイルを%d個移動しました。",
        .sourceMoveFailedStatus: "元ファイルを移動できませんでした。変更を元に戻しました。",
        .sourceMoveCatalogFailedStatus: "カタログを保存できなかったため、元ファイルを元の場所に戻しました。",
        .sourceMoveCollisionStatus: "移動先に同じ名前のファイルまたはフォルダーがあります。",
        .folderCreatedStatusFormat: "フォルダーを作成しました: %@",
        .folderCreateFailedStatus: "フォルダーを作成できませんでした。",
        .locateSourcePanelMessageFormat: "元の場所: %@",
        .locateFolderPanelMessageFormat: "元のフォルダー: %@",
        .sourceRelinkInvalid: "選択したファイルは読み込み可能な対応画像ではありません。",
        .sourceRelinkedFormat: "カタログ項目%d件を再接続しました。",
        .deleteSourceConfirmationTitle: "元ファイルをゴミ箱に移動しますか？",
        .deleteSourceConfirmationMessageFormat: "%d件のカタログ項目が%d個の元ファイルを共有しています。すべてnegaflowから削除されます。%@",
        .virtualCopy: "仮想コピー",
        .virtualCopyHelp: "同じ元画像を共有する非破壊のコピーを作成します",
        .proofCopy: "校正コピー",
        .proofCopyHelp: "選択した校正プロファイルに関連付けた非破壊コピーを作成します",
        .dragDefectRegion: "ゴミ・キズのある範囲をドラッグ",
        .undo: "取り消す",
        .undoDefectRemovalHelp: "直前のゴミ・キズ除去を取り消します",
        .defectsCountExcludedFormat: "ゴミ・キズ %d件（除外 %d件）",
        .toneCurveEditorHelp: "クリックでポイントを追加 · ドラッグで移動 · ダブルクリックで削除",
        .reset: "リセット",
        .previousFrame: "前のコマ",
        .nextFrame: "次のコマ",
        .noImages: "画像なし",
        .libraryFiles: "ファイル",
            .libraryAllPhotos: "すべての写真",
            .libraryAllShort: "すべて",
            .libraryFolders: "フォルダー",
            .libraryFilmType: "フィルムタイプ",
            .libraryOffline: "オフライン",
        .libraryCollections: "コレクション",
        .librarySmartCollections: "スマートコレクション",
        .librarySavedSearches: "保存済みの検索",
        .libraryNewCollection: "新規コレクション",
        .libraryNewSmartCollection: "新規スマートコレクション",
        .librarySaveCurrentSearch: "現在の検索を保存",
        .libraryCollectionName: "コレクション名",
        .librarySearchName: "検索名",
        .libraryAddToCollection: "コレクションに追加",
        .libraryRemoveFromCollection: "コレクションから削除",
        .libraryInvalidStoredSearch: "保存済みの検索を読み込めません",
        .librarySearchPlaceholder: "写真を検索",
        .libraryClearSearch: "検索を消去",
        .libraryResultCountFormat: "%d / %d枚",
        .filterCurrentRoll: "現在のロール",
        .filterMinimumRatingFormat: "%dつ星以上",
        .filterInfrared: "赤外線",
        .filterDefectRecipe: "修復レシピ",
        .filterUnvalidatedProfile: "未検証プロファイル",
        .filterMetadataUnknown: "メタデータ状態不明",
        .libraryFilters: "フィルター",
        .clearFilters: "フィルターを消去",
        .exportFileSettings: "ファイル",
        .exportQualitySettings: "品質",
        .exportSourceSettings: "ソース",
        .noMatchingPhotos: "一致する写真がありません",
        .noLibraryFolders: "フォルダーなし",
        .libraryRefreshStatusFormat: "ライブラリを更新: 新規%d件 · 再接続%d件 · オフライン%d件",
        .sortBy: "並べ替え",
        .ascending: "昇順",
        .descending: "降順",
        .sortInputOrder: "読み込み順",
        .sortTime: "時刻順",
        .sortName: "名前順",
        .sortFlag: "フラグ",
        .sortRating: "評価",
        .sortSize: "サイズ順",
        .renamePhoto: "名前を変更",
        .photoName: "写真名",
        .rename: "変更",
        .filmstripHeightHelp: "フィルムストリップの高さを調整",
        .frameCardSizeHelp: "サムネイルのサイズ",
        .developTargetMain: "MAIN",
        .developTargetPrint: "PRINT",
        .filmTypeColorNegative: "カラーネガ",
        .filmTypeSlide: "リバーサル",
        .filmTypeBWNegative: "モノクロネガ",
        .filmTypeBWPositive: "モノクロポジ",
        .targetFilmSummaryFormat: "%@ · %@",
        .frameAccessibilityFormat: "%@、%@、%@",
        .dynamicRangeChannel: "DR",
        .rgb: "RGB",
        .redChannelShort: "R",
        .greenChannelShort: "G",
        .blueChannelShort: "B",
    ]


}
