import Foundation
import Chromabase

enum AppLocalizedPhrase: CaseIterable {
    case idleStatus
    case noScannerStatus
    case autoWhiteBalanceStatus
    case autoToneStatus
    case filmBaseSampleFailed
    case filmBasePickedFormat
    case noFramesToSync
    case whiteBalanceSyncedFormat
    case grainMendBrushEditTitleFormat
    case grainMendAutoEditTitleFormat
    case grainMendGuidedEditTitleFormat
    case brushEditSummary
    case defectsClearedStatus
    case removingDefectsStatus
    case removingDefectsFailedStatus
    case imageLoadFailedFormat
    case historyNameFormat
    case historyRecordedFormat
    case historyAppliedFormat
    case developSettingsCopiedFormat
    case noDevelopSettingsToPaste
    case chooseDevelopPasteScope
    case developSettingsPasted
    case developSettingsPartiallyPastedFormat
    case developSettingsPasteStatusFormat
    case snapshotSavedFormat
    case snapshotAppliedFormat
    case snapshotCompareEnded
    case snapshotComparingFormat
    case snapshotNameFormat
    case exportingStatus
    case exportDownloadingSourcesFormat
    case exportSourceDownloadFailed
    case exportCompleteFormat
    case exportCompleteWithPairsFormat
    case exportDestinationConflict
    case exportFailedFormat
    case importPanelPrompt
    case importPanelMessage
    case noImportableImages
    case importLibraryRegistrationFailedStatus
    case importCompleteFormat
    case importCompleteUnsupportedFormat
    case importCompleteDuplicatesFormat
    case importCompleteUnsupportedDuplicatesFormat
    case importFolder
    case importImageShort
    case importFolderShort
    case folderImportPanelMessage
    case folderImportCompleteFormat
    case folderImportCompleteEmptyFormat
    case detectingDefectsStatus
    case detectingDefectsFailedStatus
    case noDefectsStatus
    case automaticDefectFalsePositiveRiskStatus
    case settingsMemoryCacheSection
    case settingsMemoryCacheModeAutomatic
    case settingsMemoryCacheModeManual
    case settingsMemoryCacheInstalledMemoryFormat
    case settingsMemoryCacheCleanedRawLabel
    case settingsMemoryCacheDevelopedLabel
    case settingsMemoryCacheFramesFormat
    case settingsMemoryCacheEstimateFormat
    case settingsMemoryCacheAutomaticHelp
    case settingsMemoryCacheManualHelp
    case settingsMemoryCacheResetToAutomatic
    case defectsCountFormat
    case confidenceSummaryFormat
    case grainMendIREditTitleFormat
    case infraredCleanDetectingStatus
    case infraredCleanAppliedFormat
    case infraredCleanNoDefectsStatus
    case infraredCleanSkippedBWStatus
    case infraredCleanCoverageAbortStatus
    case infraredCleanFailedStatus
    case demoModeStatus
    case scannerWaitingStatus
    case scannerPluginMissingStartImportStatus
    case scannerPluginMissingStatus
    case scannerPluginApprovalRequiredStatus
    case scannerPluginTrustStoreUnavailableStatus
    case scannerPluginApprovedStatus
    case scannerPluginApprovalFailedStatus
    case scannerPluginApprovalRevokedStatus
    case scannerAppConflictWarningFormat
    case noScannerUseDemoStatus
    case previewScanPreparing
    case filmScanPreparing
    case frameScanCompleteFormat
    case frameScanErrorFormat
    case framesScanCompleteFormat
    case scanCanceled
    case scanWorkflowPersistenceFailed
    case exportFolderUnavailableFormat
    case scanWorkflowInvalidState
    case scanInterruptedFailureReason
    case scanDeviceUnavailable
    case scanOutputFolderFailedFormat
    case scanRollFilmMismatch
    case scanNumberRangeExceeded
    case noActiveScanner
    case noInstalledPlugins
    case scanProgressIdle
    case scanProgressConnecting
    case scanProgressWarmingLamp
    case scanProgressReady
    case scanProgressPreviewScanning
    case scanProgressWaitingForFilmHolder
    case scanProgressScanningRGB
    case scanProgressScanningIR
    case scanProgressProcessingNegative
    case scanProgressRenderingLook
    case scanProgressExporting
    case scanProgressComplete
    case scanProgressScannerBusy
    case scanProgressDisconnected
    case scanProgressError
    case scanProgressBackendFallbackActive
    case userPresetNameFormat
    case userPresetSavedFormat
    case userPresetAppliedFormat
    case userPresetDeletedFormat
    case virtualCopyCreatedFormat
    case proofCopyCreatedFormat
    case proofCopyNameFormat
    case noSelection
    case none
    case baseSection
    case inspectorTabBasic
    case inspectorTabEdit
    case inspectorTabDefect
    case filmStock
    case densitySourceFormat
    case lightSource
    case lightSourceFallbackNote
    case autoMatch
    case autoMatchRequiresValidatedProfile
    case scannerProfileStatusDraft
    case scannerProfileStatusRealOnly
    case scannerProfileStatusPairedSmoke
    case scannerProfileStatusPairedValidated
    case profile
    case pick
    case pickBase
    case pickBaseOnCanvas
    case pickBaseHelp
    case baseRed
    case baseGreen
    case baseBlue
    case autoLevels
    case autoColor
    case baseModeAuto
    case baseModeFilm
    case baseModeManual
    case before
    case unedited
    case after
    case currentImage
    case beforeSourceHelp
    case raw
    case developed
    case compareSplitVertical
    case compareSplitHorizontal
    case zoomOut
    case zoomIn
    case zoomPercentHelp
    case fitToScreen
    case actualSize
    case apply
    case mode
    case strength
    case shadowHue
    case highlightHue
    case shadows
    case midtones
    case highlights
    case hue
    case saturationAbbrev
    case luminance
    case blending
    case balance
    case canvasBackgroundMenu
    case debugBadgeFormat
    case basePickerOverlayPrompt
    case scannerLabel
    case resolution
    case preview
    case bitDepth
    case bitDepthUnavailable
    case colorMode
    case scanColorModeGrayUnstable
    case perforation
    case filmFrameFormat
    case hardwareScanArea
    case scanAreaWidth
    case scanAreaHeight
    case framesFormat
    case flatbedFramesFormat
    case flatbedFrameFormat
    case flatbedAddFrame
    case flatbedRemoveFrame
    case flatbedCopyFrame
    case flatbedPasteFrame
    case flatbedDetectionMode
    case flatbedDetectionAutomatic
    case flatbedDetectionManual
    case flatbedRefreshFrames
    case flatbedPreviewRequired
    case flatbedGeometryMismatch
    case multiExposure
    case infrared
    case infraredHelp
    case scanSection
    case cancel
    case scan
    case importSource
    case scanNext
    case scanCountFormat
    case scannerSearching
    case scannerPluginMissingTitle
    case scannerPluginMissingBody
    case scannerPluginApprovalTitle
    case scannerPluginVersion
    case scannerPluginLicense
    case scannerPluginManifestPath
    case scannerPluginManifestHash
    case scannerPluginExecutableHash
    case scannerPluginApprove
    case scannerPluginRevokeApproval
    case scannerPluginApproved
    case scannerPluginApprovalRequired
    case scannerPluginChangedApprovalRequired
    case scannerPluginInvalidIdentity
    case scannerPluginTrustStoreUnavailable
    case scannerPluginNotReported
    case scannerSimulator
    case scannerSimulatorHelp
    case scannerTruth
    case transparency
    case brightness
    case contrast
    case capabilityUnavailable
    case capabilityAvailable
    case capabilityWaiting
    case multiExposurePreviewHelp
    case multiExposureUnsupportedHelp
    case multiExposureSupportedHelp
    case exportMainFlatMaster
    case exportOriginalRawTIFF
    case exportSidecar
    case colorScannerInput
    case colorWorking
    case colorMonitor
    case colorExport
    case colorSoftProof
    case colorGamutWarning
    case colorSampler
    case colorClippingOverlay
    case choose
    case all
    case red
    case orange
    case yellow
    case green
    case aqua
    case blue
    case purple
    case magenta
    case basicTone
    case exposure
    case toneHighlights
    case whites
    case blacks
    case density
    case toneCurve
    case lights
    case darks
    case color
    case warmth
    case tint
    case vibrance
    case saturation
    case colorDepth
    case colorMixer
    case colorGrading
    case bwToning
    case calibration
    case redPrimary
    case greenPrimary
    case bluePrimary
    case detailEffects
    case noiseReduction
    case noiseReductionStrength
    case noiseReductionLuminance
    case noiseReductionColor
    case noiseReductionDarkTones
    case noiseReductionDetail
    case noiseReductionGrainProtect
    case grain
    case sharpness
    case clarity
    case halation
    case vignette
    case developerDebug
    case developerMode
    case developImportsAutomatically
    case defaultDefectMicroSpecks
    case defaultDefectMicroSpecksHelp
    case debugOverlay
    case stage
    case full
    case undoLastStroke
    case clearPaintedStrokes
    case resetAppliedDefects
    case removeDefects
    case resetAdjustmentsHelp
    case autoToneHelp
    case autoWhiteBalanceHelp
    case copy
    case closePanel
    case copyAll
    case paste
    case copyDevelopSettingsHelp
    case pasteDevelopSettingsHelp
    case pasteScope
    case pasteScopeHelp
    case allSettings
    case copyPaste
    case snapshot
    case noSnapshots
    case save
    case saveSnapshotHelp
    case applySnapshotHelp
    case compareSnapshotHelp
    case current
    case noHistory
    case history
    case record
    case recordHistoryHelp
    case applyHistoryHelp
    case intensity
    case geometry
    case original
    case custom
    case aspectRatio
    case unlockCropAspect
    case lockCropAspect
    case cropAspectLocked
    case cropAspectUnlocked
    case angle
    case cropArea
    case rotateLeft
    case rotateRight
    case resetTransform
    case resetPhotoAngle
    case brushDefect
    case guidedDefect
    case brushDefectHelp
    case guidedDefectHelp
    case cloneStamp
    case cloneStampHelp
    case cloneStampSourceHint
    case cloneStampSize
    case cloneStampHardness
    case cloneStampEditTitleFormat
    case cloneStampEditSummary
    case flipHorizontal
    case flipVertical
    case baseReadoutFormat
    case batchFrameProgressFormat
    case printPageProgressFormat
    case rating
    case resetRating
    case ratingAccessibilityFormat
    case histogram
    case shadowTone
    case highlightTone
    case rgbChannelOverlay
    case redChannel
    case greenChannel
    case blueChannel
    case clippingChannelsFormat
    case resetSectionFormat
    case sliderKeyboardHelp
    case baseMetricsFormat
    case notAvailableAbbrev
    case softProofSummaryFormat
    case softProofProfileOnly
    case softProofPaperAndBlack
    case softProofInvalidICC
    case printOutputProfileRequired
    case developingFramesFormat
    case generatingPreviewFormat
    case generatingSettledPreviewFormat
    case defectLayers
    case disableLayer
    case enableLayer
    case hideMask
    case showMask
    case deleteLayer
    case defectDust
    case defectPinhole
    case defectScratchHorizontal
    case defectScratchVertical
    case defectScratchDiagonal
    case defectEmulsionDamage
    case defectMicroSpeck
    case autoDefect
    case autoDefectHelp
    case frameCountFormat
    case collapseFolder
    case expandFolder
    case frameDisplayFormat
    case frameCopyDisplayFormat
    case frameCompactCopyDisplayFormat
    case namedFrameCopyDisplayFormat
    case dpiUnspecified
    case ratingStarFormat
    case unrated
    case unflagged
    case picked
    case rejected
    case selectionSummaryFormat
    case selectionCountsFormat
    case starHelpFormat
    case clearPick
    case clearReject
    case quickExportHelpFormat
    case target
    case filmProfile
    case look
    case film
    case process
    case filmName
    case scanFolderName
    case chooseScanFolder
    case untitledFilm
    case userPreset
    case noUserPresets
    case saveUserPresetHelp
    case applyUserPresetHelp
    case deleteUserPresetHelp
    case delete
    case removeFromLibrary
    case libraryRemovalUndoAvailableFormat
    case libraryRemovalRestoredFormat
    case scanProvenanceProtectedStatus
    case sourceDeletionPlanChangedStatus
    case sourceDeletionUnavailableStatus
    case sourceDeletionMoveFailedStatus
    case sourceDeletionCatalogFailedStatus
    case sourceDeletionRollbackFailedStatus
    case moveSourceToTrash
    case sourceOffline
    case locateOriginal
    case locateMissingFolder
    case newFolder
    case create
    case showInFinder
    case renameFolder
    case moveToFolder
    case moveItemsHere
    case sourceMoveCompleteFormat
    case sourceMoveFailedStatus
    case sourceMoveCatalogFailedStatus
    case sourceMoveCollisionStatus
    case folderCreatedStatusFormat
    case folderCreateFailedStatus
    case locateSourcePanelMessageFormat
    case locateFolderPanelMessageFormat
    case sourceRelinkInvalid
    case sourceRelinkedFormat
    case deleteSourceConfirmationTitle
    case deleteSourceConfirmationMessageFormat
    case virtualCopy
    case virtualCopyHelp
    case proofCopy
    case proofCopyHelp
    case dragDefectRegion
    case undo
    case redo
    case undoDefectRemovalHelp
    case defectsCountExcludedFormat
    case toneCurveEditorHelp
    case reset
    case previousFrame
    case nextFrame
    case noImages
    case libraryFiles
    case libraryAllPhotos
    case libraryAllShort
    case libraryFolders
    case libraryFilmType
    case libraryOffline
    case libraryCollections
    case librarySmartCollections
    case librarySavedSearches
    case libraryNewCollection
    case libraryNewSmartCollection
    case librarySaveCurrentSearch
    case libraryCollectionName
    case librarySearchName
    case libraryAddToCollection
    case libraryRemoveFromCollection
    case libraryInvalidStoredSearch
    case librarySearchPlaceholder
    case libraryClearSearch
    case libraryResultCountFormat
    case filterCurrentRoll
    case filterMinimumRatingFormat
    case filterInfrared
    case filterDefectRecipe
    case filterUnvalidatedProfile
    case filterMetadataUnknown
    case libraryFilters
    case clearFilters
    case exportFileSettings
    case exportQualitySettings
    case exportSourceSettings
    case noMatchingPhotos
    case noLibraryFolders
    case libraryRefreshStatusFormat
    case sortBy
    case ascending
    case descending
    case sortInputOrder
    case sortTime
    case sortName
    case sortFlag
    case sortRating
    case sortSize
    case filmstripScope
    case filmstripScopeFolder
    case renamePhoto
    case photoName
    case rename
    case filmstripHeightHelp
    case frameCardSizeHelp
    case developTargetMain
    case developTargetPrint
    case filmTypeColorNegative
    case filmTypeSlide
    case filmTypeBWNegative
    case filmTypeBWPositive
    case filmGroupCinema
    case filmGroupBWSlide
    case filmLookDigitalOnly
    case targetFilmSummaryFormat
    case frameAccessibilityFormat
    case dynamicRangeChannel
    case rgb
    case redChannelShort
    case greenChannelShort
    case blueChannelShort
    case settingsDiskTab
    case diskLocationICloud
    case diskLocationDesktop
    case diskLocationSpecificFolder
    case diskLocationCustom
    case diskRootFolderLabel
    case diskThumbnailsFolderLabel
    case diskImportedSourcesFolderLabel
    case diskCleanedRawFolderLabel
    case diskScanPreviewFolderLabel
    case diskExportFolderLabel
    case diskResetPathsButton
    case diskFolderStructureHelp
    case diskThumbnailCacheLabel
    case diskClearThumbnailCache
    case diskThumbnailCacheClearedStatus
    case diskCacheSizeCalculating
    case diskLibraryBackupLabel
    case diskLibraryBackupNow
    case diskLibraryBackupCreatedStatus
    case diskLibraryBackupFailedStatus
    case libraryRestoredFormat
    case libraryRecoveredFromBackupFormat
    case libraryCatalogRepairedFormat
    case libraryCatalogMigratedFormat
    case libraryCatalogBlockedStatus
    case libraryCatalogLockedStatus
    case libraryCatalogLockUnavailableStatus
    case libraryCatalogNewerVersionFormat
    case libraryCatalogMissingAuthoritativeDataStatus
    case librarySelectedBackupAppliedFormat
    case libraryPendingRestoreFailedStatus
    case diskLibraryBackupBrowse
    case libraryBackupEmpty
    case libraryBackupLoadFailed
    case libraryBackupRefresh
    case libraryBackupUnknownDate
    case libraryBackupChecksummed
    case libraryBackupLegacy
    case libraryBackupIncompatible
    case libraryBackupDamaged
    case libraryBackupCountsFormat
    case libraryBackupRestoreSelected
    case libraryBackupRestoreConfirmationTitle
    case libraryBackupRestoreConfirmationMessage
    case libraryBackupScheduleRestore
    case libraryBackupRestorePending
    case libraryBackupCancelPending
    case libraryBackupRestoreScheduleFailed
    case done
    case settingsScanTab
    case settingsDefaultScanRotationPicker
    case settingsDefaultScanRotationHelp
}
