import Foundation

extension DevelopParameters {
    public func encode(to encoder: Encoder) throws {
        var c = encoder.container(keyedBy: CodingKeys.self)
        try c.encode(filmType, forKey: .filmType)
        try c.encodeIfPresent(isDigitalSource, forKey: .isDigitalSource)
        try c.encode(developTarget, forKey: .developTarget)
        try c.encodeIfPresent(scannerProfileID, forKey: .scannerProfileID)
        try c.encode(baseEstimationMode, forKey: .baseEstimationMode)
        if baseScale != .identity { try c.encode(baseScale, forKey: .baseScale) }
        if inputGamma != .automatic { try c.encode(inputGamma, forKey: .inputGamma) }
        try c.encodeIfPresent(manualBaseRGB, forKey: .manualBaseRGB)
        try c.encodeIfPresent(filmStockDminID, forKey: .filmStockDminID)
        try c.encodeIfPresent(lightSourceProfileID, forKey: .lightSourceProfileID)
        try c.encode(autoLevels, forKey: .autoLevels)
        try c.encode(autoNeutralBalance, forKey: .autoNeutralBalance)
        try c.encode(exposure, forKey: .exposure)
        try c.encode(contrast, forKey: .contrast)
        try c.encode(density, forKey: .density)
        try c.encode(highlight, forKey: .highlight)
        try c.encode(shadow, forKey: .shadow)
        try c.encode(whites, forKey: .whites)
        try c.encode(blacks, forKey: .blacks)
        try c.encode(curveHighlights, forKey: .curveHighlights)
        try c.encode(curveLights, forKey: .curveLights)
        try c.encode(curveDarks, forKey: .curveDarks)
        try c.encode(curveShadows, forKey: .curveShadows)
        try c.encode(warmth, forKey: .warmth)
        try c.encode(tint, forKey: .tint)
        try c.encode(colorDepth, forKey: .colorDepth)
        try c.encode(vibrance, forKey: .vibrance)
        try c.encode(saturation, forKey: .saturation)
        try c.encode(redPrimary, forKey: .redPrimary)
        try c.encode(greenPrimary, forKey: .greenPrimary)
        try c.encode(bluePrimary, forKey: .bluePrimary)
        try c.encode(filmEmulation, forKey: .filmEmulation)
        try c.encode(filmEmulationIntensity, forKey: .filmEmulationIntensity)
        try c.encode(grain, forKey: .grain)
        try c.encode(sharpness, forKey: .sharpness)
        try c.encode(halation, forKey: .halation)
        try c.encode(clarity, forKey: .clarity)
        try c.encode(vignette, forKey: .vignette)
        try c.encode(imageTransform, forKey: .imageTransform)
        try c.encode(defectRemoval, forKey: .defectRemoval)
        try c.encode(noiseReduction, forKey: .noiseReduction)
        try c.encode(noiseReductionLuma, forKey: .noiseReductionLuma)
        try c.encode(noiseReductionChroma, forKey: .noiseReductionChroma)
        try c.encode(noiseReductionDarkTone, forKey: .noiseReductionDarkTone)
        try c.encode(noiseReductionDetail, forKey: .noiseReductionDetail)
        try c.encode(noiseReductionGrainProtect, forKey: .noiseReductionGrainProtect)
        try c.encode(localDodgeBurn, forKey: .localDodgeBurn)
        try c.encode(pointCurves, forKey: .pointCurves)
        try c.encode(colorMixer, forKey: .colorMixer)
        try c.encode(colorGrading, forKey: .colorGrading)
        try c.encode(calibration, forKey: .calibration)
        try c.encode(bwToning, forKey: .bwToning)
    }
}
