import Foundation

extension AppLocalization {
    static let germanPhraseTable: [AppLocalizedPhrase: String] = [
        .idleStatus: "Inaktiv",
        .settingsDiskTab: "Datenträger",
        .diskLocationICloud: "iCloud",
        .diskLocationDesktop: "Schreibtisch",
        .diskLocationSpecificFolder: "Ordner",
        .diskLocationCustom: "Benutzerdefiniert",
        .settingsScanTab: "Scan",
        .settingsDefaultScanRotationPicker: "Standard-Scanausrichtung",
        .settingsDefaultScanRotationHelp: "Wird auf neue Scans ohne festgelegte Ausrichtung angewendet. Scanner-Rohdaten werden meist um 180° gedreht gespeichert.",
        .diskRootFolderLabel: "negaflow-Ordner",
        .diskThumbnailsFolderLabel: "Miniaturen-Ordner",
        .diskImportedSourcesFolderLabel: "Zielordner für importierte Originale",
        .diskCleanedRawFolderLabel: "Cacheordner für korrigierte Bilder",
        .diskScanPreviewFolderLabel: "Cacheordner für Scanvorschauen",
        .diskExportFolderLabel: "Export-Ordner",
        .diskResetPathsButton: "Pfade auf Standard zurücksetzen",
        .diskFolderStructureHelp: "Scan-Originale werden nach Datum, Filmtyp und Filmname organisiert.",
        .diskThumbnailCacheLabel: "Miniaturen-Cache",
        .diskClearThumbnailCache: "Miniaturen-Cache leeren",
        .diskThumbnailCacheClearedStatus: "Miniaturen-Cache geleert",
        .diskCacheSizeCalculating: "Berechnung",
        .diskLibraryBackupLabel: "Katalogsicherungen",
        .diskLibraryBackupNow: "Mediathek jetzt sichern",
        .diskLibraryBackupCreatedStatus: "Mediathekssicherung erstellt",
        .diskLibraryBackupFailedStatus: "Mediathekssicherung fehlgeschlagen",
        .libraryRestoredFormat: "Bibliothek wiederhergestellt: %d Fotos",
        .libraryRecoveredFromBackupFormat: "Mediathek aus Sicherung wiederhergestellt: %d Fotos",
        .libraryCatalogMigratedFormat: "Mediathek von Katalogversion %d aktualisiert: %d Fotos",
        .libraryCatalogBlockedStatus: "Der Mediathekskatalog konnte nicht sicher geöffnet werden und blieb unverändert.",
        .libraryCatalogLockedStatus: "Diese Mediathek ist bereits in einem anderen negaflow-Prozess geöffnet.",
        .libraryCatalogLockUnavailableStatus: "negaflow konnte die Schreibsperre nicht übernehmen. Der Katalog blieb unverändert.",
        .libraryCatalogNewerVersionFormat: "Diese Mediathek verwendet die neuere Katalogversion %d und blieb unverändert.",
        .libraryCatalogMissingAuthoritativeDataStatus: "Korrekturrezepte fehlen und es wurde keine gültige Sicherung gefunden. Der Katalog blieb unverändert.",
        .librarySelectedBackupAppliedFormat: "Ausgewählte Mediathekssicherung wiederhergestellt: %d Fotos",
        .libraryPendingRestoreFailedStatus: "Die geplante Wiederherstellung konnte nicht angewendet werden und bleibt vorgemerkt.",
        .diskLibraryBackupBrowse: "Sicherungen anzeigen",
        .libraryBackupEmpty: "Keine Sicherungen",
        .libraryBackupLoadFailed: "Sicherungen konnten nicht geladen werden",
        .libraryBackupRefresh: "Aktualisieren",
        .libraryBackupUnknownDate: "Datum unbekannt",
        .libraryBackupChecksummed: "Prüfsumme bestätigt",
        .libraryBackupLegacy: "Älteres Format",
        .libraryBackupIncompatible: "Nicht kompatibel",
        .libraryBackupDamaged: "Beschädigt",
        .libraryBackupCountsFormat: "%d Fotos · %d Korrekturrezepte",
        .libraryBackupRestoreSelected: "Ausgewählte Sicherung wiederherstellen",
        .libraryBackupRestoreConfirmationTitle: "Diese Sicherung wiederherstellen?",
        .libraryBackupRestoreConfirmationMessage: "Die aktuelle Mediathek wird separat gesichert. Die Wiederherstellung erfolgt beim nächsten Start.",
        .libraryBackupScheduleRestore: "Wiederherstellung vormerken",
        .libraryBackupRestorePending: "Wiederherstellung beim nächsten Start",
        .libraryBackupCancelPending: "Geplante Wiederherstellung abbrechen",
        .libraryBackupRestoreScheduleFailed: "Wiederherstellung konnte nicht vorgemerkt werden",
        .done: "Fertig",
        .noScannerStatus: "Kein Scanner",
        .autoWhiteBalanceStatus: "Automatischer Weißabgleich",
        .autoToneStatus: "Automatische Tonwerte",
        .filmBaseSampleFailed: "Filmbasis konnte nicht gemessen werden — Quellbild ist nicht geladen",
        .filmBasePickedFormat: "Filmbasis gesetzt: %.3f %.3f %.3f",
        .noFramesToSync: "Keine Bilder zum Synchronisieren",
        .whiteBalanceSyncedFormat: "Weißabgleich synchronisiert: %d Bilder",
        .grainMendBrushEditTitleFormat: "GrainMend · Pinsel · %d Striche",
        .grainMendAutoEditTitleFormat: "GrainMend · Auto · %d Defekte",
        .grainMendGuidedEditTitleFormat: "GrainMend · Geführt · %d Bereiche",
        .brushEditSummary: "Präzise Erkennung und Reparatur im ausgewählten Bereich",
        .defectsClearedStatus: "Defektentfernung zurückgesetzt",
        .removingDefectsStatus: "Defekte werden entfernt",
        .removingDefectsFailedStatus: "Entfernen der Defekte fehlgeschlagen",
        .imageLoadFailedFormat: "Bild konnte nicht geladen werden: %@",
        .historyNameFormat: "Verlauf %d",
        .historyRecordedFormat: "Im Verlauf gespeichert: %@",
        .historyAppliedFormat: "Verlaufszustand angewendet: %@",
        .developSettingsCopiedFormat: "Entwicklungseinstellungen kopiert: %@",
        .noDevelopSettingsToPaste: "Keine Entwicklungseinstellungen zum Einsetzen",
        .chooseDevelopPasteScope: "Wählen Sie, welche Entwicklungseinstellungen eingesetzt werden sollen",
        .developSettingsPasted: "Entwicklungseinstellungen eingesetzt",
        .developSettingsPartiallyPastedFormat: "Entwicklungseinstellungen teilweise eingesetzt (%@)",
        .developSettingsPasteStatusFormat: "%@: %@ -> %@",
        .snapshotSavedFormat: "Schnappschuss gesichert: %@",
        .snapshotAppliedFormat: "Schnappschuss angewendet: %@",
        .snapshotCompareEnded: "A/B-Vergleich beendet: aktuelle Einstellungen",
        .snapshotComparingFormat: "A/B-Vergleich: %@",
        .snapshotNameFormat: "Schnappschuss %d",
        .exportingStatus: "Export läuft",
        .exportDownloadingSourcesFormat: "Originale werden geladen %@/%@",
        .exportSourceDownloadFailed: "Export abgebrochen: Die iCloud-Originale konnten nicht geladen werden",
        .exportCompleteFormat: "Export abgeschlossen -> %@",
        .exportCompleteWithPairsFormat: "Export abgeschlossen -> %@",
        .exportDestinationConflict: "Der Export wurde abgebrochen, da bereits eine Ausgabedatei vorhanden ist.",
        .exportFailedFormat: "Export fehlgeschlagen: %@",
        .importPanelPrompt: "Importieren",
        .importPanelMessage: "Bilder zum Entwickeln auswählen (RAW/DNG/TIFF/PNG/JPG)",
        .noImportableImages: "Keine importierbaren Bilder (unterstützt: RAW/DNG/TIFF/PNG/JPG)",
        .importLibraryRegistrationFailedStatus: "Importierte Bilder konnten nicht zur Mediathek hinzugefügt werden",
        .importCompleteFormat: "%d Bilder importiert",
        .importCompleteUnsupportedFormat: "%d Bilder importiert (%d nicht unterstützte Dateien übersprungen)",
        .importCompleteDuplicatesFormat: "%d Bilder importiert (%d Duplikate übersprungen)",
        .importCompleteUnsupportedDuplicatesFormat: "%d Bilder importiert (%d nicht unterstützt, %d Duplikate übersprungen)",
        .importFolder: "Ordner importieren",
        .importImageShort: "Bild",
        .importFolderShort: "Ordner",
        .folderImportPanelMessage: "Wählen Sie Ordner für die Bibliothek aus. Bilddateien darin werden importiert.",
        .folderImportCompleteFormat: "%d Bilder aus %d Ordner(n) importiert",
        .folderImportCompleteEmptyFormat: "%d leere Ordner hinzugefügt",
        .detectingDefectsStatus: "Defekte werden erkannt",
        .detectingDefectsFailedStatus: "Defekterkennung fehlgeschlagen",
        .noDefectsStatus: "Keine Defekte",
        .automaticDefectFalsePositiveRiskStatus: "Hohes Risiko für Fehlerkennungen.",
        .settingsMemoryCacheSection: "Arbeitsspeicher-Cache",
        .settingsMemoryCacheModeAutomatic: "Automatisch",
        .settingsMemoryCacheModeManual: "Manuell",
        .settingsMemoryCacheInstalledMemoryFormat: "Dieser Mac hat %@ Arbeitsspeicher",
        .settingsMemoryCacheCleanedRawLabel: "Defektbereinigte Originale",
        .settingsMemoryCacheDevelopedLabel: "Entwickelte Ergebnisse",
        .settingsMemoryCacheFramesFormat: "%d Bilder",
        .settingsMemoryCacheEstimateFormat: "Bis zu etwa %@ im Speicher · %d%% des Arbeitsspeichers",
        .settingsMemoryCacheAutomaticHelp: "Bemisst die Obergrenze am installierten Arbeitsspeicher. Darüber hinausgehende Bilder werden zuerst die ältesten freigegeben und beim erneuten Öffnen neu entwickelt.",
        .settingsMemoryCacheManualHelp: "Verwendet die von dir gesetzten Werte. Die Obergrenze liegt bei 70%% des installierten Arbeitsspeichers.",
        .settingsMemoryCacheResetToAutomatic: "Auf automatisch zurücksetzen",
        .defectsCountFormat: "%d Defekte",
        .confidenceSummaryFormat: "%@ · Konfidenz %.0f%%",
        .grainMendIREditTitleFormat: "GrainMend · IR · %d Defekte",
        .infraredCleanDetectingStatus: "Defekte werden über den Infrarotkanal erkannt",
        .infraredCleanAppliedFormat: "%d Defekte über den Infrarotkanal entfernt",
        .infraredCleanNoDefectsStatus: "Keine Defekte im Infrarotkanal gefunden",
        .infraredCleanSkippedBWStatus: "IR-Reinigung übersprungen: Silberhaltiger S/W-Film blockiert Infrarot",
        .infraredCleanCoverageAbortStatus: "IR-Reinigung abgebrochen: Defektmaske zu groß (Filmtyp/IR-Ausrichtung prüfen)",
        .infraredCleanFailedStatus: "IR-Defekterkennung fehlgeschlagen",
        .demoModeStatus: "Demomodus",
        .scannerWaitingStatus: "Warten auf Scannerverbindung",
        .scannerPluginMissingStartImportStatus: "Kein Scanner-Plug-in — beginnen Sie mit dem Bildimport",
        .scannerPluginMissingStatus: "Kein Scanner-Plug-in",
        .scannerPluginApprovalRequiredStatus: "Scanner-Plug-in muss genehmigt werden",
        .scannerPluginTrustStoreUnavailableStatus: "Genehmigungsspeicher für Scanner-Plug-ins ist nicht verfügbar",
        .scannerPluginApprovedStatus: "Scanner-Plug-in genehmigt",
        .scannerPluginApprovalFailedStatus: "Scanner-Plug-in konnte nicht genehmigt werden",
        .scannerPluginApprovalRevokedStatus: "Genehmigung des Scanner-Plug-ins widerrufen",
        .scannerAppConflictWarningFormat: "%@ läuft — schließen Sie es, bevor Scanner gesucht werden.",
        .noScannerUseDemoStatus: "Kein Scanner gefunden — USB anschließen oder Demomodus aktivieren.",
        .previewScanPreparing: "Vorschauscan wird vorbereitet",
        .filmScanPreparing: "Filmscan wird vorbereitet",
        .frameScanCompleteFormat: "Bild %d gescannt: %d x %d%@",
        .frameScanErrorFormat: "Scanfehler bei Bild %d: %@",
        .framesScanCompleteFormat: "%d Bilder gescannt",
        .scanCanceled: "Scan abgebrochen",
        .scanWorkflowPersistenceFailed: "Der Scanstatus konnte nicht im Mediathekskatalog gespeichert werden.",
            .exportFolderUnavailableFormat: "Exportordner nicht verwendbar %@ — %@",
        .scanWorkflowInvalidState: "Der Status des Scan-Workflows ist ungültig.",
        .scanInterruptedFailureReason: "Die App wurde beendet, bevor der Abschluss der Hardwareaufnahme bestätigt werden konnte.",
        .scanDeviceUnavailable: "Der ausgewählte Scanner konnte nicht verifiziert werden.",
        .scanOutputFolderFailedFormat: "Der Ordner für Scan-Originale konnte nicht erstellt werden: %@",
        .scanRollFilmMismatch: "Der Filmtyp des aktiven Roll stimmt nicht mit den Scaneinstellungen überein.",
        .scanNumberRangeExceeded: "Die Grenze für Scan-Bildnummern wurde überschritten.",
        .noActiveScanner: "Kein aktiver Scanner.",
        .noInstalledPlugins: "(keine Plug-ins installiert)",
        .scanProgressIdle: "Inaktiv",
        .scanProgressConnecting: "Verbindung zum Scanner wird hergestellt",
        .scanProgressWarmingLamp: "Lampe wärmt auf",
        .scanProgressReady: "Scanbereit",
        .scanProgressPreviewScanning: "Vorschauscan läuft",
        .scanProgressWaitingForFilmHolder: "Warten auf Filmhalter",
        .scanProgressScanningRGB: "Film wird gescannt",
        .scanProgressScanningIR: "Infrarotkanal wird gescannt",
        .scanProgressProcessingNegative: "Scandaten werden verarbeitet",
        .scanProgressRenderingLook: "Entwicklungsvorschau wird gerendert",
        .scanProgressExporting: "Export läuft",
        .scanProgressComplete: "Scan abgeschlossen",
        .scanProgressScannerBusy: "Scanner belegt",
        .scanProgressDisconnected: "Scanner getrennt",
        .scanProgressError: "Scanfehler",
        .scanProgressBackendFallbackActive: "Fallback-Backend aktiv",
        .userPresetNameFormat: "Vorgabe %d",
        .userPresetSavedFormat: "Benutzervorgabe gesichert: %@",
        .userPresetAppliedFormat: "Benutzervorgabe angewendet: %@",
        .userPresetDeletedFormat: "Benutzervorgabe gelöscht: %@",
        .virtualCopyCreatedFormat: "Virtuelle Kopie erstellt: %@",
        .proofCopyCreatedFormat: "Proof-Kopie erstellt: %@",
        .proofCopyNameFormat: "%@ — Proof: %@",
        .noSelection: "Keine Auswahl",
        .none: "Keine",
        .baseSection: "Filmbasis",
        .inspectorTabBasic: "Basis",
        .inspectorTabEdit: "Bearb.",
        .inspectorTabDefect: "GrainMend",
        .filmStock: "Filmmaterial",
        .densitySourceFormat: "Dichtequelle: %@ · Gemessene Basis (Rand/Pipette) hat immer Vorrang.",
        .lightSource: "Lichtquelle",
        .lightSourceFallbackNote: "Wird ignoriert, wenn die Filmbasis aus dem Scan gemessen wurde (Messung zuerst). Gilt nur, wenn keine Basis gemessen werden kann.",
        .autoMatch: "Auto-Abgleich",
        .autoMatchRequiresValidatedProfile: "Der Auto-Abgleich erfordert ein mit gepaarten Referenzscans validiertes Profil.",
        .scannerProfileStatusDraft: "Entwurf",
        .scannerProfileStatusRealOnly: "Reale Scans",
        .scannerProfileStatusPairedSmoke: "Paartest",
        .scannerProfileStatusPairedValidated: "Paarweise validiert",
        .profile: "Profil",
        .pick: "Aufnehmen",
        .pickBase: "Basis-Pipette",
        .pickBaseOnCanvas: "Basis auf der Arbeitsfläche anklicken",
        .pickBaseHelp: "Klicken Sie vor der Umkehrung in den Rohdaten auf unbelichtete Filmbasis, um Dmin zu messen.",
        .baseRed: "Basis R",
        .baseGreen: "Basis G",
        .baseBlue: "Basis B",
        .autoLevels: "Auto-Tonwertkorrektur",
        .autoColor: "Auto-Farbe",
        .baseModeAuto: "Automatisch",
        .baseModeFilm: "Film",
        .baseModeManual: "Manuell",
        .before: "Vorher",
        .unedited: "Unbearbeitet",
        .after: "Nachher",
        .currentImage: "Aktuelles Bild",
        .beforeSourceHelp: "Quelle für die Vorher-Ansicht wählen",
        .raw: "Rohscan",
        .developed: "Entwickelt",
        .compareSplitVertical: "Vorher/Nachher nebeneinander",
        .compareSplitHorizontal: "Vorher/Nachher übereinander",
        .zoomOut: "Verkleinern",
        .zoomIn: "Vergrößern",
        .zoomPercentHelp: "Zoomstufe in Prozent eingeben",
        .fitToScreen: "Einpassen",
        .actualSize: "Originalgröße",
        .apply: "Anwenden",
        .mode: "Modus",
        .strength: "Stärke",
        .shadowHue: "Tiefen-Farbton",
        .highlightHue: "Lichter-Farbton",
        .shadows: "Tiefen",
        .midtones: "Mitteltöne",
        .highlights: "Lichter",
        .hue: "Farbton",
        .saturationAbbrev: "Sätt.",
        .luminance: "Luminanz",
        .blending: "Mischung",
        .balance: "Balance",
        .canvasBackgroundMenu: "Hintergrundfarbe",
        .debugBadgeFormat: "Debug · %@",
        .basePickerOverlayPrompt: "Unbelichtete Filmbasis anklicken (zwischen den Bildern oder am Rand) · Esc zum Abbrechen",
        .scannerLabel: "Scanner",
        .resolution: "Auflösung",
        .preview: "Vorschau",
        .bitDepth: "Bittiefe",
        .bitDepthUnavailable: "Dieser Scanner meldet keine Bittiefe-Option und kann daher nicht scannen.",
        .colorMode: "Modus",
        .perforation: "Perforation",
        .filmFrameFormat: "Bildformat",
        .hardwareScanArea: "Hardware-Scanbereich",
        .scanAreaWidth: "Breite",
        .scanAreaHeight: "Höhe",
        .framesFormat: "Bilder: %d",
        .flatbedFramesFormat: "Ausgewählt: %d",
        .flatbedFrameFormat: "Bild %d",
        .flatbedAddFrame: "Bild hinzufügen",
        .flatbedRemoveFrame: "Bild entfernen",
        .flatbedCopyFrame: "Bild kopieren",
        .flatbedPasteFrame: "Bild einfügen",
        .flatbedDetectionMode: "Bilderkennung",
        .flatbedDetectionAutomatic: "Auto",
        .flatbedDetectionManual: "Manuell",
        .flatbedRefreshFrames: "Bilder neu suchen",
        .flatbedPreviewRequired: "Vorschau starten und mindestens ein Bild auswählen.",
        .flatbedGeometryMismatch: "Der Scanner hat ein Bild mit einem anderen Seitenverhältnis als der ausgewählte Bereich zurückgegeben.",
        .multiExposure: "Mehrfachbelichtung",
        .infrared: "Infrarot (IR)",
        .infraredHelp: "Scannt den Infrarotkanal zur Staub- und Kratzererkennung. Nur bei IR-fähigen Geräten sichtbar.",
        .scanSection: "Scannen",
        .cancel: "Abbrechen",
        .scan: "Scannen",
        .importSource: "Importieren",
        .scanNext: "Nächstes Bild scannen",
        .scanCountFormat: "Scan x%d",
        .scannerSearching: "Scanner wird gesucht — USB-Verbindung prüfen.",
        .scannerPluginMissingTitle: "Es ist kein Scanner-Plug-in installiert.",
        .scannerPluginMissingBody: "Filmscanner werden aus Lizenzgründen als separate Plug-ins bereitgestellt. Nach der Installation können Sie hier scannen. Bis dahin starten Sie die Entwicklung über den Bildimport.",
        .scannerPluginApprovalTitle: "Scanner-Plug-in-Genehmigung",
        .scannerPluginVersion: "Version",
        .scannerPluginLicense: "Lizenz",
        .scannerPluginManifestPath: "Manifest-Pfad",
        .scannerPluginManifestHash: "Manifest-SHA-256",
        .scannerPluginExecutableHash: "Programm-SHA-256",
        .scannerPluginApprove: "Genehmigen",
        .scannerPluginRevokeApproval: "Genehmigung widerrufen",
        .scannerPluginApproved: "Genehmigt",
        .scannerPluginApprovalRequired: "Genehmigung erforderlich",
        .scannerPluginChangedApprovalRequired: "Geändert · Neue Genehmigung erforderlich",
        .scannerPluginInvalidIdentity: "Ungültige Identität",
        .scannerPluginTrustStoreUnavailable: "Genehmigungsspeicher nicht verfügbar",
        .scannerPluginNotReported: "Nicht angegeben",
        .scannerSimulator: "Scanner-Simulator",
        .scannerSimulatorHelp: "Integrierter Simulator, um den Scan-Workflow ohne Plug-in auszuprobieren.",
        .scannerTruth: "Scanner-Informationen",
        .transparency: "Durchlicht",
        .brightness: "Helligkeit",
        .contrast: "Kontrast",
        .capabilityUnavailable: "Nicht verfügbar",
        .capabilityAvailable: "Verfügbar",
        .capabilityWaiting: "Antwort des Scanners steht noch aus.",
        .multiExposurePreviewHelp: "Für Vorschauscans wird keine Mehrfachbelichtung verwendet.",
        .multiExposureUnsupportedHelp: "Das aktuelle Backend bietet keine echte Hardware-Belichtungssteuerung, daher ist die Funktion deaktiviert.",
        .multiExposureSupportedHelp: "Kombiniert mehrere Scans nur auf Geräten, deren Backend Belichtungssteuerung unterstützt.",
        .exportMainFlatMaster: "Unkorrigiertes MAIN-Master",
        .exportOriginalRawTIFF: "Original-Scan-TIFF",
        .exportSidecar: "Filialdateien (JSON + XMP)",
        .colorScannerInput: "Scanner-Emulation",
        .colorWorking: "Arbeitsfarbraum",
        .colorMonitor: "Monitor",
        .colorExport: "Export",
        .colorSoftProof: "Softproof",
        .colorGamutWarning: "Farbumfang-Warnung",
        .colorSampler: "RGB/Lab/HSV-Sampler",
        .colorClippingOverlay: "Beschnittwarnung",
        .choose: "Auswählen",
        .all: "Alle",
        .red: "Rot",
        .orange: "Orange",
        .yellow: "Gelb",
        .green: "Grün",
        .aqua: "Aquamarin",
        .blue: "Blau",
        .purple: "Lila",
        .magenta: "Magenta",
        .basicTone: "Grundeinstellungen",
        .exposure: "Belichtung",
        .toneHighlights: "Lichter",
        .whites: "Weiß",
        .blacks: "Schwarz",
        .density: "Dichte",
        .toneCurve: "Gradationskurve",
        .lights: "Helle Mitteltöne",
        .darks: "Dunkle Mitteltöne",
        .color: "Farbe",
        .warmth: "Temperatur",
        .tint: "Tonung",
        .vibrance: "Dynamik",
        .saturation: "Sättigung",
        .colorDepth: "Farbtiefe",
        .colorMixer: "Farbmischer",
        .colorGrading: "Farb-Grading",
        .bwToning: "S/W-Tonung",
        .calibration: "Kalibrierung",
        .redPrimary: "Primärfarbe Rot",
        .greenPrimary: "Primärfarbe Grün",
        .bluePrimary: "Primärfarbe Blau",
        .detailEffects: "Details & Effekte",
        .noiseReduction: "Rauschreduzierung",
        .noiseReductionStrength: "NR-Stärke",
        .noiseReductionLuminance: "NR-Luminanz",
        .noiseReductionColor: "NR-Farbe",
        .noiseReductionDarkTones: "NR-Tiefen",
        .noiseReductionDetail: "NR-Details",
        .noiseReductionGrainProtect: "NR-Kornschutz",
        .grain: "Körnung",
        .sharpness: "Schärfe",
        .clarity: "Klarheit",
        .halation: "Halation",
        .vignette: "Vignettierung",
        .developerDebug: "Entwickler-Debug",
        .developerMode: "Entwicklermodus",
        .developImportsAutomatically: "Neue Importe automatisch entwickeln",
        .defaultDefectMicroSpecks: "Mikropartikel standardmäßig erkennen",
        .defaultDefectMicroSpecksHelp: "Startwert für neue Bilder, getrennt für Automatik und Geführt gespeichert. Jedes Bild behält sein eigenes Kontrollkästchen und lässt sich weiterhin einzeln umschalten.",
        .debugOverlay: "Debug-Overlay",
        .stage: "Stufe",
        .full: "Ganzes Bild",
        .undoLastStroke: "Letzten Strich rückgängig machen",
        .clearPaintedStrokes: "Gemalte Striche löschen",
        .resetAppliedDefects: "Alle angewendeten Defektkorrekturen zurücksetzen",
        .removeDefects: "Defekte entfernen",
        .resetAdjustmentsHelp: "Setzt alle Anpassungen außer der Geometrie (Drehen/Zuschneiden) zurück.",
        .autoToneHelp: "Automatische Tonwerte Befehl-U — passt Belichtung, Kontrast, Lichter, Tiefen, Weiß, Schwarz und Dynamik anhand des Histogramms an.",
        .autoWhiteBalanceHelp: "Automatischer Weißabgleich Umschalt-Befehl-U — neutralisiert Temperatur und Tonung nach der Grauwelt-Methode.",
        .copy: "Kopieren",
        .closePanel: "Schließen",
        .copyAll: "Alles kopieren",
        .paste: "Einsetzen",
        .copyDevelopSettingsHelp: "Kopiert die Entwicklungseinstellungen des aktuellen Bilds.",
        .pasteDevelopSettingsHelp: "Setzt die kopierten Entwicklungseinstellungen ein.",
        .pasteScope: "Einfügebereich",
        .pasteScopeHelp: "Wählen Sie, welche Entwicklungseinstellungen eingesetzt werden.",
        .allSettings: "Alle Einstellungen",
        .copyPaste: "Kopieren / Einsetzen",
        .snapshot: "Schnappschuss",
        .noSnapshots: "Keine Schnappschüsse",
        .save: "Sichern",
        .saveSnapshotHelp: "Sichert den aktuellen Entwicklungszustand als Schnappschuss.",
        .applySnapshotHelp: "Wendet den ausgewählten Schnappschuss an.",
        .compareSnapshotHelp: "Vergleicht die aktuellen Einstellungen vorübergehend mit dem ausgewählten Schnappschuss.",
        .current: "Aktuell",
        .noHistory: "Kein Verlauf",
        .history: "Verlauf",
        .record: "Aufzeichnen",
        .recordHistoryHelp: "Zeichnet den aktuellen Entwicklungszustand im Verlauf auf.",
        .applyHistoryHelp: "Wendet den ausgewählten Verlaufszustand an.",
        .intensity: "Intensität",
        .geometry: "Geometrie",
        .original: "Original",
        .custom: "Benutzerdefiniert",
        .aspectRatio: "Seitenverhältnis",
        .unlockCropAspect: "Seitenverhältnis des Zuschnitts entsperren",
        .lockCropAspect: "Seitenverhältnis des Zuschnitts sperren",
        .cropAspectLocked: "Seitenverhältnis gesperrt",
        .cropAspectUnlocked: "Seitenverhältnis entsperrt",
        .angle: "Winkel",
        .cropArea: "Zuschnittbereich",
        .rotateLeft: "90° nach links drehen",
        .rotateRight: "90° nach rechts drehen",
        .resetTransform: "Transformation zurücksetzen",
        .resetPhotoAngle: "Bildwinkel zurücksetzen",
        .brushDefect: "Pinsel",
        .guidedDefect: "Geführt",
        .brushDefectHelp: "Pinsel — Staub oder Kratzer übermalen, dann Eingabetaste oder „Defekte entfernen“ drücken.",
        .guidedDefectHelp: "Geführt — Bereich aufziehen, dann Eingabetaste oder „Defekte entfernen“ drücken.",
        .cloneStamp: "Klonstempel",
        .cloneStampHelp: "Klonstempel — mit ⌥-Klick die Quelle festlegen, dann zum Malen ziehen.",
        .cloneStampSourceHint: "⌥-Klick legt die Klonquelle fest",
        .cloneStampSize: "Größe",
        .cloneStampHardness: "Härte",
        .cloneStampEditTitleFormat: "Klonstempel %dpx",
        .cloneStampEditSummary: "Kopiert Pixel aus der gewählten Quelle",
        .flipHorizontal: "Horizontal spiegeln",
        .flipVertical: "Vertikal spiegeln",
        .baseReadoutFormat: "Basis %.2f %.2f %.2f",
        .batchFrameProgressFormat: "Bild %d/%d",
        .printPageProgressFormat: "Seite %d/%d",
        .rating: "Bewertung",
        .resetRating: "Bewertung entfernen",
        .ratingAccessibilityFormat: "Bewertung %d",
        .histogram: "Histogramm",
        .shadowTone: "Tiefen",
        .highlightTone: "Lichter",
        .rgbChannelOverlay: "RGB-Kanal-Überlagerung",
        .redChannel: "Rot-Kanal",
        .greenChannel: "Grün-Kanal",
        .blueChannel: "Blau-Kanal",
        .clippingChannelsFormat: "Beschnitt %@",
        .resetSectionFormat: "%@ zurücksetzen",
        .sliderKeyboardHelp: "Pfeiltasten ändern um 0,01; Umschalt+Pfeil um 0,10.",
        .baseMetricsFormat: "dmin %@ · dmax %@",
        .notAvailableAbbrev: "n. v.",
        .softProofSummaryFormat: "%@, %@",
        .softProofProfileOnly: "Profil",
        .softProofPaperAndBlack: "Papier + Schwarztinte",
        .softProofInvalidICC: "Das gewählte ICC-Profil kann nicht für RGB-Softproofs verwendet werden.",
        .printOutputProfileRequired: "Für den PRINT-Export ist ein gültiges RGB-Drucker-ICC-Profil erforderlich.",
        .developingFramesFormat: "%d Bilder werden entwickelt",
        .generatingPreviewFormat: "Vorschau wird erstellt (%dpx)",
        .generatingSettledPreviewFormat: "Endgültige Vorschau wird erstellt (%dpx)",
        .defectLayers: "GrainMend-Ebenen",
        .disableLayer: "Ebene deaktivieren (Zustand vor der Reparatur anzeigen)",
        .enableLayer: "Ebene aktivieren (Reparatur anwenden)",
        .hideMask: "Maske ausblenden",
        .showMask: "Maske einblenden",
        .deleteLayer: "Ebene löschen",
        .defectDust: "Staub",
        .defectPinhole: "Nadelloch",
        .defectScratchHorizontal: "Horizontaler Kratzer",
        .defectScratchVertical: "Vertikaler Kratzer",
        .defectScratchDiagonal: "Diagonaler Kratzer",
        .defectEmulsionDamage: "Emulsionsschaden",
        .defectMicroSpeck: "Mikropartikel",
        .autoDefect: "Auto",
        .autoDefectHelp: "Auto — gesamtes Bild automatisch prüfen und Defekte entfernen",
        .frameCountFormat: "%d Bilder",
        .collapseFolder: "Ordner einklappen",
        .expandFolder: "Ordner ausklappen",
        .frameDisplayFormat: "Bild %d",
        .frameCopyDisplayFormat: "Bild %d Kopie %d",
        .frameCompactCopyDisplayFormat: "Bild %d K%d",
        .namedFrameCopyDisplayFormat: "%@ Kopie %d",
        .dpiUnspecified: "DPI nicht angegeben",
        .ratingStarFormat: "%d Sterne",
        .unrated: "Ohne Bewertung",
        .unflagged: "Ohne Markierung",
        .picked: "Markieren",
        .rejected: "Ablehnen",
        .selectionSummaryFormat: "%@ · %@",
        .selectionCountsFormat: "%d markiert · %d abgelehnt",
        .starHelpFormat: "%d Sterne",
        .clearPick: "Markierung entfernen",
        .clearReject: "Ablehnung entfernen",
        .quickExportHelpFormat: "%@ — %@ · %d dpi -> %@",
        .target: "Ziel",
        .filmProfile: "Filmprofil",
        .look: "Look",
        .film: "Film",
        .process: "Prozess",
        .filmName: "Filmname",
        .scanFolderName: "Ordnername",
        .chooseScanFolder: "Scanordner auswählen",
        .untitledFilm: "Unbenannter Film",
        .userPreset: "Benutzervorgabe",
        .noUserPresets: "Keine Benutzervorgaben",
        .saveUserPresetHelp: "Sichert die aktuellen Entwicklungseinstellungen als Benutzervorgabe",
        .applyUserPresetHelp: "Wendet die ausgewählte Benutzervorgabe an",
        .deleteUserPresetHelp: "Löscht die ausgewählte Benutzervorgabe",
        .delete: "Löschen",
        .removeFromLibrary: "Entfernen",
        .libraryRemovalUndoAvailableFormat: "%d Katalogeintrag/-einträge entfernt · Rückgängig verfügbar",
        .libraryRemovalRestoredFormat: "%d Katalogeintrag/-einträge wiederhergestellt",
        .scanProvenanceProtectedStatus: "Dieses Scan-Original gehört zum Aufnahmeprotokoll und kann noch nicht verschoben oder entfernt werden.",
        .sourceDeletionPlanChangedStatus: "Die verknüpften Quellen haben sich geändert. Prüfen Sie den Löschvorgang erneut.",
        .sourceDeletionUnavailableStatus: "Quelldateien können erst gelöscht werden, wenn der Katalog bereit ist.",
        .sourceDeletionMoveFailedStatus: "Die Quelldateien konnten nicht in den Papierkorb gelegt werden. Der Katalog wurde nicht geändert.",
        .sourceDeletionCatalogFailedStatus: "Der Katalog konnte nicht bestätigt werden. Die Quelldateien wurden wiederhergestellt.",
        .sourceDeletionRollbackFailedStatus: "Der Katalog wurde nicht geändert, aber einige Quelldateien konnten nicht wiederhergestellt werden. Stellen Sie sie aus dem Papierkorb wieder her.",
        .moveSourceToTrash: "Quelldatei in den Papierkorb legen",
        .sourceOffline: "Offline",
        .locateOriginal: "Original suchen",
        .locateMissingFolder: "Fehlenden Ordner suchen",
        .newFolder: "Neuer Ordner",
        .create: "Erstellen",
        .showInFinder: "Im Finder anzeigen",
        .renameFolder: "Umbenennen",
        .moveToFolder: "In Ordner bewegen",
        .moveItemsHere: "Hierher bewegen",
        .sourceMoveCompleteFormat: "%d Quelldatei(en) bewegt.",
        .sourceMoveFailedStatus: "Die Quelldateien konnten nicht bewegt werden. Die Änderungen wurden zurückgenommen.",
        .sourceMoveCatalogFailedStatus: "Der Katalog konnte nicht gesichert werden. Die Quelldateien wurden wiederhergestellt.",
        .sourceMoveCollisionStatus: "Am Ziel existiert bereits eine Datei oder ein Ordner mit diesem Namen.",
        .folderCreatedStatusFormat: "Ordner erstellt: %@",
        .folderCreateFailedStatus: "Der Ordner konnte nicht erstellt werden.",
        .locateSourcePanelMessageFormat: "Letzter bekannter Speicherort: %@",
        .locateFolderPanelMessageFormat: "Letzter bekannter Ordner: %@",
        .sourceRelinkInvalid: "Die ausgewählte Datei ist kein lesbares unterstütztes Bild.",
        .sourceRelinkedFormat: "%d Katalogeintrag/-einträge erneut verbunden.",
        .deleteSourceConfirmationTitle: "Quelldatei in den Papierkorb legen?",
        .deleteSourceConfirmationMessageFormat: "%d Katalogeinträge teilen %d Quelldatei(en). Alle werden aus negaflow entfernt. %@",
        .virtualCopy: "Virtuelle Kopie",
        .virtualCopyHelp: "Erstellt eine nicht-destruktive Kopie, die denselben Rohscan verwendet",
        .proofCopy: "Proof-Kopie",
        .proofCopyHelp: "Erstellt eine nicht-destruktive Kopie für das gewählte Proof-Profil",
        .dragDefectRegion: "Über den Defektbereich ziehen",
        .undo: "Widerrufen",
        .undoDefectRemovalHelp: "Macht die letzte Defektkorrektur rückgängig",
        .defectsCountExcludedFormat: "%d Defekte (%d ausgeschlossen)",
        .toneCurveEditorHelp: "Klicken fügt Punkte hinzu · Ziehen verschiebt · Doppelklick löscht",
        .reset: "Zurücksetzen",
        .previousFrame: "Vorheriges Bild",
        .nextFrame: "Nächstes Bild",
        .noImages: "Keine Bilder",
        .libraryFiles: "Dateien",
        .libraryAllPhotos: "Alle Fotos",
        .libraryAllShort: "Alle",
        .libraryFolders: "Ordner",
        .libraryFilmType: "Filmtyp",
        .libraryOffline: "Offline",
        .libraryCollections: "Sammlungen",
        .librarySmartCollections: "Smart-Sammlungen",
        .librarySavedSearches: "Gespeicherte Suchen",
        .libraryNewCollection: "Neue Sammlung",
        .libraryNewSmartCollection: "Neue Smart-Sammlung",
        .librarySaveCurrentSearch: "Aktuelle Suche speichern",
        .libraryCollectionName: "Sammlungsname",
        .librarySearchName: "Suchname",
        .libraryAddToCollection: "Zur Sammlung hinzufügen",
        .libraryRemoveFromCollection: "Aus Sammlung entfernen",
        .libraryInvalidStoredSearch: "Gespeicherte Suche kann nicht gelesen werden",
        .librarySearchPlaceholder: "Fotos suchen",
        .libraryClearSearch: "Suche löschen",
        .libraryResultCountFormat: "%d von %d Fotos",
        .filterCurrentRoll: "Aktueller Film",
        .filterMinimumRatingFormat: "Ab %d Sternen",
        .filterInfrared: "Infrarot",
        .filterDefectRecipe: "Korrekturrezept",
        .filterUnvalidatedProfile: "Nicht validiertes Profil",
        .filterMetadataUnknown: "Metadatenstatus unbekannt",
        .libraryFilters: "Filter",
        .clearFilters: "Filter löschen",
        .exportFileSettings: "Datei",
        .exportQualitySettings: "Qualität",
        .exportSourceSettings: "Quelle",
        .noMatchingPhotos: "Keine passenden Fotos",
        .noLibraryFolders: "Keine Ordner",
        .libraryRefreshStatusFormat: "Mediathek aktualisiert: %d neu · %d erneut verbunden · %d offline",
        .sortBy: "Sortieren nach",
        .ascending: "Aufsteigend",
        .descending: "Absteigend",
        .sortInputOrder: "Importreihenfolge",
        .sortTime: "Zeit",
        .sortName: "Name",
        .sortFlag: "Markierung",
        .sortRating: "Bewertung",
        .sortSize: "Größe",
        .filmstripScope: "Bereich",
        .filmstripScopeFolder: "Dieser Ordner",
        .renamePhoto: "Foto umbenennen",
        .photoName: "Fotoname",
        .rename: "Umbenennen",
        .filmstripHeightHelp: "Höhe des Filmstreifens anpassen",
        .frameCardSizeHelp: "Größe der Miniaturen",
        .developTargetMain: "MAIN",
        .developTargetPrint: "PRINT",
        .filmTypeColorNegative: "Farbnegativ",
        .filmTypeSlide: "Dia",
        .filmTypeBWNegative: "S/W-Negativ",
        .filmTypeBWPositive: "S/W-Positiv",
        .targetFilmSummaryFormat: "%@ · %@",
        .frameAccessibilityFormat: "%@, %@, %@",
        .dynamicRangeChannel: "DR",
        .rgb: "RGB",
        .redChannelShort: "R",
        .greenChannelShort: "G",
        .blueChannelShort: "B",
    ]
}
