import Foundation

extension AppLocalization {
    static let englishPhraseTable: [AppLocalizedPhrase: String] = [
            .idleStatus: "Idle",
            .settingsDiskTab: "Disk",
            .diskLocationICloud: "iCloud",
            .diskLocationDesktop: "Desktop",
            .diskLocationSpecificFolder: "Folder",
            .diskLocationCustom: "Custom",
            .settingsScanTab: "Scan",
            .settingsDefaultScanRotationPicker: "Default scan rotation",
            .settingsDefaultScanRotationHelp: "Applied to new scans with no orientation set. Scanner raw is usually stored upside-down (180°).",
            .diskRootFolderLabel: "negaflow Folder",
            .diskThumbnailsFolderLabel: "Thumbnail Folder",
            .diskImportedSourcesFolderLabel: "Imported Source Move Folder",
            .diskCleanedRawFolderLabel: "Corrected Image Cache Folder",
            .diskScanPreviewFolderLabel: "Scan Preview Cache Folder",
            .diskExportFolderLabel: "Export Folder",
            .diskResetPathsButton: "Reset Paths to Defaults",
            .diskFolderStructureHelp: "Scanned originals are organized by date, film type, and film name.",
            .diskThumbnailCacheLabel: "Thumbnail Cache",
            .diskClearThumbnailCache: "Clear Thumbnail Cache",
            .diskThumbnailCacheClearedStatus: "Thumbnail cache cleared",
            .diskCacheSizeCalculating: "Calculating",
            .diskLibraryBackupLabel: "Catalog Backups",
            .diskLibraryBackupNow: "Back Up Library Now",
            .diskLibraryBackupCreatedStatus: "Library backup created",
            .diskLibraryBackupFailedStatus: "Library backup failed",
            .libraryRestoredFormat: "Library restored: %d photos",
            .libraryRecoveredFromBackupFormat: "Library recovered from backup: %d photos",
            .libraryCatalogMigratedFormat: "Library upgraded from catalog version %d: %d photos",
            .libraryCatalogBlockedStatus: "The library catalog could not be opened safely and was left unchanged.",
            .libraryCatalogLockedStatus: "This library is already open in another negaflow process.",
            .libraryCatalogLockUnavailableStatus: "negaflow could not acquire the library write lock. The catalog was left unchanged.",
            .libraryCatalogNewerVersionFormat: "This library uses newer catalog version %d and was left unchanged.",
            .libraryCatalogMissingAuthoritativeDataStatus: "Library defect recipes are incomplete and no valid backup was found. The catalog was left unchanged.",
            .librarySelectedBackupAppliedFormat: "Selected library backup restored: %d photos",
            .libraryPendingRestoreFailedStatus: "The scheduled library restore could not be applied and was left pending.",
            .diskLibraryBackupBrowse: "Browse Backups",
            .libraryBackupEmpty: "No Backups",
            .libraryBackupLoadFailed: "Couldn’t Load Backups",
            .libraryBackupRefresh: "Refresh",
            .libraryBackupUnknownDate: "Unknown Date",
            .libraryBackupChecksummed: "Checksum Verified",
            .libraryBackupLegacy: "Legacy Format",
            .libraryBackupIncompatible: "Incompatible",
            .libraryBackupDamaged: "Damaged",
            .libraryBackupCountsFormat: "%d photos · %d repair recipes",
            .libraryBackupRestoreSelected: "Restore Selected Backup",
            .libraryBackupRestoreConfirmationTitle: "Restore This Backup?",
            .libraryBackupRestoreConfirmationMessage: "The current library will be preserved. The restore will be applied on the next launch.",
            .libraryBackupScheduleRestore: "Schedule Restore",
            .libraryBackupRestorePending: "Restores on Next Launch",
            .libraryBackupCancelPending: "Cancel Scheduled Restore",
            .libraryBackupRestoreScheduleFailed: "Couldn’t Schedule Restore",
            .done: "Done",
            .noScannerStatus: "No scanner",
            .autoWhiteBalanceStatus: "Auto White Balance",
            .autoToneStatus: "Auto Tone",
            .filmBaseSampleFailed: "Film base sample failed — source image is not loaded",
            .filmBasePickedFormat: "Film base set: %.3f %.3f %.3f",
            .noFramesToSync: "No frames to sync",
            .whiteBalanceSyncedFormat: "White balance synced: %d frames",
            .grainMendBrushEditTitleFormat: "GrainMend · Brush · %d strokes",
            .grainMendAutoEditTitleFormat: "GrainMend · Auto · %d defects",
            .grainMendGuidedEditTitleFormat: "GrainMend · Guided · %d regions",
            .brushEditSummary: "Custom region precision detect and repair",
            .defectsClearedStatus: "Defect removal reset",
            .removingDefectsStatus: "Removing defects",
            .removingDefectsFailedStatus: "Defect removal failed",
            .imageLoadFailedFormat: "Image load failed: %@",
            .historyNameFormat: "History %d",
            .historyRecordedFormat: "History recorded: %@",
            .historyAppliedFormat: "History applied: %@",
            .developSettingsCopiedFormat: "Develop settings copied: %@",
            .noDevelopSettingsToPaste: "No develop settings to paste",
            .chooseDevelopPasteScope: "Choose a develop settings paste scope",
            .developSettingsPasted: "Develop settings pasted",
            .developSettingsPartiallyPastedFormat: "Partial develop settings pasted (%@)",
            .developSettingsPasteStatusFormat: "%@: %@ -> %@",
            .snapshotSavedFormat: "Snapshot saved: %@",
            .snapshotAppliedFormat: "Snapshot applied: %@",
            .snapshotCompareEnded: "A/B comparison ended: Current",
            .snapshotComparingFormat: "A/B comparison: %@",
            .snapshotNameFormat: "Snapshot %d",
            .exportingStatus: "Exporting",
            .exportDownloadingSourcesFormat: "Downloading originals %@/%@",
            .exportSourceDownloadFailed: "Export stopped: the iCloud originals could not be downloaded",
            .exportCompleteFormat: "Export complete -> %@",
            .exportCompleteWithPairsFormat: "Export complete -> %@",
            .exportDestinationConflict: "Export stopped because an output file already exists.",
            .exportFailedFormat: "Export failed: %@",
            .importPanelPrompt: "Import",
            .importPanelMessage: "Choose images to develop (RAW/DNG/TIFF/PNG/JPG)",
            .noImportableImages: "No importable images (supported: RAW/DNG/TIFF/PNG/JPG)",
            .importLibraryRegistrationFailedStatus: "Imported images could not be added to the Library",
            .importCompleteFormat: "%d images imported",
            .importCompleteUnsupportedFormat: "%d images imported (%d unsupported files skipped)",
            .importCompleteDuplicatesFormat: "%d images imported (%d duplicates skipped)",
            .importCompleteUnsupportedDuplicatesFormat: "%d images imported (%d unsupported, %d duplicates skipped)",
            .importFolder: "Import Folder",
            .importImageShort: "Image",
            .importFolderShort: "Folder",
            .folderImportPanelMessage: "Choose folders to add to the Library. Image files inside them will be imported.",
            .folderImportCompleteFormat: "%d images imported from %d folder(s)",
            .folderImportCompleteEmptyFormat: "%d empty folder(s) added",
            .detectingDefectsStatus: "Detecting defects",
            .detectingDefectsFailedStatus: "Defect detection failed",
            .noDefectsStatus: "No defects",
            .automaticDefectFalsePositiveRiskStatus: "High risk of false detections.",
            .settingsMemoryCacheSection: "Memory cache",
            .settingsMemoryCacheModeAutomatic: "Automatic",
            .settingsMemoryCacheModeManual: "Manual",
            .settingsMemoryCacheInstalledMemoryFormat: "This Mac has %@ of memory",
            .settingsMemoryCacheCleanedRawLabel: "Defect-cleaned originals",
            .settingsMemoryCacheDevelopedLabel: "Developed results",
            .settingsMemoryCacheFramesFormat: "%d frames",
            .settingsMemoryCacheEstimateFormat: "Up to about %@ resident · %d%% of memory",
            .settingsMemoryCacheAutomaticHelp: "Sizes the limit to your installed memory. Frames beyond the limit are released oldest first and re-developed when reopened.",
            .settingsMemoryCacheManualHelp: "Uses the values you set. The ceiling is 70%% of installed memory.",
            .settingsMemoryCacheResetToAutomatic: "Reset to automatic",
            .defectsCountFormat: "%d defects",
            .confidenceSummaryFormat: "%@ · confidence %.0f%%",
            .grainMendIREditTitleFormat: "GrainMend · IR · %d defects",
            .infraredCleanDetectingStatus: "Detecting defects from the infrared channel",
            .infraredCleanAppliedFormat: "Removed %d defects using the infrared channel",
            .infraredCleanNoDefectsStatus: "No defects found in the infrared channel",
            .infraredCleanSkippedBWStatus: "IR clean skipped: silver-based B&W film blocks infrared",
            .infraredCleanCoverageAbortStatus: "IR clean aborted: defect mask too large (check film type or IR alignment)",
            .infraredCleanFailedStatus: "IR defect detection failed",
            .demoModeStatus: "Demo mode",
            .scannerWaitingStatus: "Waiting for scanner connection",
            .scannerPluginMissingStartImportStatus: "No scanner plug-in — start with image import",
            .scannerPluginMissingStatus: "No scanner plug-in",
            .scannerPluginApprovalRequiredStatus: "Scanner plug-in approval required",
            .scannerPluginTrustStoreUnavailableStatus: "Scanner plug-in approval storage is unavailable",
            .scannerPluginApprovedStatus: "Scanner plug-in approved",
            .scannerPluginApprovalFailedStatus: "Scanner plug-in approval failed",
            .scannerPluginApprovalRevokedStatus: "Scanner plug-in approval revoked",
            .scannerAppConflictWarningFormat: "%@ is running — close it before detecting scanners.",
            .noScannerUseDemoStatus: "No scanner — connect USB or enable Demo mode.",
            .previewScanPreparing: "Preparing preview scan",
            .filmScanPreparing: "Preparing film scan",
            .frameScanCompleteFormat: "Frame %d scan complete: %d x %d%@",
            .frameScanErrorFormat: "Frame %d scan error: %@",
            .framesScanCompleteFormat: "%d frames scanned",
            .scanCanceled: "Scan canceled",
            .scanWorkflowPersistenceFailed: "The scan state could not be saved to the library catalog.",
            .exportFolderUnavailableFormat: "Cannot use the export folder %@ — %@",
            .scanWorkflowInvalidState: "The scan workflow state is invalid.",
            .scanInterruptedFailureReason: "The app closed before hardware capture completion could be confirmed.",
            .scanDeviceUnavailable: "The selected scanner could not be verified.",
            .scanOutputFolderFailedFormat: "The scan source folder could not be created: %@",
            .scanRollFilmMismatch: "The active Roll’s film type does not match the scan settings.",
            .scanNumberRangeExceeded: "The scan frame number limit was exceeded.",
            .noActiveScanner: "No active scanner.",
            .noInstalledPlugins: "(no installed plug-ins)",
            .scanProgressIdle: "Idle",
            .scanProgressConnecting: "Connecting to scanner",
            .scanProgressWarmingLamp: "Warming lamp",
            .scanProgressReady: "Ready to scan",
            .scanProgressPreviewScanning: "Preview scanning",
            .scanProgressWaitingForFilmHolder: "Waiting for film holder",
            .scanProgressScanningRGB: "Scanning film",
            .scanProgressScanningIR: "Scanning IR channel",
            .scanProgressProcessingNegative: "Processing scan data",
            .scanProgressRenderingLook: "Rendering preview develop",
            .scanProgressExporting: "Exporting",
            .scanProgressComplete: "Scan complete",
            .scanProgressScannerBusy: "Scanner busy",
            .scanProgressDisconnected: "Scanner disconnected",
            .scanProgressError: "Scan error",
            .scanProgressBackendFallbackActive: "Fallback backend active",
            .userPresetNameFormat: "Preset %d",
            .userPresetSavedFormat: "User preset saved: %@",
            .userPresetAppliedFormat: "User preset applied: %@",
            .userPresetDeletedFormat: "User preset deleted: %@",
            .virtualCopyCreatedFormat: "Virtual Copy created: %@",
            .proofCopyCreatedFormat: "Proof Copy created: %@",
            .proofCopyNameFormat: "%@ — Proof: %@",
            .noSelection: "None",
            .none: "None",
            .baseSection: "Base",
            .inspectorTabBasic: "Basic",
            .inspectorTabEdit: "Edit",
            .inspectorTabDefect: "GrainMend",
            .filmStock: "Film Stock",
            .densitySourceFormat: "Density source: %@ · measured base (edge/eyedropper) always takes priority.",
            .lightSource: "Light Source",
            .lightSourceFallbackNote: "Ignored when the film base is measured from the scan (measurement first). Applied only when no base can be measured.",
            .autoMatch: "Auto Match",
            .autoMatchRequiresValidatedProfile: "Automatic matching requires a profile validated with paired reference scans.",
            .scannerProfileStatusDraft: "Draft",
            .scannerProfileStatusRealOnly: "Real Scans",
            .scannerProfileStatusPairedSmoke: "Paired Test",
            .scannerProfileStatusPairedValidated: "Paired Validated",
            .profile: "Profile",
            .pick: "Pick",
            .pickBase: "Base Eyedropper",
            .pickBaseOnCanvas: "Click base on canvas",
            .pickBaseHelp: "Click unexposed film base on raw data before inversion to measure Dmin.",
            .baseRed: "Base R",
            .baseGreen: "Base G",
            .baseBlue: "Base B",
            .autoLevels: "Auto Levels",
            .autoColor: "Auto Color",
            .baseModeAuto: "Auto",
            .baseModeFilm: "Film",
            .baseModeManual: "Manual",
            .before: "Before",
            .unedited: "Unedited",
            .after: "After",
            .currentImage: "Current Image",
            .beforeSourceHelp: "Choose Before source",
            .raw: "Raw",
            .developed: "Developed",
            .compareSplitVertical: "Left/right Before/After",
            .compareSplitHorizontal: "Top/bottom Before/After",
            .zoomOut: "Zoom Out",
            .zoomIn: "Zoom In",
            .zoomPercentHelp: "Enter zoom percentage",
            .fitToScreen: "Fit",
            .actualSize: "Actual Size",
            .apply: "Apply",
            .mode: "Mode",
            .strength: "Strength",
            .shadowHue: "Shadow Hue",
            .highlightHue: "Highlight Hue",
            .shadows: "Shadows",
            .midtones: "Midtones",
            .highlights: "Highlights",
            .hue: "Hue",
            .saturationAbbrev: "Sat",
            .luminance: "Luminance",
            .blending: "Blending",
            .balance: "Balance",
            .canvasBackgroundMenu: "Background Color",
            .debugBadgeFormat: "Debug · %@",
            .basePickerOverlayPrompt: "Click unexposed film base (between frames or edge) · Esc to cancel",
            .scannerLabel: "Scanner",
            .resolution: "Resolution",
            .preview: "Preview",
            .bitDepth: "Bit Depth",
            .bitDepthUnavailable: "This scanner reports no bit depth option, so it can't scan.",
            .colorMode: "Mode",
            .perforation: "Perforation",
            .filmFrameFormat: "Frame Format",
            .hardwareScanArea: "Hardware Scan Area",
            .scanAreaWidth: "Width",
            .scanAreaHeight: "Height",
            .framesFormat: "Frames: %d",
            .flatbedFramesFormat: "Selected: %d",
            .flatbedFrameFormat: "Frame %d",
            .flatbedAddFrame: "Add Frame",
            .flatbedRemoveFrame: "Remove Frame",
            .flatbedCopyFrame: "Copy Frame",
            .flatbedPasteFrame: "Paste Frame",
            .flatbedDetectionMode: "Find Frames",
            .flatbedDetectionAutomatic: "Auto",
            .flatbedDetectionManual: "Manual",
            .flatbedRefreshFrames: "Find Frames Again",
            .flatbedPreviewRequired: "Run a preview and select at least one frame.",
            .flatbedGeometryMismatch: "The scanner returned an image with a different aspect ratio than the selected area.",
            .multiExposure: "Multi-Exposure",
            .infrared: "Infrared (IR)",
            .infraredHelp: "Scan the infrared channel for dust and scratch detection. Shown only on IR-capable devices.",
            .scanSection: "Scan",
            .cancel: "Cancel",
            .scan: "Scan",
            .importSource: "Import",
            .scanNext: "Scan Next",
            .scanCountFormat: "Scan x%d",
            .scannerSearching: "Looking for scanner — check the USB connection.",
            .scannerPluginMissingTitle: "No scanner plug-in is installed.",
            .scannerPluginMissingBody: "Film scanners are provided as separate plug-ins for license separation. Once installed, you can scan here. For now, start developing with image import.",
            .scannerPluginApprovalTitle: "Scanner Plug-in Approval",
            .scannerPluginVersion: "Version",
            .scannerPluginLicense: "License",
            .scannerPluginManifestPath: "Manifest Path",
            .scannerPluginManifestHash: "Manifest SHA-256",
            .scannerPluginExecutableHash: "Executable SHA-256",
            .scannerPluginApprove: "Approve",
            .scannerPluginRevokeApproval: "Revoke Approval",
            .scannerPluginApproved: "Approved",
            .scannerPluginApprovalRequired: "Approval Required",
            .scannerPluginChangedApprovalRequired: "Changed · Approval Required",
            .scannerPluginInvalidIdentity: "Invalid Identity",
            .scannerPluginTrustStoreUnavailable: "Approval Storage Unavailable",
            .scannerPluginNotReported: "Not Reported",
            .scannerSimulator: "Scanner Simulator",
            .scannerSimulatorHelp: "Built-in simulator for demonstrating the scan workflow without a plug-in.",
            .scannerTruth: "Scanner Truth",
            .transparency: "Transparency",
            .brightness: "Brightness",
            .contrast: "Contrast",
            .capabilityUnavailable: "Unavailable",
            .capabilityAvailable: "Available",
            .capabilityWaiting: "Capability response has not arrived yet.",
            .multiExposurePreviewHelp: "Multi-Exposure is not used for preview scans.",
            .multiExposureUnsupportedHelp: "The current backend does not expose real hardware exposure control, so this is disabled.",
            .multiExposureSupportedHelp: "Combines multiple scans only on devices where the backend supports exposure control.",
            .exportMainFlatMaster: "Main Flat Master",
            .exportOriginalRawTIFF: "Original Raw TIFF",
            .exportSidecar: "Sidecar (JSON + XMP)",
            .colorScannerInput: "Scanner Emulation",
            .colorWorking: "Working",
            .colorMonitor: "Monitor",
            .colorExport: "Export",
            .colorSoftProof: "Soft Proof",
            .colorGamutWarning: "Gamut Warning",
            .colorSampler: "RGB/Lab/HSV Sampler",
            .colorClippingOverlay: "Clipping Overlay",
            .choose: "Choose",
            .all: "All",
            .red: "Red",
            .orange: "Orange",
            .yellow: "Yellow",
            .green: "Green",
            .aqua: "Aqua",
            .blue: "Blue",
            .purple: "Purple",
            .magenta: "Magenta",
            .basicTone: "Basic Tone",
            .exposure: "Exposure",
            .toneHighlights: "Highlights",
            .whites: "Whites",
            .blacks: "Blacks",
            .density: "Density",
            .toneCurve: "Tone Curve",
            .lights: "Lights",
            .darks: "Darks",
            .color: "Color",
            .warmth: "Warmth",
            .tint: "Tint",
            .vibrance: "Vibrance",
            .saturation: "Saturation",
            .colorDepth: "Color Depth",
            .colorMixer: "Color Mixer",
            .colorGrading: "Color Grading",
            .bwToning: "B&W Toning",
            .calibration: "Calibration",
            .redPrimary: "Red Primary",
            .greenPrimary: "Green Primary",
            .bluePrimary: "Blue Primary",
            .detailEffects: "Detail & Effects",
            .noiseReduction: "Noise Reduction",
            .noiseReductionStrength: "NR Strength",
            .noiseReductionLuminance: "NR Luminance",
            .noiseReductionColor: "NR Color",
            .noiseReductionDarkTones: "NR Dark Tones",
            .noiseReductionDetail: "NR Detail",
            .noiseReductionGrainProtect: "NR Grain Protect",
            .grain: "Grain",
            .sharpness: "Sharpness",
            .clarity: "Clarity",
            .halation: "Halation",
            .vignette: "Vignette",
            .developerDebug: "Developer Debug",
            .developerMode: "Developer Mode",
            .developImportsAutomatically: "Develop new imports automatically",
            .defaultDefectMicroSpecks: "Detect micro specks by default",
            .defaultDefectMicroSpecksHelp: "Starting value for new frames, kept separately for auto and guided. Each frame keeps its own checkbox, so you can still turn it on or off per photo.",
            .debugOverlay: "Debug Overlay",
            .stage: "Stage",
            .full: "Full",
            .undoLastStroke: "Undo last stroke",
            .clearPaintedStrokes: "Clear painted strokes",
            .resetAppliedDefects: "Reset all applied defect removal",
            .removeDefects: "Remove Defects",
            .resetAdjustmentsHelp: "Reset all adjustment values except geometry (rotate/crop).",
            .autoToneHelp: "Auto Tone Command-U — use the histogram to adjust exposure, contrast, highlights, shadows, whites, blacks, and vibrance.",
            .autoWhiteBalanceHelp: "Auto White Balance Shift-Command-U — neutralize Warmth and Tint using gray-world.",
            .copy: "Copy",
            .closePanel: "Close",
            .copyAll: "Copy all",
            .paste: "Paste",
            .copyDevelopSettingsHelp: "Copy current frame develop settings.",
            .pasteDevelopSettingsHelp: "Paste copied develop settings.",
            .pasteScope: "Paste Scope",
            .pasteScopeHelp: "Choose which develop settings to paste.",
            .allSettings: "All Settings",
            .copyPaste: "Copy / Paste",
            .snapshot: "Snapshot",
            .noSnapshots: "No snapshots",
            .save: "Save",
            .saveSnapshotHelp: "Save current develop state as a Snapshot.",
            .applySnapshotHelp: "Apply selected Snapshot.",
            .compareSnapshotHelp: "Temporarily compare current settings with the selected Snapshot.",
            .current: "Current",
            .noHistory: "No history",
            .history: "History",
            .record: "Record",
            .recordHistoryHelp: "Record current develop state in History.",
            .applyHistoryHelp: "Apply selected History state.",
            .intensity: "Intensity",
            .geometry: "Geometry",
            .original: "Original",
            .custom: "Custom",
            .aspectRatio: "Aspect Ratio",
            .unlockCropAspect: "Unlock crop aspect ratio",
            .lockCropAspect: "Lock crop aspect ratio",
            .cropAspectLocked: "Crop aspect ratio locked",
            .cropAspectUnlocked: "Crop aspect ratio unlocked",
            .angle: "Angle",
            .cropArea: "Crop Area",
            .rotateLeft: "Rotate Left 90 Degrees",
            .rotateRight: "Rotate Right 90 Degrees",
            .resetTransform: "Reset Transform",
            .resetPhotoAngle: "Reset Photo Angle",
            .brushDefect: "Brush",
            .guidedDefect: "Guided",
            .brushDefectHelp: "Brush — paint over dust or scratches, then press Enter or Remove Defects.",
            .guidedDefectHelp: "Guided — drag a region, then press Enter or Remove Defects.",
            .cloneStamp: "Clone Stamp",
            .cloneStampHelp: "Clone Stamp — Option-click to set the source, then drag to paint.",
            .cloneStampSourceHint: "Option-click to set the clone source",
            .cloneStampSize: "Size",
            .cloneStampHardness: "Hardness",
            .cloneStampEditTitleFormat: "Clone stamp %dpx",
            .cloneStampEditSummary: "Clones pixels from the sampled source",
            .flipHorizontal: "Flip Horizontal",
            .flipVertical: "Flip Vertical",
            .baseReadoutFormat: "base %.2f %.2f %.2f",
            .batchFrameProgressFormat: "Frame %d/%d",
            .printPageProgressFormat: "Page %d/%d",
            .rating: "Rating",
            .resetRating: "Clear Rating",
            .ratingAccessibilityFormat: "Rating %d",
            .histogram: "Histogram",
            .shadowTone: "Shadow",
            .highlightTone: "Highlight",
            .rgbChannelOverlay: "RGB channel overlay",
            .redChannel: "Red channel",
            .greenChannel: "Green channel",
            .blueChannel: "Blue channel",
            .clippingChannelsFormat: "Clip %@",
            .resetSectionFormat: "Reset %@",
            .sliderKeyboardHelp: "Arrow keys adjust by 0.01; Shift-arrow adjusts by 0.10.",
            .baseMetricsFormat: "dmin %@ · dmax %@",
            .notAvailableAbbrev: "n/a",
            .softProofSummaryFormat: "%@, %@",
            .softProofProfileOnly: "Profile",
            .softProofPaperAndBlack: "Paper + Black",
            .softProofInvalidICC: "The selected ICC profile cannot be used for RGB soft proofing.",
            .printOutputProfileRequired: "PRINT export requires a valid RGB printer ICC profile.",
            .developingFramesFormat: "Developing %d frames",
            .generatingPreviewFormat: "Generating preview (%dpx)",
            .generatingSettledPreviewFormat: "Generating settled preview (%dpx)",
            .defectLayers: "GrainMend Layers",
            .disableLayer: "Disable layer (view before repair)",
            .enableLayer: "Enable layer (apply repair)",
            .hideMask: "Hide Mask",
            .showMask: "Show Mask",
            .deleteLayer: "Delete Layer",
            .defectDust: "Dust",
            .defectPinhole: "Pinhole",
            .defectScratchHorizontal: "Horizontal Scratch",
            .defectScratchVertical: "Vertical Scratch",
            .defectScratchDiagonal: "Diagonal Scratch",
            .defectEmulsionDamage: "Emulsion Damage",
            .defectMicroSpeck: "Micro Specks",
            .autoDefect: "Auto",
            .autoDefectHelp: "Auto — detect the full frame automatically, then remove defects",
            .frameCountFormat: "%d frames",
            .collapseFolder: "Collapse folder",
            .expandFolder: "Expand folder",
            .frameDisplayFormat: "Frame %d",
            .frameCopyDisplayFormat: "Frame %d Copy %d",
            .frameCompactCopyDisplayFormat: "Frame %d C%d",
            .namedFrameCopyDisplayFormat: "%@ Copy %d",
            .dpiUnspecified: "DPI unspecified",
            .ratingStarFormat: "%d star",
            .unrated: "Unrated",
            .unflagged: "Unflagged",
            .picked: "Pick",
            .rejected: "Reject",
            .selectionSummaryFormat: "%@ · %@",
            .selectionCountsFormat: "%d pick · %d reject",
            .starHelpFormat: "%d star",
            .clearPick: "Clear Pick",
            .clearReject: "Clear Reject",
            .quickExportHelpFormat: "%@ — %@ · %d dpi -> %@",
            .target: "Target",
            .filmProfile: "Film Profile",
            .look: "Look",
            .film: "Film",
            .process: "Process",
            .filmName: "Film Name",
            .scanFolderName: "Folder Name",
            .chooseScanFolder: "Choose Scan Folder",
            .untitledFilm: "Untitled Film",
            .userPreset: "User Preset",
            .noUserPresets: "No user presets",
            .saveUserPresetHelp: "Save the current develop settings as a user preset",
            .applyUserPresetHelp: "Apply the selected user preset",
            .deleteUserPresetHelp: "Delete the selected user preset",
            .delete: "Delete",
            .removeFromLibrary: "Remove",
            .libraryRemovalUndoAvailableFormat: "%d catalog item(s) removed · Undo available",
            .libraryRemovalRestoredFormat: "%d catalog item(s) restored",
            .scanProvenanceProtectedStatus: "This scanned original is part of the capture record and can’t be moved or removed yet.",
            .sourceDeletionPlanChangedStatus: "The source set changed. Review the deletion again.",
            .sourceDeletionUnavailableStatus: "Source deletion is unavailable until the catalog is ready.",
            .sourceDeletionMoveFailedStatus: "The source files could not be moved to Trash. The catalog was not changed.",
            .sourceDeletionCatalogFailedStatus: "The catalog could not be committed. The source files were restored.",
            .sourceDeletionRollbackFailedStatus: "The catalog was not changed, but some source files could not be restored. Recover them from Trash.",
            .moveSourceToTrash: "Move Source File to Trash",
            .sourceOffline: "Offline",
            .locateOriginal: "Locate Original",
            .locateMissingFolder: "Locate Missing Folder",
            .newFolder: "New Folder",
            .create: "Create",
            .showInFinder: "Show in Finder",
            .renameFolder: "Rename",
            .moveToFolder: "Move to Folder",
            .moveItemsHere: "Move Here",
            .sourceMoveCompleteFormat: "Moved %d source file(s).",
            .sourceMoveFailedStatus: "The source files could not be moved. Changes were rolled back.",
            .sourceMoveCatalogFailedStatus: "The catalog could not be committed. The source files were restored.",
            .sourceMoveCollisionStatus: "An item with the same name already exists in the destination folder.",
            .folderCreatedStatusFormat: "Created folder: %@",
            .folderCreateFailedStatus: "The folder could not be created.",
            .locateSourcePanelMessageFormat: "Last known location: %@",
            .locateFolderPanelMessageFormat: "Last known folder: %@",
            .sourceRelinkInvalid: "The selected file is not a readable supported image.",
            .sourceRelinkedFormat: "Reconnected %d catalog item(s).",
            .deleteSourceConfirmationTitle: "Move the source file to Trash?",
            .deleteSourceConfirmationMessageFormat: "%d catalog items share %d source file(s). This removes all of them from negaflow. %@",
            .virtualCopy: "Virtual Copy",
            .virtualCopyHelp: "Create a non-destructive copy that shares the current raw frame",
            .proofCopy: "Proof Copy",
            .proofCopyHelp: "Create a non-destructive copy tied to the selected proof profile",
            .dragDefectRegion: "Drag over a defect area",
            .undo: "Undo",
            .undoDefectRemovalHelp: "Undo the last defect removal edit",
            .defectsCountExcludedFormat: "%d defects (%d excluded)",
            .toneCurveEditorHelp: "Click to add points · drag to move · double-click to delete",
            .reset: "Reset",
            .previousFrame: "Previous Frame",
            .nextFrame: "Next Frame",
            .noImages: "No Images",
            .libraryFiles: "Files",
            .libraryAllPhotos: "All Photos",
            .libraryAllShort: "All",
            .libraryFolders: "Folders",
            .libraryFilmType: "Film Type",
            .libraryOffline: "Offline",
            .libraryCollections: "Collections",
            .librarySmartCollections: "Smart Collections",
            .librarySavedSearches: "Saved Searches",
            .libraryNewCollection: "New Collection",
            .libraryNewSmartCollection: "New Smart Collection",
            .librarySaveCurrentSearch: "Save Current Search",
            .libraryCollectionName: "Collection Name",
            .librarySearchName: "Search Name",
            .libraryAddToCollection: "Add to Collection",
            .libraryRemoveFromCollection: "Remove from Collection",
            .libraryInvalidStoredSearch: "Saved search cannot be read",
            .librarySearchPlaceholder: "Search Photos",
            .libraryClearSearch: "Clear Search",
            .libraryResultCountFormat: "%d of %d photos",
            .filterCurrentRoll: "Current Roll",
            .filterMinimumRatingFormat: "%d Stars & Up",
            .filterInfrared: "Infrared",
            .filterDefectRecipe: "Repair Recipe",
            .filterUnvalidatedProfile: "Unvalidated Profile",
            .filterMetadataUnknown: "Metadata Status Unknown",
            .libraryFilters: "Filters",
            .clearFilters: "Clear Filters",
            .exportFileSettings: "File",
            .exportQualitySettings: "Quality",
            .exportSourceSettings: "Source",
            .noMatchingPhotos: "No Matching Photos",
            .noLibraryFolders: "No folders",
            .libraryRefreshStatusFormat: "Library refreshed: %d new · %d reconnected · %d offline",
            .sortBy: "Sort By",
            .ascending: "Ascending",
            .descending: "Descending",
            .sortInputOrder: "Input Order",
            .sortTime: "Time",
            .sortName: "Name",
            .sortFlag: "Flag",
            .sortRating: "Rating",
            .sortSize: "Size",
            .filmstripScope: "Scope",
            .filmstripScopeFolder: "This Folder",
            .renamePhoto: "Rename Photo",
            .photoName: "Photo Name",
            .rename: "Rename",
            .filmstripHeightHelp: "Adjust filmstrip height",
            .frameCardSizeHelp: "Frame card size",
            .developTargetMain: "MAIN",
            .developTargetPrint: "PRINT",
            .filmTypeColorNegative: "Color Negative",
            .filmTypeSlide: "Slide",
            .filmTypeBWNegative: "B&W Negative",
            .filmTypeBWPositive: "B&W Positive",
            .filmGroupCinema: "Cinema",
            .filmGroupBWSlide: "B&W Slide",
            .filmLookDigitalOnly: "Film looks apply only to Digital Color and Digital B&W",
            .targetFilmSummaryFormat: "%@ · %@",
            .frameAccessibilityFormat: "%@, %@, %@",
            .dynamicRangeChannel: "DR",
            .rgb: "RGB",
            .redChannelShort: "R",
            .greenChannelShort: "G",
            .blueChannelShort: "B",
    ]
}
