import Foundation

extension AppLocalization {
    static let simplifiedChinesePhraseTable: [AppLocalizedPhrase: String] = [
        .idleStatus: "空闲",
        .settingsDiskTab: "磁盘",
        .diskLocationICloud: "iCloud",
        .diskLocationDesktop: "桌面",
        .diskLocationSpecificFolder: "文件夹",
        .diskLocationCustom: "自定义",
        .settingsScanTab: "扫描",
        .settingsDefaultScanRotationPicker: "扫描默认方向",
        .settingsDefaultScanRotationHelp: "应用于未设置方向的新扫描。扫描仪原始图像通常上下颠倒（180°）保存。",
        .diskRootFolderLabel: "negaflow 文件夹",
        .diskThumbnailsFolderLabel: "缩略图文件夹",
        .diskImportedSourcesFolderLabel: "导入原片默认移动文件夹",
        .diskCleanedRawFolderLabel: "校正图像缓存文件夹",
        .diskScanPreviewFolderLabel: "扫描预览缓存文件夹",
        .diskExportFolderLabel: "导出文件夹",
        .diskResetPathsButton: "将路径重置为默认值",
        .diskFolderStructureHelp: "扫描原片按日期/胶片类型/胶片名称整理。",
        .diskThumbnailCacheLabel: "缩略图缓存",
        .diskClearThumbnailCache: "清除缩略图缓存",
        .diskThumbnailCacheClearedStatus: "已清除缩略图缓存",
        .diskCacheSizeCalculating: "计算中",
        .diskLibraryBackupLabel: "目录备份",
        .diskLibraryBackupNow: "立即备份图库",
        .diskLibraryBackupCreatedStatus: "图库备份已创建",
        .diskLibraryBackupFailedStatus: "图库备份失败",
        .libraryRestoredFormat: "已恢复图库：%d 张照片",
        .libraryRecoveredFromBackupFormat: "已从备份恢复图库：%d 张照片",
        .libraryCatalogRepairedFormat: "已修复 %1$d 条不一致记录后打开图库：%2$d 张照片",
        .libraryCatalogMigratedFormat: "图库已从目录版本 %d 升级：%d 张照片",
        .libraryCatalogBlockedStatus: "无法安全打开图库目录，已保持原文件不变。",
        .libraryCatalogLockedStatus: "此图库已在另一个 negaflow 进程中打开。",
        .libraryCatalogLockUnavailableStatus: "无法获取图库写入锁，目录未被更改。",
        .libraryCatalogNewerVersionFormat: "此图库使用较新的目录版本 %d，已保持原文件不变。",
        .libraryCatalogMissingAuthoritativeDataStatus: "图库修复配方不完整且未找到有效备份，已保持目录不变。",
        .librarySelectedBackupAppliedFormat: "已恢复所选图库备份：%d 张照片",
        .libraryPendingRestoreFailedStatus: "无法应用已计划的图库恢复，恢复计划已保留。",
        .diskLibraryBackupBrowse: "查看备份",
        .libraryBackupEmpty: "没有备份",
        .libraryBackupLoadFailed: "无法载入备份",
        .libraryBackupRefresh: "刷新",
        .libraryBackupUnknownDate: "日期未知",
        .libraryBackupChecksummed: "校验和已验证",
        .libraryBackupLegacy: "旧格式",
        .libraryBackupIncompatible: "不兼容",
        .libraryBackupDamaged: "已损坏",
        .libraryBackupCountsFormat: "%d 张照片 · %d 个修复配方",
        .libraryBackupRestoreSelected: "恢复所选备份",
        .libraryBackupRestoreConfirmationTitle: "恢复所选备份？",
        .libraryBackupRestoreConfirmationMessage: "当前图库将另行保留，恢复将在下次启动时应用。",
        .libraryBackupScheduleRestore: "计划恢复",
        .libraryBackupRestorePending: "将在下次启动时恢复",
        .libraryBackupCancelPending: "取消恢复计划",
        .libraryBackupRestoreScheduleFailed: "无法计划恢复",
        .done: "完成",
        .noScannerStatus: "无扫描仪",
        .autoWhiteBalanceStatus: "自动白平衡",
        .autoToneStatus: "自动色调",
        .filmBaseSampleFailed: "片基取样失败 — 源图像未加载",
        .filmBasePickedFormat: "片基已设定：%.3f %.3f %.3f",
        .noFramesToSync: "没有可同步的照片",
        .whiteBalanceSyncedFormat: "白平衡已同步：%d 张",
        .grainMendBrushEditTitleFormat: "GrainMend · 画笔 · %d 笔",
        .grainMendAutoEditTitleFormat: "GrainMend · 自动 · %d 处",
        .grainMendGuidedEditTitleFormat: "GrainMend · 引导 · %d 个区域",
        .brushEditSummary: "对自选区域进行精细检测与修复",
        .defectsClearedStatus: "瑕疵修复已重置",
        .removingDefectsStatus: "正在移除瑕疵",
        .removingDefectsFailedStatus: "瑕疵移除失败",
        .imageLoadFailedFormat: "图像加载失败：%@",
        .historyNameFormat: "历史记录 %d",
        .historyRecordedFormat: "历史记录已保存：%@",
        .historyAppliedFormat: "历史记录已应用：%@",
        .developSettingsCopiedFormat: "显影设置已复制：%@",
        .noDevelopSettingsToPaste: "没有可粘贴的显影设置",
        .chooseDevelopPasteScope: "请选择要粘贴的显影设置范围",
        .developSettingsPasted: "显影设置已粘贴",
        .developSettingsPartiallyPastedFormat: "已粘贴部分显影设置（%@）",
        .developSettingsPasteStatusFormat: "%@：%@ -> %@",
        .snapshotSavedFormat: "快照已存储：%@",
        .snapshotAppliedFormat: "快照已应用：%@",
        .snapshotCompareEnded: "A/B 对比结束：当前设置",
        .snapshotComparingFormat: "A/B 对比中：%@",
        .snapshotNameFormat: "快照 %d",
        .exportingStatus: "正在导出",
        .exportDownloadingSourcesFormat: "正在下载原始文件 %@/%@",
        .exportSourceDownloadFailed: "无法下载 iCloud 原始文件，已中止导出",
        .exportCompleteFormat: "导出完成 -> %@",
        .exportCompleteWithPairsFormat: "导出完成 -> %@",
        .exportDestinationConflict: "输出文件已存在，导出已停止。",
        .exportFailedFormat: "导出失败：%@",
        .importPanelPrompt: "导入",
        .importPanelMessage: "选择要显影的图像（RAW/DNG/TIFF/PNG/JPG）",
        .noImportableImages: "没有可导入的图像（支持：RAW/DNG/TIFF/PNG/JPG）",
        .importLibraryRegistrationFailedStatus: "无法将导入的图像添加到图库",
        .importCompleteFormat: "已导入 %d 张图像",
        .importCompleteUnsupportedFormat: "已导入 %d 张图像（已跳过 %d 个不支持的文件）",
        .importCompleteDuplicatesFormat: "已导入 %d 张图像（已跳过 %d 个重复文件）",
        .importCompleteUnsupportedDuplicatesFormat: "已导入 %d 张图像（已跳过 %d 个不支持的文件和 %d 个重复文件）",
        .importFolder: "导入文件夹",
        .importImageShort: "图像",
        .importFolderShort: "文件夹",
        .folderImportPanelMessage: "选择要加入图库的文件夹。文件夹内的图像文件将被导入。",
        .folderImportCompleteFormat: "已导入 %d 张图像（%d 个文件夹）",
        .folderImportCompleteEmptyFormat: "已添加 %d 个空文件夹",
        .detectingDefectsStatus: "正在检测瑕疵",
        .detectingDefectsFailedStatus: "瑕疵检测失败",
        .noDefectsStatus: "未发现瑕疵",
        .automaticDefectFalsePositiveRiskStatus: "误检风险较高。",
        .settingsMemoryCacheSection: "内存缓存",
        .settingsMemoryCacheModeAutomatic: "自动",
        .settingsMemoryCacheModeManual: "手动",
        .settingsMemoryCacheInstalledMemoryFormat: "本机内存 %@",
        .settingsMemoryCacheCleanedRawLabel: "去瑕疵原片",
        .settingsMemoryCacheDevelopedLabel: "冲洗结果",
        .settingsMemoryCacheFramesFormat: "%d 张",
        .settingsMemoryCacheEstimateFormat: "最多常驻约 %@ · 占内存 %d%%",
        .settingsMemoryCacheAutomaticHelp: "根据已安装内存自动确定上限。超出上限的帧会从最旧的开始释放，重新打开时再次冲洗。",
        .settingsMemoryCacheManualHelp: "使用你设定的数值。上限为已安装内存的 70%%。",
        .settingsMemoryCacheResetToAutomatic: "恢复为自动值",
        .defectsCountFormat: "%d 处瑕疵",
        .confidenceSummaryFormat: "%@ · 置信度 %.0f%%",
        .grainMendIREditTitleFormat: "GrainMend · IR · %d 处",
        .infraredCleanDetectingStatus: "正在通过红外通道检测瑕疵",
        .infraredCleanAppliedFormat: "已通过红外通道移除 %d 处瑕疵",
        .infraredCleanNoDefectsStatus: "红外通道中未发现瑕疵",
        .infraredCleanSkippedBWStatus: "已跳过红外除尘：银盐黑白胶片不透红外线",
        .infraredCleanCoverageAbortStatus: "红外除尘已中止：瑕疵蒙版过大（请检查胶片类型或红外对齐）",
        .infraredCleanFailedStatus: "红外瑕疵检测失败",
        .demoModeStatus: "演示模式",
        .scannerWaitingStatus: "正在等待扫描仪连接",
        .scannerPluginMissingStartImportStatus: "未安装扫描仪插件 — 请先从导入图像开始",
        .scannerPluginMissingStatus: "未安装扫描仪插件",
        .scannerPluginApprovalRequiredStatus: "需要批准扫描仪插件",
        .scannerPluginTrustStoreUnavailableStatus: "无法使用扫描仪插件批准存储",
        .scannerPluginApprovedStatus: "已批准扫描仪插件",
        .scannerPluginApprovalFailedStatus: "扫描仪插件批准失败",
        .scannerPluginApprovalRevokedStatus: "已撤销扫描仪插件批准",
        .scannerAppConflictWarningFormat: "%@ 正在运行 — 退出后再重新检测扫描仪。",
        .noScannerUseDemoStatus: "未找到扫描仪 — 请连接 USB 或开启演示模式。",
        .previewScanPreparing: "正在准备预览扫描",
        .filmScanPreparing: "正在准备胶片扫描",
        .frameScanCompleteFormat: "照片 %d 扫描完成：%d x %d%@",
        .frameScanErrorFormat: "照片 %d 扫描出错：%@",
        .framesScanCompleteFormat: "已扫描 %d 张",
        .scanCanceled: "扫描已取消",
        .scanWorkflowPersistenceFailed: "无法将扫描状态保存到图库目录。",
            .exportFolderUnavailableFormat: "无法使用导出文件夹 %@ —— %@",
        .scanWorkflowInvalidState: "扫描工作流状态无效。",
        .scanInterruptedFailureReason: "应用已关闭，无法确认硬件采集是否完成。",
        .scanDeviceUnavailable: "无法验证所选扫描仪。",
        .scanOutputFolderFailedFormat: "无法创建扫描原件文件夹：%@",
        .scanRollFilmMismatch: "当前 Roll 的胶片类型与扫描设置不一致。",
        .scanNumberRangeExceeded: "已超出扫描帧编号上限。",
        .noActiveScanner: "没有正在使用的扫描仪。",
        .noInstalledPlugins: "（未安装任何插件）",
        .scanProgressIdle: "空闲",
        .scanProgressConnecting: "正在连接扫描仪",
        .scanProgressWarmingLamp: "正在预热灯管",
        .scanProgressReady: "准备就绪",
        .scanProgressPreviewScanning: "正在预览扫描",
        .scanProgressWaitingForFilmHolder: "正在等待片夹",
        .scanProgressScanningRGB: "正在扫描胶片",
        .scanProgressScanningIR: "正在扫描红外通道",
        .scanProgressProcessingNegative: "正在处理扫描数据",
        .scanProgressRenderingLook: "正在生成显影预览",
        .scanProgressExporting: "正在导出",
        .scanProgressComplete: "扫描完成",
        .scanProgressScannerBusy: "扫描仪忙",
        .scanProgressDisconnected: "扫描仪已断开",
        .scanProgressError: "扫描出错",
        .scanProgressBackendFallbackActive: "正在使用备用后端",
        .userPresetNameFormat: "预设 %d",
        .userPresetSavedFormat: "用户预设已存储：%@",
        .userPresetAppliedFormat: "用户预设已应用：%@",
        .userPresetDeletedFormat: "用户预设已删除：%@",
        .virtualCopyCreatedFormat: "虚拟副本已创建：%@",
        .proofCopyCreatedFormat: "校样副本已创建：%@",
        .proofCopyNameFormat: "%@ — 校样：%@",
        .noSelection: "未选择",
        .none: "无",
        .baseSection: "片基",
        .inspectorTabBasic: "基础",
        .inspectorTabEdit: "编辑",
        .inspectorTabDefect: "GrainMend",
        .filmStock: "胶片型号",
        .densitySourceFormat: "密度来源：%@ · 实测片基（片边/吸管）始终优先。",
        .lightSource: "光源",
        .lightSourceFallbackNote: "当能从扫描中实测片基时,光源配置将被忽略(实测优先)。仅在无法实测片基时应用。",
        .autoMatch: "自动匹配",
        .autoMatchRequiresValidatedProfile: "自动匹配需要使用成对参考扫描验证的配置文件。",
        .scannerProfileStatusDraft: "草稿",
        .scannerProfileStatusRealOnly: "实测扫描",
        .scannerProfileStatusPairedSmoke: "配对测试",
        .scannerProfileStatusPairedValidated: "配对验证通过",
        .profile: "配置文件",
        .pick: "拾取",
        .pickBase: "片基吸管",
        .pickBaseOnCanvas: "在画布上点按片基",
        .pickBaseHelp: "在反相前的原始数据上点按未曝光的片基，以实测 Dmin。",
        .baseRed: "片基 R",
        .baseGreen: "片基 G",
        .baseBlue: "片基 B",
        .autoLevels: "自动色阶",
        .autoColor: "自动颜色",
        .baseModeAuto: "自动",
        .baseModeFilm: "胶片",
        .baseModeManual: "手动",
        .before: "调整前",
        .unedited: "未调整",
        .after: "调整后",
        .currentImage: "当前图像",
        .beforeSourceHelp: "选择“调整前”的来源",
        .raw: "原片",
        .developed: "显影后",
        .compareSplitVertical: "左右对比调整前/调整后",
        .compareSplitHorizontal: "上下对比调整前/调整后",
        .zoomOut: "缩小",
        .zoomIn: "放大",
        .zoomPercentHelp: "输入缩放百分比",
        .fitToScreen: "适合窗口",
        .actualSize: "实际大小",
        .apply: "应用",
        .mode: "模式",
        .strength: "强度",
        .shadowHue: "阴影色相",
        .highlightHue: "高光色相",
        .shadows: "阴影",
        .midtones: "中间调",
        .highlights: "高光",
        .hue: "色相",
        .saturationAbbrev: "饱和度",
        .luminance: "明亮度",
        .blending: "混合",
        .balance: "平衡",
        .canvasBackgroundMenu: "背景颜色",
        .debugBadgeFormat: "调试 · %@",
        .basePickerOverlayPrompt: "点按未曝光的片基（画幅之间或片边） · 按 Esc 取消",
        .scannerLabel: "扫描仪",
        .resolution: "分辨率",
        .preview: "预览",
        .bitDepth: "位深度",
        .bitDepthUnavailable: "此扫描仪未报告位深度选项，因此无法扫描。",
        .colorMode: "模式",
        .scanColorModeGrayUnstable: "Gray (不稳定)",
        .perforation: "齿孔",
        .filmFrameFormat: "画幅格式",
        .hardwareScanArea: "硬件扫描区域",
        .scanAreaWidth: "宽度",
        .scanAreaHeight: "高度",
        .framesFormat: "照片：%d",
        .flatbedFramesFormat: "已选择：%d",
        .flatbedFrameFormat: "画幅 %d",
        .flatbedAddFrame: "添加画幅",
        .flatbedRemoveFrame: "删除画幅",
        .flatbedCopyFrame: "复制画幅",
        .flatbedPasteFrame: "粘贴画幅",
        .flatbedDetectionMode: "查找画幅",
        .flatbedDetectionAutomatic: "自动",
        .flatbedDetectionManual: "手动",
        .flatbedRefreshFrames: "重新查找画幅",
        .flatbedPreviewRequired: "请先预览并至少选择一个画幅。",
        .flatbedGeometryMismatch: "扫描仪返回的图像宽高比与所选区域不一致。",
        .multiExposure: "多重曝光",
        .infrared: "红外 (IR)",
        .infraredHelp: "扫描红外通道以检测灰尘和划痕。仅在支持红外的设备上显示。",
        .scanSection: "扫描",
        .cancel: "取消",
        .scan: "扫描",
        .importSource: "导入",
        .scanNext: "扫描下一张",
        .scanCountFormat: "扫描 x%d",
        .scannerSearching: "正在查找扫描仪 — 请检查 USB 连接。",
        .scannerPluginMissingTitle: "未安装扫描仪插件。",
        .scannerPluginMissingBody: "为了隔离许可证，胶片扫描仪以独立插件的形式提供。安装后即可在此扫描。现在可以先通过导入图像开始显影。",
        .scannerPluginApprovalTitle: "扫描仪插件批准",
        .scannerPluginVersion: "版本",
        .scannerPluginLicense: "许可证",
        .scannerPluginManifestPath: "Manifest 路径",
        .scannerPluginManifestHash: "Manifest SHA-256",
        .scannerPluginExecutableHash: "可执行文件 SHA-256",
        .scannerPluginApprove: "批准",
        .scannerPluginRevokeApproval: "撤销批准",
        .scannerPluginApproved: "已批准",
        .scannerPluginApprovalRequired: "需要批准",
        .scannerPluginChangedApprovalRequired: "已更改 · 需要重新批准",
        .scannerPluginInvalidIdentity: "身份无效",
        .scannerPluginTrustStoreUnavailable: "批准存储不可用",
        .scannerPluginNotReported: "未报告",
        .scannerSimulator: "扫描仪模拟器",
        .scannerSimulatorHelp: "内置模拟器，无需插件即可演示扫描流程。",
        .scannerTruth: "扫描仪信息",
        .transparency: "透射稿",
        .brightness: "亮度",
        .contrast: "对比度",
        .capabilityUnavailable: "不可用",
        .capabilityAvailable: "可用",
        .capabilityWaiting: "尚未收到功能信息。",
        .multiExposurePreviewHelp: "预览扫描不使用多重曝光。",
        .multiExposureUnsupportedHelp: "当前后端未提供真实的硬件曝光控制，该功能已停用。",
        .multiExposureSupportedHelp: "仅在后端支持曝光控制的设备上合成多次扫描。",
        .exportMainFlatMaster: "MAIN 无调整母版",
        .exportOriginalRawTIFF: "原始扫描 TIFF",
        .exportSidecar: "附属文件 (JSON + XMP)",
        .colorScannerInput: "扫描仪模拟",
        .colorWorking: "工作空间",
        .colorMonitor: "显示器",
        .colorExport: "导出",
        .colorSoftProof: "软打样",
        .colorGamutWarning: "色域警告",
        .colorSampler: "RGB/Lab/HSV 取样器",
        .colorClippingOverlay: "剪切叠加",
        .choose: "选择",
        .all: "全部",
        .red: "红色",
        .orange: "橙色",
        .yellow: "黄色",
        .green: "绿色",
        .aqua: "浅绿色",
        .blue: "蓝色",
        .purple: "紫色",
        .magenta: "洋红色",
        .basicTone: "基本色调",
        .exposure: "曝光度",
        .toneHighlights: "高光",
        .whites: "白色色阶",
        .blacks: "黑色色阶",
        .density: "密度",
        .toneCurve: "色调曲线",
        .lights: "亮色调",
        .darks: "暗色调",
        .color: "颜色",
        .warmth: "色温",
        .tint: "色调",
        .vibrance: "鲜艳度",
        .saturation: "饱和度",
        .colorDepth: "色彩深度",
        .colorMixer: "混色器",
        .colorGrading: "颜色分级",
        .bwToning: "黑白调色",
        .calibration: "校准",
        .redPrimary: "红原色",
        .greenPrimary: "绿原色",
        .bluePrimary: "蓝原色",
        .detailEffects: "细节与效果",
        .noiseReduction: "降噪",
        .noiseReductionStrength: "降噪强度",
        .noiseReductionLuminance: "降噪明亮度",
        .noiseReductionColor: "降噪颜色",
        .noiseReductionDarkTones: "降噪暗部",
        .noiseReductionDetail: "降噪细节",
        .noiseReductionGrainProtect: "颗粒保护",
        .grain: "颗粒",
        .sharpness: "锐化",
        .clarity: "清晰度",
        .halation: "光晕",
        .vignette: "暗角",
        .developerDebug: "开发者调试",
        .developerMode: "开发者模式",
        .developImportsAutomatically: "自动显影新导入的照片",
        .defaultDefectMicroSpecks: "默认检测微小颗粒",
        .defaultDefectMicroSpecksHelp: "新照片的初始值，自动与引导分别记住。每张照片都有各自的复选框，仍可单独开启或关闭。",
        .debugOverlay: "调试叠加",
        .stage: "阶段",
        .full: "全图",
        .undoLastStroke: "撤销最后一笔",
        .clearPaintedStrokes: "清除已涂抹的笔画",
        .resetAppliedDefects: "重置所有已应用的瑕疵修复",
        .removeDefects: "移除瑕疵",
        .resetAdjustmentsHelp: "重置除几何（旋转/裁剪）外的所有调整值。",
        .autoToneHelp: "自动色调 Command-U — 依据直方图调整曝光度、对比度、高光、阴影、白色色阶、黑色色阶和鲜艳度。",
        .autoWhiteBalanceHelp: "自动白平衡 Shift-Command-U — 使用灰度世界算法中和色温与色调。",
        .copy: "拷贝",
        .closePanel: "关闭",
        .copyAll: "全部拷贝",
        .paste: "粘贴",
        .copyDevelopSettingsHelp: "拷贝当前照片的显影设置。",
        .pasteDevelopSettingsHelp: "粘贴已拷贝的显影设置。",
        .pasteScope: "粘贴范围",
        .pasteScopeHelp: "选择要粘贴哪些显影设置。",
        .allSettings: "全部设置",
        .copyPaste: "拷贝 / 粘贴",
        .snapshot: "快照",
        .noSnapshots: "没有快照",
        .save: "存储",
        .saveSnapshotHelp: "将当前显影状态存储为快照。",
        .applySnapshotHelp: "应用所选快照。",
        .compareSnapshotHelp: "将当前设置与所选快照进行临时对比。",
        .current: "当前",
        .noHistory: "无历史记录",
        .history: "历史记录",
        .record: "记录",
        .recordHistoryHelp: "将当前显影状态记录到历史记录。",
        .applyHistoryHelp: "应用所选历史状态。",
        .intensity: "强度",
        .geometry: "几何",
        .original: "原始",
        .custom: "自定",
        .aspectRatio: "长宽比",
        .unlockCropAspect: "解锁裁剪长宽比",
        .lockCropAspect: "锁定裁剪长宽比",
        .cropAspectLocked: "裁剪长宽比已锁定",
        .cropAspectUnlocked: "裁剪长宽比已解锁",
        .angle: "角度",
        .cropArea: "裁剪区域",
        .rotateLeft: "向左旋转 90°",
        .rotateRight: "向右旋转 90°",
        .resetTransform: "重置变换",
        .resetPhotoAngle: "重置照片角度",
        .brushDefect: "画笔",
        .guidedDefect: "引导",
        .brushDefectHelp: "画笔 — 涂抹灰尘或划痕，然后按 Enter 或“移除瑕疵”。",
        .guidedDefectHelp: "引导 — 拖选一个区域，然后按 Enter 或“移除瑕疵”。",
        .cloneStamp: "克隆图章",
        .cloneStampHelp: "克隆图章 — 按住 ⌥ 点按设置源点，然后拖动进行复制。",
        .cloneStampSourceHint: "按住 ⌥ 点按以设置克隆源",
        .cloneStampSize: "大小",
        .cloneStampHardness: "硬度",
        .cloneStampEditTitleFormat: "克隆图章 %dpx",
        .cloneStampEditSummary: "复制所选源的像素",
        .flipHorizontal: "水平翻转",
        .flipVertical: "垂直翻转",
        .baseReadoutFormat: "片基 %.2f %.2f %.2f",
        .batchFrameProgressFormat: "照片 %d/%d",
        .printPageProgressFormat: "页面 %d/%d",
        .rating: "星级",
        .resetRating: "清除星级",
        .ratingAccessibilityFormat: "星级 %d",
        .histogram: "直方图",
        .shadowTone: "阴影",
        .highlightTone: "高光",
        .rgbChannelOverlay: "RGB 通道叠加",
        .redChannel: "红色通道",
        .greenChannel: "绿色通道",
        .blueChannel: "蓝色通道",
        .clippingChannelsFormat: "剪切 %@",
        .resetSectionFormat: "重置%@",
        .sliderKeyboardHelp: "方向键调整 0.01；Shift+方向键调整 0.10。",
        .baseMetricsFormat: "dmin %@ · dmax %@",
        .notAvailableAbbrev: "n/a",
        .softProofSummaryFormat: "%@，%@",
        .softProofProfileOnly: "配置文件",
        .softProofPaperAndBlack: "纸张 + 黑色油墨",
        .softProofInvalidICC: "所选 ICC 配置文件不能用于 RGB 软打样。",
        .printOutputProfileRequired: "PRINT 导出需要有效的 RGB 打印机 ICC 配置文件。",
        .developingFramesFormat: "正在显影 %d 张",
        .generatingPreviewFormat: "正在生成预览 (%dpx)",
        .generatingSettledPreviewFormat: "正在生成最终预览 (%dpx)",
        .defectLayers: "GrainMend 图层",
        .disableLayer: "停用图层（查看修复前）",
        .enableLayer: "启用图层（应用修复）",
        .hideMask: "隐藏蒙版",
        .showMask: "显示蒙版",
        .deleteLayer: "删除图层",
        .defectDust: "灰尘",
        .defectPinhole: "针孔",
        .defectScratchHorizontal: "水平划痕",
        .defectScratchVertical: "垂直划痕",
        .defectScratchDiagonal: "斜向划痕",
        .defectEmulsionDamage: "药膜损伤",
        .defectMicroSpeck: "微小颗粒",
        .autoDefect: "自动",
        .autoDefectHelp: "自动 — 自动检测整幅画面并移除瑕疵",
        .frameCountFormat: "%d 张",
        .collapseFolder: "折叠文件夹",
        .expandFolder: "展开文件夹",
        .frameDisplayFormat: "照片 %d",
        .frameCopyDisplayFormat: "照片 %d 副本 %d",
        .frameCompactCopyDisplayFormat: "照片 %d 副本%d",
        .namedFrameCopyDisplayFormat: "%@ 副本 %d",
        .dpiUnspecified: "未指定 DPI",
        .ratingStarFormat: "%d 星",
        .unrated: "无星级",
        .unflagged: "无旗标",
        .picked: "留用",
        .rejected: "排除",
        .selectionSummaryFormat: "%@ · %@",
        .selectionCountsFormat: "留用 %d · 排除 %d",
        .starHelpFormat: "%d 星",
        .clearPick: "取消留用",
        .clearReject: "取消排除",
        .quickExportHelpFormat: "%@ — %@ · %d dpi -> %@",
        .target: "目标",
        .filmProfile: "胶片配置文件",
        .look: "风格",
        .film: "胶片",
        .process: "冲洗工艺",
        .filmName: "胶片名称",
        .scanFolderName: "文件夹名称",
        .chooseScanFolder: "选择扫描文件夹",
        .untitledFilm: "未命名胶片",
        .userPreset: "用户预设",
        .noUserPresets: "没有用户预设",
        .saveUserPresetHelp: "将当前显影设置存储为用户预设",
        .applyUserPresetHelp: "应用所选用户预设",
        .deleteUserPresetHelp: "删除所选用户预设",
        .delete: "删除",
        .removeFromLibrary: "移除",
        .libraryRemovalUndoAvailableFormat: "已移除 %d 个目录项目 · 可撤销",
        .libraryRemovalRestoredFormat: "已恢复 %d 个目录项目",
        .scanProvenanceProtectedStatus: "此扫描原件属于采集记录，目前无法移动或移除。",
        .sourceDeletionPlanChangedStatus: "源文件关联已更改，请重新确认删除对象。",
        .sourceDeletionUnavailableStatus: "目录准备完成前无法删除源文件。",
        .sourceDeletionMoveFailedStatus: "无法将源文件移到废纸篓，目录未被更改。",
        .sourceDeletionCatalogFailedStatus: "无法提交目录，源文件已恢复。",
        .sourceDeletionRollbackFailedStatus: "目录未被更改，但部分源文件无法恢复，请从废纸篓中恢复。",
        .moveSourceToTrash: "将源文件移到废纸篓",
        .sourceOffline: "离线",
        .locateOriginal: "查找原始文件",
        .locateMissingFolder: "查找缺失文件夹",
        .newFolder: "新建文件夹",
        .create: "创建",
        .showInFinder: "在 Finder 中显示",
        .renameFolder: "重命名",
        .moveToFolder: "移到文件夹",
        .moveItemsHere: "移到这里",
        .sourceMoveCompleteFormat: "已移动 %d 个原始文件。",
        .sourceMoveFailedStatus: "无法移动原始文件，已撤销更改。",
        .sourceMoveCatalogFailedStatus: "无法提交目录，原始文件已恢复到原位置。",
        .sourceMoveCollisionStatus: "目标文件夹中已有同名文件或文件夹。",
        .folderCreatedStatusFormat: "已创建文件夹：%@",
        .folderCreateFailedStatus: "无法创建文件夹。",
        .locateSourcePanelMessageFormat: "上次已知位置：%@",
        .locateFolderPanelMessageFormat: "上次已知文件夹：%@",
        .sourceRelinkInvalid: "所选文件不是可读取的受支持图像。",
        .sourceRelinkedFormat: "已重新连接 %d 个目录项目。",
        .deleteSourceConfirmationTitle: "要将源文件移到废纸篓吗？",
        .deleteSourceConfirmationMessageFormat: "%d 个目录项目共享 %d 个源文件。它们将全部从 negaflow 中移除。%@",
        .virtualCopy: "虚拟副本",
        .virtualCopyHelp: "创建共享同一原始照片的非破坏性副本",
        .proofCopy: "校样副本",
        .proofCopyHelp: "创建与所选校样配置文件关联的非破坏性副本",
        .dragDefectRegion: "在瑕疵区域上拖动",
        .undo: "撤销",
        .redo: "重做",
        .undoDefectRemovalHelp: "撤销上一次瑕疵修复",
        .defectsCountExcludedFormat: "%d 处瑕疵（已排除 %d 处）",
        .toneCurveEditorHelp: "点按添加节点 · 拖动移动 · 双击删除",
        .reset: "重置",
        .previousFrame: "上一张",
        .nextFrame: "下一张",
        .noImages: "无图像",
        .libraryFiles: "文件",
        .libraryAllPhotos: "所有照片",
        .libraryAllShort: "全部",
        .libraryFolders: "文件夹",
        .libraryFilmType: "胶片类型",
        .libraryOffline: "离线",
        .libraryCollections: "收藏集",
        .librarySmartCollections: "智能收藏集",
        .librarySavedSearches: "已存搜索",
        .libraryNewCollection: "新建收藏集",
        .libraryNewSmartCollection: "新建智能收藏集",
        .librarySaveCurrentSearch: "保存当前搜索",
        .libraryCollectionName: "收藏集名称",
        .librarySearchName: "搜索名称",
        .libraryAddToCollection: "添加到收藏集",
        .libraryRemoveFromCollection: "从收藏集中移除",
        .libraryInvalidStoredSearch: "无法读取已存搜索",
        .librarySearchPlaceholder: "搜索照片",
        .libraryClearSearch: "清除搜索",
        .libraryResultCountFormat: "%d / %d 张照片",
        .filterCurrentRoll: "当前胶卷",
        .filterMinimumRatingFormat: "%d 星及以上",
        .filterInfrared: "红外",
        .filterDefectRecipe: "修复配方",
        .filterUnvalidatedProfile: "未验证的配置文件",
        .filterMetadataUnknown: "元数据状态未知",
        .libraryFilters: "筛选",
        .clearFilters: "清除筛选条件",
        .exportFileSettings: "文件",
        .exportQualitySettings: "质量",
        .exportSourceSettings: "源文件",
        .noMatchingPhotos: "没有匹配的照片",
        .noLibraryFolders: "无文件夹",
        .libraryRefreshStatusFormat: "图库已刷新：新增 %d 个 · 重新连接 %d 个 · 离线 %d 个",
        .sortBy: "排序",
        .ascending: "升序",
        .descending: "降序",
        .sortInputOrder: "导入顺序",
        .sortTime: "时间",
        .sortName: "名称",
        .sortFlag: "旗标",
        .sortRating: "星级",
        .sortSize: "大小",
        .filmstripScope: "显示范围",
        .filmstripScopeFolder: "该文件夹",
        .renamePhoto: "重命名照片",
        .photoName: "照片名称",
        .rename: "重命名",
        .filmstripHeightHelp: "调整胶片栏高度",
        .frameCardSizeHelp: "缩略图大小",
        .developTargetMain: "MAIN",
        .developTargetPrint: "PRINT",
        .filmTypeColorNegative: "彩色负片",
        .filmTypeSlide: "反转片",
        .filmTypeBWNegative: "黑白负片",
        .filmTypeBWPositive: "黑白正片",
        .filmGroupCinema: "电影",
        .filmGroupBWSlide: "黑白反转片",
        .filmLookDigitalOnly: "胶片风格仅适用于 Digital Color 与 Digital B&W",
        .targetFilmSummaryFormat: "%@ · %@",
        .frameAccessibilityFormat: "%@，%@，%@",
        .dynamicRangeChannel: "DR",
        .rgb: "RGB",
        .redChannelShort: "R",
        .greenChannelShort: "G",
        .blueChannelShort: "B",
    ]


}
