#pragma once

/* The fixed vocabularies a develop request is written in - format, film, look route, stage. */

#include "negaflow/abi/platform.h"

#ifdef __cplusplus
extern "C" {
#endif

#define NF_EXPORT_FORMAT_PNG16 0U
#define NF_EXPORT_FORMAT_TIFF16 1U
#define NF_EXPORT_FORMAT_JPEG8 2U

#define NF_FILM_TYPE_COLOR 0U
#define NF_FILM_TYPE_BLACK_AND_WHITE 1U

#define NF_FILM_POLARITY_NEGATIVE 0U
#define NF_FILM_POLARITY_POSITIVE 1U

#define NF_BASE_ESTIMATION_AUTO 0U
#define NF_BASE_ESTIMATION_PRESET 1U
#define NF_BASE_ESTIMATION_MANUAL 2U

#define NF_DEVELOP_BASE_SOURCE_MANUAL 0U
#define NF_DEVELOP_BASE_SOURCE_AUTO_SCENE_EDGE 1U
#define NF_DEVELOP_BASE_SOURCE_AUTO_FALLBACK 2U
#define NF_DEVELOP_BASE_SOURCE_AUTO_CONNECTED_COMPONENT 3U
#define NF_DEVELOP_BASE_SOURCE_AUTO_CONTINUOUS_BORDER 4U
#define NF_DEVELOP_BASE_SOURCE_AUTO_DISTRIBUTED_MASK 5U
#define NF_DEVELOP_BASE_SOURCE_AUTO_STRIP_FALLBACK 6U
#define NF_DEVELOP_BASE_SOURCE_PRESET_MEASURED 7U
#define NF_DEVELOP_BASE_SOURCE_PRESET_FALLBACK 8U

#define NF_DEVELOP_SOURCE_FILM_SCAN 0U
#define NF_DEVELOP_SOURCE_RENDERED_DIGITAL 1U

#define NF_FILM_LOOK_ROUTE_INVALID 0U
#define NF_FILM_LOOK_ROUTE_IDENTITY 1U
#define NF_FILM_LOOK_ROUTE_FILM_SCAN_EMULATION 2U
#define NF_FILM_LOOK_ROUTE_DIGITAL_FILM_LOOK 3U

/* Stage identifiers mirror negaflow::pipeline::DevelopExportStage. A failure
   reports the stage together with that stage's own status name, so the caller
   never has to collapse two different refusals into one code. */
#define NF_DEVELOP_STAGE_NONE 0U
#define NF_DEVELOP_STAGE_REQUEST_VALIDATION 1U
#define NF_DEVELOP_STAGE_OBSERVE_SOURCE_BEFORE 2U
#define NF_DEVELOP_STAGE_DECODE 3U
#define NF_DEVELOP_STAGE_OBSERVE_SOURCE_AFTER 4U
#define NF_DEVELOP_STAGE_FILM_LOOK_WORKSPACE 5U
#define NF_DEVELOP_STAGE_DEVELOP 6U
#define NF_DEVELOP_STAGE_TONE_ADJUST 7U
#define NF_DEVELOP_STAGE_FILM_LOOK 8U
#define NF_DEVELOP_STAGE_OUTPUT 9U
#define NF_DEVELOP_STAGE_GRAIN_MEND 10U
#define NF_DEVELOP_STAGE_FILM_SCAN_DENOISE 11U
#define NF_DEVELOP_STAGE_LOCAL_DODGE_BURN 12U
#define NF_DEVELOP_STAGE_TEXTURE 13U
#define NF_DEVELOP_STAGE_BLACK_AND_WHITE 14U
#define NF_DEVELOP_STAGE_IMAGE_TRANSFORM 15U
#define NF_DEVELOP_STAGE_COLOR_MODEL 16U
#define NF_DEVELOP_STAGE_SCENE_CORRECTION 17U
#define NF_DEVELOP_STAGE_TARGET_GRADE 18U
#define NF_DEVELOP_STAGE_DEFECT_COMPONENT_REPAIR 19U
#define NF_DEVELOP_STAGE_DEFECT_CLONE_STAMP 20U
#define NF_DEVELOP_STAGE_DEFECT_BRUSH 21U
#define NF_DEVELOP_STAGE_OUTPUT_SHARPENING 22U

#define NF_OUTPUT_SHARPENING_SCREEN 0U
#define NF_OUTPUT_SHARPENING_MATTE_PAPER 1U
#define NF_OUTPUT_SHARPENING_GLOSSY_PAPER 2U

#define NF_TIFF_COMPRESSION_NONE 0U
#define NF_TIFF_COMPRESSION_LZW 1U
#define NF_TIFF_COMPRESSION_DEFLATE 2U

#define NF_DEVELOP_TARGET_MAIN 0U
#define NF_DEVELOP_TARGET_PRINT 1U
#define NF_DEVELOP_TARGET_NORITSU 2U
#define NF_DEVELOP_TARGET_SP3000 3U
#define NF_DEVELOP_TARGET_F135 4U
#define NF_DEVELOP_TARGET_HR 5U
#define NF_DEVELOP_TARGET_RESCUE 6U

#define NF_FILM_SCAN_DENOISE_COLOR_NEGATIVE 0U
#define NF_FILM_SCAN_DENOISE_COLOR_POSITIVE 1U
#define NF_FILM_SCAN_DENOISE_BLACK_AND_WHITE_NEGATIVE 2U
#define NF_FILM_SCAN_DENOISE_BLACK_AND_WHITE_POSITIVE 3U

#define NF_FAILURE_NAME_CAPACITY 64U
#define NF_POINT_CURVE_MAX_POINTS 64U

#ifdef __cplusplus
}
#endif
