import Foundation

enum AppLocalizedText: CaseIterable {
    case menuFile
    case menuEdit
    case menuLibrary
    case menuPhoto
    case menuDevelop
    case menuPrint
    case menuView
    case menuScanner
    case menuExport
    case menuWindow
    case menuHelp
    case commandAboutNegaflow
    case commandImportImages
    case commandRefreshLibrary
    case commandDeletePhoto
    case commandPick
    case commandReject
    case commandCopyDevelopSettings
    case commandPasteDevelopSettings
    case commandAutoTone
    case commandAutoWhiteBalance
    case commandResetAdjustments
    case commandShowHideSidebar
    case commandShowHideFilmstrip
    case commandShowHideInspector
    case commandToggleFullScreen
    case commandDetectScanners
    case commandToggleScannerSimulator
    case commandPreviewScan
    case commandScanFrame
    case commandExport
    case commandQuickExport
    case commandPrintExport
    case commandSettings
    case commandNegaflowHelp
    case commandKeyboardShortcuts
    case commandDiagnostics
    case commandWorkspaceOptions
    case aboutAnniversaryMessage
    case aboutVersionLabel
    case diagnosticsEmpty
    case diagnosticsRecentProblemsTitle
    case diagnosticsClearProblems
    case diagnosticsNoProblems
    case diagnosticsReportProblemsSection
    case diagnosticsReportEventsSection
    case diagnosticsReportLibrarySection
    case diagnosticsReportScannerSection
    case diagnosticsStatFrames
    case diagnosticsStatUnsaved
    case diagnosticsStatLifecycle
    case diagnosticsStatSaveError
    case diagnosticsValueYes
    case diagnosticsValueNo
    case diagnosticsGeneratedAt
    case diagnosticsScannerBackend
    case diagnosticsScannerPlugins
    case settingsGeneralTab
    case settingsInterfaceTab
    case settingsLanguageTab
    case settingsWorkflowTab
    case settingsExportTab
    case settingsShortcutsTab
    case settingsLegalTab
    case legalLicenseTitle
    case legalLicenseBody
    case legalTrademarkTitle
    case legalTrademarkBody
    case legalNamesTitle
    case legalNamesBody
    case legalProfilesTitle
    case legalProfilesBody
    case legalAffiliationTitle
    case legalAffiliationBody
    case settingsLanguagePicker
    case settingsAppearancePicker
    case settingsCanvasBackgroundPicker
    case settingsQuickExportFormat
    case settingsQuickExportDPI
    case settingsQuickExportFolder
    case settingsQuickExportSize
    case settingsSourceDPI
    case settingsExportVerification
    case settingsExportVerificationStandard
    case settingsExportVerificationStrict
    case settingsExportVerificationHelp
    case shortcutKeyField
    case shortcutReset
    case shortcutResetAll
    case shortcutInvalidOrConflict
    case shortcutClickToRecord
    case shortcutRecordingPrompt
    case shortcutModifierCommand
    case shortcutModifierShift
    case shortcutModifierOption
    case shortcutModifierControl
    case appearanceSystem
    case appearanceDark
    case appearanceLight
    case canvasBackgroundBlack
    case canvasBackgroundGray
    case canvasBackgroundWhite
    case exportFormatLabel
    case exportColorLabel
    case exportSoftProofLabel
    case exportProofLabel
    case exportDPILabel
    case exportSizeLabel
    case exportFullSize
    case exportLongEdgeSuffix
    case exportMainFlatMasterHelp
    case exportOriginalRawHelp
    case exportSidecarHelp
    case exportSourceLabel
    case exportFolderLabel
    case exportChangeFolder
    case libraryAmbiguousExportRecoveryTitle
    case libraryAmbiguousExportRecoveryMessage
    case libraryAmbiguousExportTransaction
    case libraryAmbiguousExportKeepFiles
    case libraryAmbiguousExportDeleteFiles
    case libraryAmbiguousExportDeleteConfirmationTitle
    case libraryAmbiguousExportDeleteConfirmationMessage
    case libraryAmbiguousExportRecoveryFailed
    case colorManagementSection
    case colorScannerInputReason
    case colorSoftProofOffReason
    case colorGamutUnavailableReason
    case colorSamplerUnavailableReason
    case colorUnavailable
    case colorUnassigned
    case colorSystemDisplayProfile
    case colorOff
    case scanPhaseIdle
    case scanPhaseConnecting
    case scanPhaseWarmingLamp
    case scanPhaseReady
    case scanPhasePreviewScanning
    case scanPhaseWaitingForFilmHolder
    case scanPhaseScanningRGB
    case scanPhaseScanningIR
    case scanPhaseProcessingNegative
    case scanPhaseRenderingLook
    case scanPhaseExporting
    case scanPhaseComplete
    case scanPhaseScannerBusy
    case scanPhaseDisconnected
    case scanPhaseError
    case scanPhaseBackendFallbackActive
    case sidebarLibrary
    case sidebarFiles
    case sidebarVersions
    case sidebarPresets
    case sidebarFilm
    case sidebarOutput
    case noFrame
    case noExportFrame
    case importSection
    case importImages
    case importHint
    case loadScanner
    case developDefaults
    case noLook
    case autoFilmMatch
    case emptyCanvasTitle
    case emptyCanvasDescription
    case exportSection
    case quickExportSection
    case printLayoutSection
    case printContentSection
    case printLayoutMode
    case printSingleImage
    case printContactSheet
    case printPicturePackage
    case printCustomPackage
    case printCyanotype
    case printGlassPlate
    case printGelatin
    case printPaperSize
    case printPaperPhotoRatio
    case printOrientation
    case printOrientationAutomatic
    case printOrientationPortrait
    case printOrientationLandscape
    case printMargin
    case printRuler
    case printRulerUnit
    case printRulerInches
    case printRulerCentimeters
    case printContactSheetBackground
    case printRows
    case printColumns
    case printHorizontalSpacing
    case printVerticalSpacing
    case printImageFit
    case printFit
    case printFill
    case printRotateToFit
    case printRepeatOnePhoto
    case printNormalizeOrientation
    case printPictureTemplate
    case printOneLargeTwoSmall
    case printTwoUp
    case printFourUp
    case printCaption
    case printCaptionFileName
    case printCaptionFrameNumber
    case printCaptionSequenceNumber
    case printCaptionRating
    case printCaptionCustomText
    case printCaptionFont
    case printCaptionAlignment
    case printCaptionAlignLeft
    case printCaptionAlignCenter
    case printCaptionAlignRight
    case printCustomCaption
    case printCaptionText
    case printAddCaption
    case printDeleteCaption
    case printCropMarks
    case printTemplates
    case printTemplateName
    case printTemplateUpdateFailed
    case printPackagePageLimit
    case printAddCell
    case printDuplicateCell
    case printDeleteCell
    case printCell
    case printSourcePhoto
    case printPage
    case printPreviousPage
    case printNextPage
    case printPositionX
    case printPositionY
    case printWidth
    case printHeight
    case printFilmSimulation
    case printPaperSimulation
    case printOutputProfile
    case printOutputSection
    case printOutputProcess
    case printOutputStandard
    case printOutputCPrint
    case printLab
    case printPaper
    case printSurface
    case printSurfaceGlossy
    case printSurfaceMatte
    case printSurfaceLustre
    case printSurfaceSilk
    case printProofProfile
    case printPreview
    case printPreviewProfileRequired
    case printAdvanced
    case printDeliveryColorSpace
    case printPerforationSimulation
}
