import Foundation

extension AppLocalization {
    static let germanTextTable: [AppLocalizedText: String] = [
            .menuFile: "Ablage",
            .menuEdit: "Bearbeiten",
            .menuLibrary: "Mediathek",
            .menuPhoto: "Foto",
            .menuDevelop: "Entwickeln",
            .menuPrint: "Abzug",
            .menuView: "Darstellung",
            .menuScanner: "Scanner",
            .menuExport: "Exportieren",
            .menuWindow: "Fenster",
            .menuHelp: "Hilfe",
            .commandAboutNegaflow: "Über negaflow",
            .commandImportImages: "Bilder importieren",
            .commandRefreshLibrary: "Mediathek aktualisieren",
            .commandDeletePhoto: "Aus negaflow entfernen",
            .commandPick: "Markieren",
            .commandReject: "Ablehnen",
            .commandCopyDevelopSettings: "Entwicklungseinstellungen kopieren",
            .commandPasteDevelopSettings: "Entwicklungseinstellungen einsetzen",
            .commandAutoTone: "Automatische Tonwerte",
            .commandAutoWhiteBalance: "Automatischer Weißabgleich",
            .commandResetAdjustments: "Alle Anpassungen zurücksetzen",
            .commandShowHideSidebar: "Seitenleiste ein-/ausblenden",
            .commandShowHideFilmstrip: "Filmstreifen ein-/ausblenden",
            .commandShowHideInspector: "Inspektor ein-/ausblenden",
            .commandToggleFullScreen: "Vollbildmodus aktivieren",
            .commandDetectScanners: "Scanner erneut suchen",
            .commandToggleScannerSimulator: "Scanner-Simulator",
            .commandPreviewScan: "Vorschauscan",
            .commandScanFrame: "Bild scannen",
            .commandExport: "Exportieren",
            .commandQuickExport: "Schnellexport",
            .commandPrintExport: "Abzug exportieren",
            .commandSettings: "Einstellungen",
            .commandNegaflowHelp: "Schnellstart",
            .commandKeyboardShortcuts: "Tastaturkurzbefehle",
            .commandDiagnostics: "Diagnose",
            .commandWorkspaceOptions: "Arbeitsbereichsoptionen",
            .aboutAnniversaryMessage: "Diesem Sommer gewidmet — zweihundert Jahre seit Niépces erster Fotografie.",
            .aboutVersionLabel: "Version",
            .diagnosticsEmpty: "Keine Diagnoseinformationen verfügbar",
            .diagnosticsRecentProblemsTitle: "Letzte Probleme",
            .diagnosticsClearProblems: "Löschen",
            .diagnosticsNoProblems: "Keine Probleme",
            .diagnosticsReportProblemsSection: "Letzte Probleme",
            .diagnosticsReportEventsSection: "Letzte Fehlerereignisse",
            .diagnosticsReportLibrarySection: "Bibliotheksstatus",
            .diagnosticsReportScannerSection: "Scanner",
            .diagnosticsStatFrames: "Bilder",
            .diagnosticsStatUnsaved: "Nicht gespeicherte Änderungen",
            .diagnosticsStatLifecycle: "Lebenszyklus",
            .diagnosticsStatSaveError: "Speicherfehler",
            .diagnosticsValueYes: "Ja",
            .diagnosticsValueNo: "Nein",
            .diagnosticsGeneratedAt: "Erstellt",
            .diagnosticsScannerBackend: "Backend",
            .diagnosticsScannerPlugins: "Plug-ins",
            .settingsGeneralTab: "Allgemein",
            .settingsInterfaceTab: "Oberfläche",
            .settingsLanguageTab: "Sprache",
            .settingsWorkflowTab: "Arbeitsablauf",
            .settingsExportTab: "Exportieren",
            .settingsShortcutsTab: "Kurzbefehle",
            .settingsLegalTab: "Rechtliches",
            .legalLicenseTitle: "Open-Source-Lizenz",
            .legalLicenseBody: "Der negaflow-Quellcode wird unter der Apache License 2.0 verteilt. Diese Lizenz gilt für den Code dieses Projekts; sie gewährt keine Rechte an Marken, Filmnamen, Scannernamen, Produktnamen, veröffentlichten Datenblättern, Referenzscans, Logos, Verpackungen oder proprietärer Scanner-Software Dritter.",
            .legalTrademarkTitle: "Markenverwendung",
            .legalTrademarkBody: "negaflow ist ein unabhängiges Open-Source-Werkzeug für Filmscans und Farbprofilierung. Film-, Scanner-, Minilab-, Prozess- und Zielnamen werden nur verwendet, um reale Filmtypen, Scannermodelle, Labor-Zielsysteme oder Profilfamilien zu identifizieren, die negaflow annähert, misst oder mit denen es interoperiert.",
            .legalNamesTitle: "Erwähnte Namen",
            .legalNamesBody: "Erwähnte Namen können Kodak, Kodak Professional, Portra, Ektar, Gold, UltraMax, Pro Image, ColorPlus, Vision3, Ektachrome, Fujifilm, Fuji, Fujicolor, Fujichrome, Superia, Frontier, SP-3000, Noritsu, HS-1800, CineStill, Lomography, Lomo, Harman, Phoenix, ORWO, Wolfen sowie zugehörige Film-, Scanner-, Minilab- oder Prozessnamen umfassen.",
            .legalProfilesTitle: "Profile und Zielsysteme",
            .legalProfilesBody: "Die mitgelieferten Film- und Scannerprofile sind Kompatibilitätsmetadaten sowie gemessene oder geschätzte Farbtransformationen für negaflow. Sie sind keine offiziellen Herstellerprofile, zertifizierten Farbtargets, Ersatz-Scanner-Firmware oder Kopien proprietärer Herstellersoftware.",
            .legalAffiliationTitle: "Keine Zugehörigkeit oder Empfehlung",
            .legalAffiliationBody: "negaflow ist nicht mit Eastman Kodak Company, Kodak Alaris, FUJIFILM Corporation, Noritsu Koki Co., Ltd., CineStill Film, Lomographische AG/Lomography, Harman Technology Ltd, ORWO/ORWO Net oder anderen Markeninhabern verbunden, von ihnen unterstützt, gesponsert, zertifiziert oder genehmigt. Alle Marken, Dienstleistungsmarken, Handelsnamen, Logos und Produktnamen sind Eigentum ihrer jeweiligen Inhaber.",
            .settingsLanguagePicker: "App-Sprache",
            .settingsAppearancePicker: "Erscheinungsbild",
            .settingsCanvasBackgroundPicker: "Arbeitsflächenhintergrund",
            .settingsQuickExportFormat: "Schnellexport-Format",
            .settingsQuickExportDPI: "Schnellexport-DPI",
            .settingsQuickExportFolder: "Schnellexport-Ordner",
            .settingsQuickExportSize: "Schnellexport-Größe",
            .settingsExportVerification: "Integritätsprüfung beim Export",
            .settingsExportVerificationStandard: "Standard",
            .settingsExportVerificationStrict: "Streng (langsamer)",
            .settingsExportVerificationHelp: "Standard berechnet je Datei einmal einen Hash und prüft danach über die Dateiidentität. Streng hasht an jedem Prüfpunkt alle Bytes erneut. Die Absturzwiederherstellung bietet in beiden Fällen dieselben Garantien.",
            .settingsSourceDPI: "Quell-DPI",
            .shortcutKeyField: "Taste",
            .shortcutReset: "Zurücksetzen",
            .shortcutResetAll: "Kurzbefehle zurücksetzen",
            .shortcutInvalidOrConflict: "Dieser Kurzbefehl ist nicht verfügbar oder bereits belegt.",
            .shortcutClickToRecord: "Klicken und Tasten drücken",
            .shortcutRecordingPrompt: "Kurzbefehl eingeben",
            .shortcutModifierCommand: "Befehl",
            .shortcutModifierShift: "Umschalt",
            .shortcutModifierOption: "Option",
            .shortcutModifierControl: "Steuerung",
            .appearanceSystem: "System",
            .appearanceDark: "Dunkel",
            .appearanceLight: "Hell",
            .canvasBackgroundBlack: "Schwarz",
            .canvasBackgroundGray: "Grau",
            .canvasBackgroundWhite: "Weiß",
            .exportFormatLabel: "Format",
            .exportColorLabel: "Farbe",
            .exportSoftProofLabel: "Softproof",
            .exportProofLabel: "Proof",
            .exportDPILabel: "DPI",
            .exportSizeLabel: "Größe",
            .exportFullSize: "Volle Größe",
            .exportLongEdgeSuffix: "px (lange Kante)",
            .exportMainFlatMasterHelp: "Speichert neben dem bearbeiteten Export ein unbearbeitetes MAIN-Master als -main-flat.",
            .exportOriginalRawHelp: "Speichert neben dem bearbeiteten Export das ursprüngliche Scan-TIFF als -original.",
            .exportSidecarHelp: "Speichert Entwicklungseinstellungen als <name>.negaflow.json und <name>.xmp.",
            .exportSourceLabel: "Quelle",
            .exportFolderLabel: "Ordner",
            .exportChangeFolder: "Ändern",
            .libraryAmbiguousExportRecoveryTitle: "Exportwiederherstellung erforderlich",
            .libraryAmbiguousExportRecoveryMessage: "negaflow konnte diesen Export nicht sicher abschließen. Die aktuellen Dateien zu behalten und fortzufahren ist die sicherste Wahl.",
            .libraryAmbiguousExportTransaction: "Transaktion",
            .libraryAmbiguousExportKeepFiles: "Dateien behalten und fortfahren",
            .libraryAmbiguousExportDeleteFiles: "Erstellte Dateien löschen",
            .libraryAmbiguousExportDeleteConfirmationTitle: "Diese Exportdateien löschen?",
            .libraryAmbiguousExportDeleteConfirmationMessage: "Es werden nur Dateien gelöscht, deren Eigentümerschaft und Inhalt noch mit diesem Export übereinstimmen. Dies kann nicht rückgängig gemacht werden.",
            .libraryAmbiguousExportRecoveryFailed: "Exportwiederherstellung konnte nicht abgeschlossen werden",
            .colorManagementSection: "Farbmanagement",
            .colorScannerInputReason: "Kein Scanner-Emulations-Look ausgewählt.",
            .colorSoftProofOffReason: "Softproof ist deaktiviert.",
            .colorGamutUnavailableReason: "Das gewählte Ausgabeprofil unterstützt keine ColorSync-Farbumfangprüfung.",
            .colorSamplerUnavailableReason: "Der Pixel-Sampler ist in diesem Build nicht verfügbar.",
            .colorUnavailable: "Nicht verfügbar",
            .colorUnassigned: "Nicht zugewiesen",
            .colorSystemDisplayProfile: "System ColorSync Anzeigeprofil",
            .colorOff: "Aus",
            .scanPhaseIdle: "Inaktiv",
            .scanPhaseConnecting: "Verbindet",
            .scanPhaseWarmingLamp: "Lampe wärmt auf",
            .scanPhaseReady: "Scanbereit",
            .scanPhasePreviewScanning: "Vorschauscan",
            .scanPhaseWaitingForFilmHolder: "Wartet auf Filmhalter",
            .scanPhaseScanningRGB: "Scan läuft",
            .scanPhaseScanningIR: "IR-Scan",
            .scanPhaseProcessingNegative: "Negativ wird verarbeitet",
            .scanPhaseRenderingLook: "Entwicklung wird gerendert",
            .scanPhaseExporting: "Exportiert",
            .scanPhaseComplete: "Fertig",
            .scanPhaseScannerBusy: "Scanner belegt",
            .scanPhaseDisconnected: "Getrennt",
            .scanPhaseError: "Fehler",
            .scanPhaseBackendFallbackActive: "Fallback-Backend",
            .sidebarLibrary: "Mediathek",
            .sidebarFiles: "Dateien",
            .sidebarVersions: "Versionen",
            .sidebarPresets: "Vorgaben",
            .sidebarFilm: "Film",
            .sidebarOutput: "Ausgabe",
            .noFrame: "Kein Bild",
            .noExportFrame: "Kein Bild zum Exportieren",
            .importSection: "Importieren",
            .importImages: "Bilder importieren",
            .importHint: "Wählen Sie mehrere Dateien oder ziehen Sie Bilder in das Fenster.",
            .loadScanner: "Scanner laden",
            .developDefaults: "Entwicklung",
            .noLook: "Keine",
            .autoFilmMatch: "Auto (Filmabgleich)",
            .emptyCanvasTitle: "Bilder importieren",
            .emptyCanvasDescription: "Ziehen Sie Dateien in das Fenster oder verwenden Sie Importieren in der Mediathek.\nLaden Sie einen Scanner aus der Mediathek, um Film zu scannen.",
            .exportSection: "Exportieren",
            .quickExportSection: "Schnellexport",
            .printLayoutSection: "Abzugslayout",
            .printContentSection: "Inhalt",
            .printLayoutMode: "Layout",
            .printSingleImage: "Einzelbild",
            .printContactSheet: "Kontaktbogen",
            .printPicturePackage: "Bildpaket",
            .printCustomPackage: "Benutzerpaket",
            .printCyanotype: "Cyanotypie",
            .printGlassPlate: "Glasplatte",
            .printGelatin: "Silbergelatine",
            .printPaperSize: "Papierformat",
            .printPaperPhotoRatio: "Fotoformat",
            .printOrientation: "Ausrichtung",
            .printOrientationAutomatic: "Automatisch",
            .printOrientationPortrait: "Hochformat",
            .printOrientationLandscape: "Querformat",
            .printMargin: "Rand",
            .printContactSheetBackground: "Bogenfarbe",
            .printRows: "Zeilen",
            .printColumns: "Spalten",
            .printHorizontalSpacing: "Horizontaler Abstand",
            .printVerticalSpacing: "Vertikaler Abstand",
            .printImageFit: "Bildanpassung",
            .printFit: "Einpassen",
            .printFill: "Zelle füllen",
            .printRotateToFit: "Zum Einpassen 90° drehen",
            .printRepeatOnePhoto: "Ein Foto wiederholen",
            .printNormalizeOrientation: "Ausrichtung angleichen",
            .printPictureTemplate: "Paketlayout",
            .printOneLargeTwoSmall: "1 groß + 2 klein",
            .printTwoUp: "2-fach",
            .printFourUp: "4-fach",
            .printCaption: "Beschriftung",
            .printCaptionFileName: "Dateiname",
            .printCaptionFrameNumber: "Bildnummer",
            .printCaptionSequenceNumber: "Reihenfolgennummer",
            .printCaptionRating: "Bewertung",
            .printCaptionCustomText: "Benutzerdefinierter Text",
            .printCaptionFont: "Beschriftungsschrift",
            .printCaptionAlignment: "Beschriftungsausrichtung",
            .printCaptionAlignLeft: "Links",
            .printCaptionAlignCenter: "Mitte",
            .printCaptionAlignRight: "Rechts",
            .printCustomCaption: "Text",
            .printCaptionText: "Beschriftungstext",
            .printAddCaption: "Text hinzufügen",
            .printDeleteCaption: "Text löschen",
            .printCropMarks: "Schnittmarken",
            .printTemplates: "Layoutvorlagen",
            .printTemplateName: "Vorlagenname",
            .printTemplateUpdateFailed: "Vorlagenänderungen konnten nicht gespeichert werden.",
            .printPackagePageLimit: "Ein Druckpaket kann bis zu 32 Seiten enthalten.",
            .printAddCell: "Zelle hinzufügen",
            .printDuplicateCell: "Zelle duplizieren",
            .printDeleteCell: "Zelle löschen",
            .printCell: "Zelle",
            .printSourcePhoto: "Foto",
            .printPage: "Seite",
            .printPreviousPage: "Vorherige Seite",
            .printNextPage: "Nächste Seite",
            .printPositionX: "Horizontale Position",
            .printPositionY: "Vertikale Position",
            .printWidth: "Breite",
            .printHeight: "Höhe",
            .printFilmSimulation: "Filmabzug-Simulation",
            .printPaperSimulation: "Fotopapier-Simulation",
            .printOutputProfile: "Drucker-Ausgabeprofil",
            .printOutputSection: "Ausgabe",
            .printOutputProcess: "Ausgabeverfahren",
            .printOutputStandard: "Standardausgabe",
            .printOutputCPrint: "C-Print",
            .printLab: "Labor",
            .printPaper: "Papier",
            .printSurface: "Oberfläche",
            .printSurfaceGlossy: "Glänzend",
            .printSurfaceMatte: "Matt",
            .printSurfaceLustre: "Seidenglanz",
            .printSurfaceSilk: "Seide",
            .printProofProfile: "Softproof-Profil",
            .printPreview: "Abzugsvorschau",
            .printPreviewProfileRequired:
                "Wählen Sie das RGB-ICC-Profil des Labors für die Abzugsvorschau.",
            .printAdvanced: "Erweitert",
            .printDeliveryColorSpace: "Auslieferungsfarbraum",
            .printPerforationSimulation: "Filmperforations-Simulation",
    ]
}
