import Foundation

extension AppLocalization {
    static let koreanTextTable: [AppLocalizedText: String] = [
            .menuFile: "파일",
            .menuEdit: "편집",
            .menuLibrary: "라이브러리",
            .menuPhoto: "사진",
            .menuDevelop: "현상",
            .menuPrint: "인화",
            .menuView: "보기",
            .menuScanner: "스캐너",
            .menuExport: "내보내기",
            .menuWindow: "윈도우",
            .menuHelp: "도움말",
            .commandImportImages: "이미지 가져오기",
            .commandRefreshLibrary: "라이브러리 새로고침",
            .commandDeletePhoto: "negaflow에서 제거",
            .commandPick: "선택",
            .commandReject: "제외",
            .commandCopyDevelopSettings: "현상 설정 복사",
            .commandPasteDevelopSettings: "현상 설정 붙여넣기",
            .commandAutoTone: "자동 톤",
            .commandAutoWhiteBalance: "자동 화이트 밸런스",
            .commandResetAdjustments: "모든 보정 초기화",
            .commandShowHideSidebar: "사이드바 보기/숨기기",
            .commandShowHideFilmstrip: "필름스트립 보기/숨기기",
            .commandShowHideInspector: "인스펙터 보기/숨기기",
            .commandToggleFullScreen: "전체 화면 시작",
            .commandDetectScanners: "스캐너 다시 찾기",
            .commandToggleScannerSimulator: "스캐너 시뮬레이터",
            .commandPreviewScan: "프리뷰 스캔",
            .commandScanFrame: "사진 스캔",
            .commandExport: "내보내기",
            .commandQuickExport: "빠른 내보내기",
            .commandSettings: "설정",
            .commandNegaflowHelp: "빠른 시작",
            .commandKeyboardShortcuts: "단축키",
            .commandDiagnostics: "진단",
            .commandWorkspaceOptions: "작업 옵션",
            .diagnosticsEmpty: "진단 정보 없음",
            .diagnosticsRecentProblemsTitle: "최근 문제",
            .diagnosticsClearProblems: "지우기",
            .diagnosticsNoProblems: "문제 없음",
            .diagnosticsReportProblemsSection: "최근 문제",
            .diagnosticsReportEventsSection: "최근 실패 이벤트",
            .diagnosticsReportLibrarySection: "라이브러리 상태",
            .diagnosticsReportScannerSection: "스캐너",
            .diagnosticsStatFrames: "프레임",
            .diagnosticsStatUnsaved: "미저장 변경",
            .diagnosticsStatLifecycle: "수명 주기",
            .diagnosticsStatSaveError: "저장 오류",
            .diagnosticsValueYes: "예",
            .diagnosticsValueNo: "아니오",
            .diagnosticsGeneratedAt: "생성 시각",
            .diagnosticsScannerBackend: "백엔드",
            .diagnosticsScannerPlugins: "플러그인",
            .settingsGeneralTab: "일반",
            .settingsInterfaceTab: "인터페이스",
            .settingsLanguageTab: "언어",
            .settingsWorkflowTab: "워크플로우",
            .settingsExportTab: "내보내기",
            .settingsShortcutsTab: "단축키",
            .settingsLegalTab: "법적 고지",
            .legalLicenseTitle: "오픈소스 라이선스",
            .legalLicenseBody: "negaflow의 소스 코드는 Apache License 2.0에 따라 배포됩니다. 이 라이선스는 본 프로젝트의 코드에 적용되며, 제3자의 상표, 필름명, 스캐너명, 제품명, 공개 데이터시트, 참조 스캔, 로고, 패키지 디자인, 제조사 전용 스캐너 소프트웨어에 대한 권리를 부여하지 않습니다.",
            .legalTrademarkTitle: "상표 사용",
            .legalTrademarkBody: "negaflow는 독립적으로 개발된 오픈소스 필름 스캔 및 컬러 프로파일링 도구입니다. 필름, 스캐너, 미니랩, 현상 공정, 타겟 명칭은 negaflow가 근사하거나 측정하거나 연동하려는 실제 필름 스톡, 스캐너 모델, 랩 타겟 시스템 또는 프로파일 계열을 식별하기 위해서만 사용됩니다.",
            .legalNamesTitle: "언급되는 명칭",
            .legalNamesBody: "언급되는 명칭에는 Kodak, Kodak Professional, Portra, Ektar, Gold, UltraMax, Pro Image, ColorPlus, Vision3, Ektachrome, Fujifilm, Fuji, Fujicolor, Fujichrome, Superia, Frontier, SP-3000, Noritsu, HS-1800, CineStill, Lomography, Lomo, Harman, Phoenix, ORWO, Wolfen 및 관련 필름, 스캐너, 미니랩, 공정명이 포함될 수 있습니다.",
            .legalProfilesTitle: "프로파일과 타겟 시스템",
            .legalProfilesBody: "번들된 필름 및 스캐너 프로파일은 negaflow를 위한 호환성 메타데이터이자 실측 또는 추정 기반 색 변환입니다. 이는 공식 제조사 프로파일, 인증된 컬러 타겟, 대체 스캐너 펌웨어 또는 제조사의 전용 처리 소프트웨어 사본이 아닙니다.",
            .legalAffiliationTitle: "제휴 및 승인 관계 없음",
            .legalAffiliationBody: "negaflow는 Eastman Kodak Company, Kodak Alaris, FUJIFILM Corporation, Noritsu Koki Co., Ltd., CineStill Film, Lomographische AG/Lomography, Harman Technology Ltd, ORWO/ORWO Net 또는 기타 상표권자와 제휴, 후원, 보증, 인증, 승인 관계가 없습니다. 모든 상표, 서비스표, 상호, 로고, 제품명은 각 소유자의 자산입니다.",
            .settingsLanguagePicker: "앱 언어",
            .settingsAppearancePicker: "화면 모드",
            .settingsCanvasBackgroundPicker: "캔버스 배경",
            .settingsQuickExportFormat: "빠른 내보내기 형식",
            .settingsQuickExportDPI: "빠른 내보내기 DPI",
            .settingsQuickExportFolder: "빠른 내보내기 폴더",
            .settingsQuickExportSize: "빠른 내보내기 크기",
            .settingsExportVerification: "내보내기 무결성 검사",
            .settingsExportVerificationStandard: "표준",
            .settingsExportVerificationStrict: "엄격(느림)",
            .settingsExportVerificationHelp: "표준은 파일마다 해시를 한 번만 계산하고 이후에는 파일 식별자로 재확인합니다. 엄격은 확인 지점마다 전체 바이트를 다시 해시합니다. 크래시 복구 보증은 두 경우 모두 같습니다.",
            .settingsSourceDPI: "원본 DPI",
            .shortcutKeyField: "키",
            .shortcutReset: "초기화",
            .shortcutResetAll: "모든 단축키 초기화",
            .shortcutInvalidOrConflict: "사용할 수 없거나 이미 사용 중인 단축키입니다.",
            .shortcutClickToRecord: "클릭한 다음 키를 누르세요",
            .shortcutRecordingPrompt: "단축키 입력",
            .shortcutModifierCommand: "Command",
            .shortcutModifierShift: "Shift",
            .shortcutModifierOption: "Option",
            .shortcutModifierControl: "Control",
            .appearanceSystem: "시스템",
            .appearanceDark: "어둡게",
            .appearanceLight: "밝게",
            .canvasBackgroundBlack: "검정",
            .canvasBackgroundGray: "회색",
            .canvasBackgroundWhite: "흰색",
            .exportFormatLabel: "형식",
            .exportColorLabel: "색상",
            .exportSoftProofLabel: "소프트 프루프",
            .exportProofLabel: "프루프",
            .exportDPILabel: "DPI",
            .exportSizeLabel: "크기",
            .exportFullSize: "전체",
            .exportLongEdgeSuffix: "px (긴 변)",
            .exportMainFlatMasterHelp: "보정본 옆에 MAIN 무보정본을 -main-flat 파일로 함께 저장합니다.",
            .exportOriginalRawHelp: "보정본 옆에 원본 스캔 TIFF를 -original 파일로 함께 저장합니다.",
            .exportSidecarHelp: "현상 파라미터를 <이름>.negaflow.json 과 <이름>.xmp 로 저장합니다.",
            .exportSourceLabel: "소스",
            .exportFolderLabel: "폴더",
            .exportChangeFolder: "변경",
            .libraryAmbiguousExportRecoveryTitle: "내보내기 복구 필요",
            .libraryAmbiguousExportRecoveryMessage: "내보내기를 안전하게 종료했는지 확인할 수 없습니다. 현재 파일을 유지하고 계속하는 것이 가장 안전합니다.",
            .libraryAmbiguousExportTransaction: "처리 ID",
            .libraryAmbiguousExportKeepFiles: "파일 유지 후 계속",
            .libraryAmbiguousExportDeleteFiles: "생성한 파일 삭제",
            .libraryAmbiguousExportDeleteConfirmationTitle: "이 내보내기 파일을 삭제하시겠습니까?",
            .libraryAmbiguousExportDeleteConfirmationMessage: "이 내보내기의 소유권과 내용이 모두 일치하는 파일만 삭제합니다. 이 작업은 취소할 수 없습니다.",
            .libraryAmbiguousExportRecoveryFailed: "내보내기 복구를 완료할 수 없습니다",
            .colorManagementSection: "색상 관리",
            .colorScannerInputReason: "선택된 스캐너 에뮬레이션 룩이 없습니다.",
            .colorSoftProofOffReason: "소프트 프루프가 꺼져 있습니다.",
            .colorGamutUnavailableReason: "선택한 출력 프로파일은 ColorSync 색역 검사를 지원하지 않습니다.",
            .colorSamplerUnavailableReason: "현재 빌드에는 픽셀 샘플러와 읽기 기능이 구현되어 있지 않습니다.",
            .colorUnavailable: "사용 불가",
            .colorUnassigned: "미지정",
            .colorSystemDisplayProfile: "시스템 ColorSync 디스플레이 프로파일",
            .colorOff: "끔",
            .scanPhaseIdle: "대기",
            .scanPhaseConnecting: "연결 중",
            .scanPhaseWarmingLamp: "램프 예열",
            .scanPhaseReady: "준비됨",
            .scanPhasePreviewScanning: "프리뷰 스캔",
            .scanPhaseWaitingForFilmHolder: "필름 홀더 대기",
            .scanPhaseScanningRGB: "스캔 중",
            .scanPhaseScanningIR: "IR 스캔",
            .scanPhaseProcessingNegative: "네거티브 처리",
            .scanPhaseRenderingLook: "현상 렌더링",
            .scanPhaseExporting: "내보내는 중",
            .scanPhaseComplete: "완료",
            .scanPhaseScannerBusy: "스캐너 사용 중",
            .scanPhaseDisconnected: "연결 끊김",
            .scanPhaseError: "오류",
            .scanPhaseBackendFallbackActive: "대체 백엔드",
            .sidebarLibrary: "라이브러리",
            .sidebarFiles: "파일",
            .sidebarVersions: "버전",
            .sidebarPresets: "프리셋",
            .sidebarFilm: "필름",
            .sidebarOutput: "출력",
            .noFrame: "사진 없음",
            .noExportFrame: "내보낼 사진 없음",
            .importSection: "가져오기",
            .importImages: "이미지 가져오기",
            .importHint: "여러 파일을 선택하거나 이미지를 창으로 드래그하세요.",
            .loadScanner: "스캐너 불러오기",
            .developDefaults: "현상",
            .noLook: "없음",
            .autoFilmMatch: "자동 (필름 매칭)",
            .emptyCanvasTitle: "이미지를 가져오세요",
            .emptyCanvasDescription: "파일을 창에 드래그앤드롭하거나 좌측 라이브러리의 가져오기 항목을 사용하세요.\n스캐너를 쓰려면 좌측에서 스캐너를 불러오세요.",
            .exportSection: "내보내기",
            .quickExportSection: "빠른 내보내기",
            .printLayoutSection: "인화 레이아웃",
            .printLayoutMode: "레이아웃",
            .printSingleImage: "단일 이미지",
            .printContactSheet: "콘택트 시트",
            .printPicturePackage: "사진 패키지",
            .printCustomPackage: "사용자 패키지",
            .printPaperSize: "용지 크기",
            .printOrientation: "방향",
            .printOrientationAutomatic: "자동",
            .printOrientationPortrait: "세로",
            .printOrientationLandscape: "가로",
            .printMargin: "여백",
            .printRows: "행",
            .printColumns: "열",
            .printHorizontalSpacing: "가로 간격",
            .printVerticalSpacing: "세로 간격",
            .printImageFit: "이미지 맞춤",
            .printFit: "전체 맞춤",
            .printFill: "셀 채우기",
            .printRotateToFit: "90° 회전 맞춤",
            .printRepeatOnePhoto: "사진 한 장씩 반복",
            .printPictureTemplate: "패키지 구성",
            .printOneLargeTwoSmall: "대형 1 + 소형 2",
            .printTwoUp: "2장",
            .printFourUp: "4장",
            .printCaption: "캡션",
            .printCaptionFileName: "파일명",
            .printCaptionFrameNumber: "프레임 번호",
            .printCaptionRating: "평점",
            .printCropMarks: "재단 표시",
            .printTemplates: "레이아웃 템플릿",
            .printTemplateName: "템플릿 이름",
            .printTemplateUpdateFailed: "템플릿 변경사항을 저장할 수 없습니다.",
            .printPackagePageLimit: "인화 패키지는 최대 32페이지까지 출력할 수 있습니다.",
            .printAddCell: "셀 추가",
            .printDuplicateCell: "셀 복제",
            .printDeleteCell: "셀 삭제",
            .printCell: "셀",
            .printSourcePhoto: "사진",
            .printPage: "페이지",
            .printPreviousPage: "이전 페이지",
            .printNextPage: "다음 페이지",
            .printPositionX: "가로 위치",
            .printPositionY: "세로 위치",
            .printWidth: "너비",
            .printHeight: "높이",
            .printFilmSimulation: "필름 인화 시뮬레이션",
            .printPaperSimulation: "인화 용지 시뮬레이션",
            .printOutputProfile: "프린터 출력 프로파일",
            .printPerforationSimulation: "필름 퍼포레이션 시뮬레이션",
    ]
}
