import Foundation

extension AppLocalization {
    static let simplifiedChineseTextTable: [AppLocalizedText: String] = [
            .menuFile: "文件",
            .menuEdit: "编辑",
            .menuLibrary: "图库",
            .menuPhoto: "照片",
            .menuDevelop: "显影",
            .menuPrint: "印相",
            .menuView: "视图",
            .menuScanner: "扫描仪",
            .menuExport: "导出",
            .menuWindow: "窗口",
            .menuHelp: "帮助",
            .commandImportImages: "导入图像",
            .commandRefreshLibrary: "刷新图库",
            .commandDeletePhoto: "从 negaflow 中移除",
            .commandPick: "留用",
            .commandReject: "排除",
            .commandCopyDevelopSettings: "复制显影设置",
            .commandPasteDevelopSettings: "粘贴显影设置",
            .commandAutoTone: "自动色调",
            .commandAutoWhiteBalance: "自动白平衡",
            .commandResetAdjustments: "重置所有调整",
            .commandShowHideSidebar: "显示/隐藏边栏",
            .commandShowHideFilmstrip: "显示/隐藏胶片栏",
            .commandShowHideInspector: "显示/隐藏检查器",
            .commandToggleFullScreen: "进入全屏幕",
            .commandDetectScanners: "重新检测扫描仪",
            .commandToggleScannerSimulator: "扫描仪模拟器",
            .commandPreviewScan: "预览扫描",
            .commandScanFrame: "扫描照片",
            .commandExport: "导出",
            .commandQuickExport: "快速导出",
            .commandSettings: "设置",
            .commandNegaflowHelp: "快速入门",
            .commandKeyboardShortcuts: "键盘快捷键",
            .commandDiagnostics: "诊断",
            .commandWorkspaceOptions: "工作区选项",
            .diagnosticsEmpty: "无诊断信息",
            .diagnosticsRecentProblemsTitle: "最近的问题",
            .diagnosticsClearProblems: "清除",
            .diagnosticsNoProblems: "无问题",
            .diagnosticsReportProblemsSection: "最近的问题",
            .diagnosticsReportEventsSection: "最近的失败事件",
            .diagnosticsReportLibrarySection: "库状态",
            .diagnosticsReportScannerSection: "扫描仪",
            .diagnosticsStatFrames: "帧",
            .diagnosticsStatUnsaved: "未保存的更改",
            .diagnosticsStatLifecycle: "生命周期",
            .diagnosticsStatSaveError: "保存错误",
            .diagnosticsValueYes: "是",
            .diagnosticsValueNo: "否",
            .diagnosticsGeneratedAt: "生成时间",
            .diagnosticsScannerBackend: "后端",
            .diagnosticsScannerPlugins: "插件",
            .settingsGeneralTab: "通用",
            .settingsInterfaceTab: "界面",
            .settingsLanguageTab: "语言",
            .settingsWorkflowTab: "工作流",
            .settingsExportTab: "导出",
            .settingsShortcutsTab: "快捷键",
            .settingsLegalTab: "法律声明",
            .legalLicenseTitle: "开源许可证",
            .legalLicenseBody: "negaflow 源代码按照 Apache License 2.0 分发。该许可证仅覆盖本项目代码；并不授予任何第三方商标、胶片名称、扫描仪名称、产品名称、公开数据表、参考扫描、标志、包装或厂商专有扫描软件的权利。",
            .legalTrademarkTitle: "商标使用",
            .legalTrademarkBody: "negaflow 是独立开发的开源胶片扫描与色彩配置工具。胶片、扫描仪、迷你冲印系统、工艺和目标名称仅用于识别 negaflow 近似、测量或互操作的实体胶片、扫描仪型号、实验室目标系统或配置文件系列。",
            .legalNamesTitle: "引用的名称",
            .legalNamesBody: "引用的名称可能包括 Kodak、Kodak Professional、Portra、Ektar、Gold、UltraMax、Pro Image、ColorPlus、Vision3、Ektachrome、Fujifilm、Fuji、Fujicolor、Fujichrome、Superia、Frontier、SP-3000、Noritsu、HS-1800、CineStill、Lomography、Lomo、Harman、Phoenix、ORWO、Wolfen，以及相关胶片、扫描仪、迷你冲印系统或工艺名称。",
            .legalProfilesTitle: "配置文件与目标系统",
            .legalProfilesBody: "随附的胶片和扫描仪配置文件是供 negaflow 使用的兼容性元数据，以及基于实测或估算的色彩转换。它们不是官方厂商配置文件、认证色彩目标、替代扫描仪固件，也不是任何厂商专有处理软件的副本。",
            .legalAffiliationTitle: "无关联或背书",
            .legalAffiliationBody: "negaflow 未与 Eastman Kodak Company、Kodak Alaris、FUJIFILM Corporation、Noritsu Koki Co., Ltd.、CineStill Film、Lomographische AG/Lomography、Harman Technology Ltd、ORWO/ORWO Net 或任何其他商标所有者建立关联、赞助、担保、认证或批准关系。所有商标、服务标志、商号、标志和产品名称均归其各自所有者所有。",
            .settingsLanguagePicker: "应用语言",
            .settingsAppearancePicker: "外观",
            .settingsCanvasBackgroundPicker: "画布背景",
            .settingsQuickExportFormat: "快速导出格式",
            .settingsQuickExportDPI: "快速导出 DPI",
            .settingsQuickExportFolder: "快速导出文件夹",
            .settingsSourceDPI: "源 DPI",
            .shortcutKeyField: "按键",
            .shortcutReset: "重置",
            .shortcutResetAll: "重置所有快捷键",
            .shortcutInvalidOrConflict: "快捷键不可用或已被使用。",
            .shortcutClickToRecord: "点击后按键",
            .shortcutRecordingPrompt: "输入快捷键",
            .shortcutModifierCommand: "Command",
            .shortcutModifierShift: "Shift",
            .shortcutModifierOption: "Option",
            .shortcutModifierControl: "Control",
            .appearanceSystem: "系统",
            .appearanceDark: "深色",
            .appearanceLight: "浅色",
            .canvasBackgroundBlack: "黑色",
            .canvasBackgroundGray: "灰色",
            .canvasBackgroundWhite: "白色",
            .exportFormatLabel: "格式",
            .exportColorLabel: "颜色",
            .exportSoftProofLabel: "软打样",
            .exportProofLabel: "打样",
            .exportDPILabel: "DPI",
            .exportSizeLabel: "大小",
            .exportFullSize: "完整",
            .exportLongEdgeSuffix: "px（长边）",
            .exportMainFlatMasterHelp: "在调整后的导出旁保存未调整的 MAIN 母版，文件名后缀为 -main-flat。",
            .exportOriginalRawHelp: "在调整后的导出旁保存原始扫描 TIFF，文件名后缀为 -original。",
            .exportSidecarHelp: "将显影参数保存为 <name>.negaflow.json 和 <name>.xmp。",
            .exportSourceLabel: "来源",
            .exportFolderLabel: "文件夹",
            .exportChangeFolder: "更改",
            .libraryAmbiguousExportRecoveryTitle: "需要恢复导出",
            .libraryAmbiguousExportRecoveryMessage: "无法确认此导出是否已安全完成。保留当前文件并继续是最安全的选择。",
            .libraryAmbiguousExportTransaction: "处理 ID",
            .libraryAmbiguousExportKeepFiles: "保留文件并继续",
            .libraryAmbiguousExportDeleteFiles: "删除已创建的文件",
            .libraryAmbiguousExportDeleteConfirmationTitle: "要删除这些导出文件吗？",
            .libraryAmbiguousExportDeleteConfirmationMessage: "只会删除所有权和内容均与此次导出相符的文件。此操作无法撤销。",
            .libraryAmbiguousExportRecoveryFailed: "无法完成导出恢复",
            .colorManagementSection: "色彩管理",
            .colorScannerInputReason: "未选择扫描仪模拟外观。",
            .colorSoftProofOffReason: "软打样已关闭。",
            .colorGamutUnavailableReason: "所选输出配置文件不支持 ColorSync 色域检查。",
            .colorSamplerUnavailableReason: "此版本尚未提供像素取样/读数功能。",
            .colorUnavailable: "不可用",
            .colorUnassigned: "未指定",
            .colorSystemDisplayProfile: "系统 ColorSync 显示配置文件",
            .colorOff: "关闭",
            .scanPhaseIdle: "空闲",
            .scanPhaseConnecting: "正在连接",
            .scanPhaseWarmingLamp: "灯管预热",
            .scanPhaseReady: "就绪",
            .scanPhasePreviewScanning: "预览扫描",
            .scanPhaseWaitingForFilmHolder: "等待胶片夹",
            .scanPhaseScanningRGB: "扫描中",
            .scanPhaseScanningIR: "IR 扫描",
            .scanPhaseProcessingNegative: "正在处理负片",
            .scanPhaseRenderingLook: "正在渲染显影",
            .scanPhaseExporting: "正在导出",
            .scanPhaseComplete: "完成",
            .scanPhaseScannerBusy: "扫描仪忙",
            .scanPhaseDisconnected: "已断开",
            .scanPhaseError: "错误",
            .scanPhaseBackendFallbackActive: "备用后端",
            .sidebarLibrary: "图库",
            .sidebarFiles: "文件",
            .sidebarVersions: "版本",
            .sidebarPresets: "预设",
            .sidebarFilm: "胶片",
            .sidebarOutput: "输出",
            .noFrame: "无照片",
            .noExportFrame: "没有可导出的照片",
            .importSection: "导入",
            .importImages: "导入图像",
            .importHint: "选择多个文件，或将图像拖入窗口。",
            .loadScanner: "加载扫描仪",
            .developDefaults: "显影",
            .noLook: "无",
            .autoFilmMatch: "自动（匹配胶片）",
            .emptyCanvasTitle: "导入图像",
            .emptyCanvasDescription: "将文件拖入窗口，或使用图库中的导入。\n要扫描胶片，请从图库加载扫描仪。",
            .exportSection: "导出",
            .quickExportSection: "快速导出",
            .printLayoutSection: "印相布局",
            .printLayoutMode: "布局",
            .printSingleImage: "单张图像",
            .printContactSheet: "接触印相表",
            .printPicturePackage: "照片套版",
            .printCustomPackage: "自定义套版",
            .printPaperSize: "纸张尺寸",
            .printOrientation: "方向",
            .printOrientationAutomatic: "自动",
            .printOrientationPortrait: "纵向",
            .printOrientationLandscape: "横向",
            .printMargin: "边距",
            .printRows: "行",
            .printColumns: "列",
            .printHorizontalSpacing: "水平间距",
            .printVerticalSpacing: "垂直间距",
            .printImageFit: "图像适配",
            .printFit: "完整适配",
            .printFill: "填满单元格",
            .printRotateToFit: "旋转 90° 适配",
            .printRepeatOnePhoto: "重复单张照片",
            .printPictureTemplate: "套版布局",
            .printOneLargeTwoSmall: "1 大 + 2 小",
            .printTwoUp: "2 联",
            .printFourUp: "4 联",
            .printCaption: "说明文字",
            .printCaptionFileName: "文件名",
            .printCaptionFrameNumber: "画面编号",
            .printCaptionRating: "星级",
            .printCropMarks: "裁切标记",
            .printTemplates: "布局模板",
            .printTemplateName: "模板名称",
            .printTemplateUpdateFailed: "无法保存模板更改。",
            .printPackagePageLimit: "打印套装最多可包含32页。",
            .printAddCell: "添加单元格",
            .printDuplicateCell: "复制单元格",
            .printDeleteCell: "删除单元格",
            .printCell: "单元格",
            .printSourcePhoto: "照片",
            .printPage: "页面",
            .printPreviousPage: "上一页",
            .printNextPage: "下一页",
            .printPositionX: "水平位置",
            .printPositionY: "垂直位置",
            .printWidth: "宽度",
            .printHeight: "高度",
            .printFilmSimulation: "胶片印相模拟",
            .printPaperSimulation: "相纸模拟",
            .printOutputProfile: "打印机输出配置文件",
            .printPerforationSimulation: "胶片齿孔模拟",
    ]
}
