import Foundation

extension AppLocalization {
    static let frenchTextTable: [AppLocalizedText: String] = [
            .menuFile: "Fichier",
            .menuEdit: "Édition",
            .menuLibrary: "Bibliothèque",
            .menuPhoto: "Photo",
            .menuDevelop: "Développement",
            .menuPrint: "Tirage",
            .menuView: "Présentation",
            .menuScanner: "Scanner",
            .menuExport: "Exportation",
            .menuWindow: "Fenêtre",
            .menuHelp: "Aide",
            .commandImportImages: "Importer des images",
            .commandRefreshLibrary: "Actualiser la bibliothèque",
            .commandDeletePhoto: "Retirer de negaflow",
            .commandPick: "Retenir",
            .commandReject: "Rejeter",
            .commandCopyDevelopSettings: "Copier les réglages de développement",
            .commandPasteDevelopSettings: "Coller les réglages de développement",
            .commandAutoTone: "Tonalité auto",
            .commandAutoWhiteBalance: "Balance des blancs auto",
            .commandResetAdjustments: "Réinitialiser tous les réglages",
            .commandShowHideSidebar: "Afficher/masquer la barre latérale",
            .commandShowHideFilmstrip: "Afficher/masquer le film fixe",
            .commandShowHideInspector: "Afficher/masquer l'inspecteur",
            .commandToggleFullScreen: "Passer en plein écran",
            .commandDetectScanners: "Rechercher les scanners",
            .commandToggleScannerSimulator: "Simulateur de scanner",
            .commandPreviewScan: "Numérisation d'aperçu",
            .commandScanFrame: "Numériser l'image",
            .commandExport: "Exporter",
            .commandQuickExport: "Exportation rapide",
            .commandSettings: "Réglages",
            .commandNegaflowHelp: "Démarrage rapide",
            .commandKeyboardShortcuts: "Raccourcis clavier",
            .commandDiagnostics: "Diagnostics",
            .commandWorkspaceOptions: "Options de l'espace de travail",
            .diagnosticsEmpty: "Aucun diagnostic disponible",
            .diagnosticsRecentProblemsTitle: "Problèmes récents",
            .diagnosticsClearProblems: "Effacer",
            .diagnosticsNoProblems: "Aucun problème",
            .diagnosticsReportProblemsSection: "Problèmes récents",
            .diagnosticsReportEventsSection: "Événements d'échec récents",
            .diagnosticsReportLibrarySection: "État de la bibliothèque",
            .diagnosticsReportScannerSection: "Scanner",
            .diagnosticsStatFrames: "Images",
            .diagnosticsStatUnsaved: "Modifications non enregistrées",
            .diagnosticsStatLifecycle: "Cycle de vie",
            .diagnosticsStatSaveError: "Erreur d'enregistrement",
            .diagnosticsValueYes: "Oui",
            .diagnosticsValueNo: "Non",
            .diagnosticsGeneratedAt: "Généré",
            .diagnosticsScannerBackend: "Backend",
            .diagnosticsScannerPlugins: "Plug-ins",
            .settingsGeneralTab: "Général",
            .settingsInterfaceTab: "Interface",
            .settingsLanguageTab: "Langue",
            .settingsWorkflowTab: "Flux de travail",
            .settingsExportTab: "Exportation",
            .settingsShortcutsTab: "Raccourcis",
            .settingsLegalTab: "Mentions",
            .legalLicenseTitle: "Licence open source",
            .legalLicenseBody: "Le code source de negaflow est distribué sous licence Apache License 2.0. Cette licence couvre le code du projet ; elle n'accorde aucun droit sur les marques, noms de films, noms de scanners, noms de produits, fiches techniques publiées, scans de référence, logos, emballages ou logiciels de scanner propriétaires de tiers.",
            .legalTrademarkTitle: "Utilisation des marques",
            .legalTrademarkBody: "negaflow est un outil indépendant et open source de numérisation de film et de profilage couleur. Les noms de films, scanners, minilabs, procédés et cibles servent uniquement à identifier les films, modèles de scanners, systèmes de laboratoire ou familles de profils que negaflow approxime, mesure ou avec lesquels il interopère.",
            .legalNamesTitle: "Noms mentionnés",
            .legalNamesBody: "Les noms mentionnés peuvent inclure Kodak, Kodak Professional, Portra, Ektar, Gold, UltraMax, Pro Image, ColorPlus, Vision3, Ektachrome, Fujifilm, Fuji, Fujicolor, Fujichrome, Superia, Frontier, SP-3000, Noritsu, HS-1800, CineStill, Lomography, Lomo, Harman, Phoenix, ORWO, Wolfen, ainsi que des noms associés de films, scanners, minilabs ou procédés.",
            .legalProfilesTitle: "Profils et systèmes cibles",
            .legalProfilesBody: "Les profils de films et de scanners inclus sont des métadonnées de compatibilité et des transformations couleur mesurées ou estimées pour negaflow. Ce ne sont pas des profils officiels de fabricants, des chartes couleur certifiées, un firmware de remplacement de scanner ni une copie d'un logiciel de traitement propriétaire.",
            .legalAffiliationTitle: "Aucune affiliation ni approbation",
            .legalAffiliationBody: "negaflow n'est pas affilié, approuvé, sponsorisé, certifié ni validé par Eastman Kodak Company, Kodak Alaris, FUJIFILM Corporation, Noritsu Koki Co., Ltd., CineStill Film, Lomographische AG/Lomography, Harman Technology Ltd, ORWO/ORWO Net ou tout autre détenteur de marque. Toutes les marques, marques de service, dénominations commerciales, logos et noms de produits appartiennent à leurs propriétaires respectifs.",
            .settingsLanguagePicker: "Langue de l'application",
            .settingsAppearancePicker: "Apparence",
            .settingsCanvasBackgroundPicker: "Arrière-plan du canevas",
            .settingsQuickExportFormat: "Format d'exportation rapide",
            .settingsQuickExportDPI: "DPI d'exportation rapide",
            .settingsQuickExportFolder: "Dossier d'exportation rapide",
            .settingsQuickExportSize: "Taille d'exportation rapide",
            .settingsExportVerification: "Vérification d'intégrité à l'exportation",
            .settingsExportVerificationStandard: "Standard",
            .settingsExportVerificationStrict: "Stricte (plus lente)",
            .settingsExportVerificationHelp: "Le mode standard calcule un hachage une seule fois par fichier, puis revérifie via l'identité du fichier. Le mode strict rehache tous les octets à chaque point de contrôle. La récupération après plantage offre les mêmes garanties dans les deux cas.",
            .settingsSourceDPI: "DPI source",
            .shortcutKeyField: "Touche",
            .shortcutReset: "Réinitialiser",
            .shortcutResetAll: "Réinitialiser tous les raccourcis",
            .shortcutInvalidOrConflict: "Ce raccourci est indisponible ou déjà utilisé.",
            .shortcutClickToRecord: "Cliquez, puis appuyez sur les touches",
            .shortcutRecordingPrompt: "Saisissez un raccourci",
            .shortcutModifierCommand: "Commande",
            .shortcutModifierShift: "Maj",
            .shortcutModifierOption: "Option",
            .shortcutModifierControl: "Contrôle",
            .appearanceSystem: "Système",
            .appearanceDark: "Sombre",
            .appearanceLight: "Clair",
            .canvasBackgroundBlack: "Noir",
            .canvasBackgroundGray: "Gris",
            .canvasBackgroundWhite: "Blanc",
            .exportFormatLabel: "Format",
            .exportColorLabel: "Couleur",
            .exportSoftProofLabel: "Épreuve écran",
            .exportProofLabel: "Épreuve",
            .exportDPILabel: "DPI",
            .exportSizeLabel: "Taille",
            .exportFullSize: "Taille réelle",
            .exportLongEdgeSuffix: "px (bord long)",
            .exportMainFlatMasterHelp: "Enregistre un master MAIN non corrigé à côté de l'export corrigé, avec le suffixe -main-flat.",
            .exportOriginalRawHelp: "Enregistre le TIFF de scan original à côté de l'export corrigé, avec le suffixe -original.",
            .exportSidecarHelp: "Enregistre les paramètres de développement dans <name>.negaflow.json et <name>.xmp.",
            .exportSourceLabel: "Source",
            .exportFolderLabel: "Dossier",
            .exportChangeFolder: "Modifier",
            .libraryAmbiguousExportRecoveryTitle: "Récupération d’exportation requise",
            .libraryAmbiguousExportRecoveryMessage: "negaflow n’a pas pu terminer cette exportation en toute sécurité. Conserver les fichiers actuels et continuer est le choix le plus sûr.",
            .libraryAmbiguousExportTransaction: "Transaction",
            .libraryAmbiguousExportKeepFiles: "Conserver les fichiers et continuer",
            .libraryAmbiguousExportDeleteFiles: "Supprimer les fichiers créés",
            .libraryAmbiguousExportDeleteConfirmationTitle: "Supprimer ces fichiers exportés ?",
            .libraryAmbiguousExportDeleteConfirmationMessage: "Seuls les fichiers dont la propriété et le contenu correspondent encore à cette exportation seront supprimés. Cette action est irréversible.",
            .libraryAmbiguousExportRecoveryFailed: "Impossible de terminer la récupération de l’exportation",
            .colorManagementSection: "Gestion des couleurs",
            .colorScannerInputReason: "Aucun rendu d’émulation de scanner n’est sélectionné.",
            .colorSoftProofOffReason: "L'épreuve écran est désactivée.",
            .colorGamutUnavailableReason: "Le profil de sortie sélectionné ne prend pas en charge le contrôle de gamme ColorSync.",
            .colorSamplerUnavailableReason: "L'échantillonneur de pixels n'est pas disponible dans cette version.",
            .colorUnavailable: "Indisponible",
            .colorUnassigned: "Non attribué",
            .colorSystemDisplayProfile: "Profil d'affichage ColorSync du système",
            .colorOff: "Désactivé",
            .scanPhaseIdle: "Inactif",
            .scanPhaseConnecting: "Connexion",
            .scanPhaseWarmingLamp: "Préchauffage de la lampe",
            .scanPhaseReady: "Prêt",
            .scanPhasePreviewScanning: "Aperçu de numérisation",
            .scanPhaseWaitingForFilmHolder: "En attente du porte-film",
            .scanPhaseScanningRGB: "Numérisation",
            .scanPhaseScanningIR: "Numérisation IR",
            .scanPhaseProcessingNegative: "Traitement du négatif",
            .scanPhaseRenderingLook: "Rendu du développement",
            .scanPhaseExporting: "Exportation",
            .scanPhaseComplete: "Terminé",
            .scanPhaseScannerBusy: "Scanner occupé",
            .scanPhaseDisconnected: "Déconnecté",
            .scanPhaseError: "Erreur",
            .scanPhaseBackendFallbackActive: "Backend de secours",
            .sidebarLibrary: "Bibliothèque",
            .sidebarFiles: "Fichiers",
            .sidebarVersions: "Versions",
            .sidebarPresets: "Paramètres prédéfinis",
            .sidebarFilm: "Film",
            .sidebarOutput: "Sortie",
            .noFrame: "Aucune image",
            .noExportFrame: "Aucune image à exporter",
            .importSection: "Importation",
            .importImages: "Importer des images",
            .importHint: "Choisissez plusieurs fichiers ou glissez des images dans la fenêtre.",
            .loadScanner: "Charger le scanner",
            .developDefaults: "Développement",
            .noLook: "Aucun",
            .autoFilmMatch: "Auto (correspondance film)",
            .emptyCanvasTitle: "Importer des images",
            .emptyCanvasDescription: "Glissez des fichiers dans la fenêtre ou utilisez Importer dans Bibliothèque.\nChargez un scanner depuis Bibliothèque pour numériser un film.",
            .exportSection: "Exportation",
            .quickExportSection: "Exportation rapide",
            .printLayoutSection: "Mise en page du tirage",
            .printLayoutMode: "Disposition",
            .printSingleImage: "Image unique",
            .printContactSheet: "Planche-contact",
            .printPicturePackage: "Package d’images",
            .printCustomPackage: "Package personnalisé",
            .printPaperSize: "Format du papier",
            .printOrientation: "Orientation",
            .printOrientationAutomatic: "Auto",
            .printOrientationPortrait: "Portrait",
            .printOrientationLandscape: "Paysage",
            .printMargin: "Marge",
            .printRows: "Lignes",
            .printColumns: "Colonnes",
            .printHorizontalSpacing: "Espacement horizontal",
            .printVerticalSpacing: "Espacement vertical",
            .printImageFit: "Ajustement de l’image",
            .printFit: "Ajuster",
            .printFill: "Remplir la cellule",
            .printRotateToFit: "Pivoter de 90° pour ajuster",
            .printRepeatOnePhoto: "Répéter une photo",
            .printPictureTemplate: "Disposition du package",
            .printOneLargeTwoSmall: "1 grande + 2 petites",
            .printTwoUp: "2 poses",
            .printFourUp: "4 poses",
            .printCaption: "Légende",
            .printCaptionFileName: "Nom du fichier",
            .printCaptionFrameNumber: "Numéro de vue",
            .printCaptionRating: "Note",
            .printCropMarks: "Repères de coupe",
            .printTemplates: "Modèles de disposition",
            .printTemplateName: "Nom du modèle",
            .printTemplateUpdateFailed: "Les modifications du modèle n’ont pas pu être enregistrées.",
            .printPackagePageLimit: "Un lot d’impression peut contenir jusqu’à 32 pages.",
            .printAddCell: "Ajouter une cellule",
            .printDuplicateCell: "Dupliquer la cellule",
            .printDeleteCell: "Supprimer la cellule",
            .printCell: "Cellule",
            .printSourcePhoto: "Photo",
            .printPage: "Page",
            .printPreviousPage: "Page précédente",
            .printNextPage: "Page suivante",
            .printPositionX: "Position horizontale",
            .printPositionY: "Position verticale",
            .printWidth: "Largeur",
            .printHeight: "Hauteur",
            .printFilmSimulation: "Simulation du tirage film",
            .printPaperSimulation: "Simulation du papier photo",
            .printOutputProfile: "Profil de sortie d’imprimante",
            .printPerforationSimulation: "Simulation des perforations",
    ]
}
