import Foundation

extension AppLocalization {
    static let englishTextTable: [AppLocalizedText: String] = [
            .menuFile: "File",
            .menuEdit: "Edit",
            .menuLibrary: "Library",
            .menuPhoto: "Photo",
            .menuDevelop: "Develop",
            .menuPrint: "Print",
            .menuView: "View",
            .menuScanner: "Scanner",
            .menuExport: "Export",
            .menuWindow: "Window",
            .menuHelp: "Help",
            .commandImportImages: "Import Photos",
            .commandRefreshLibrary: "Refresh Library",
            .commandDeletePhoto: "Remove from Negaflow",
            .commandPick: "Pick",
            .commandReject: "Reject",
            .commandCopyDevelopSettings: "Copy Develop Settings",
            .commandPasteDevelopSettings: "Paste Develop Settings",
            .commandAutoTone: "Auto Tone",
            .commandAutoWhiteBalance: "Auto White Balance",
            .commandResetAdjustments: "Reset All Adjustments",
            .commandShowHideSidebar: "Show/Hide Sidebar",
            .commandShowHideFilmstrip: "Show/Hide Filmstrip",
            .commandShowHideInspector: "Show/Hide Inspector",
            .commandToggleFullScreen: "Enter Full Screen",
            .commandDetectScanners: "Detect Scanners",
            .commandToggleScannerSimulator: "Scanner Simulator",
            .commandPreviewScan: "Preview Scan",
            .commandScanFrame: "Scan Frame",
            .commandExport: "Export",
            .commandQuickExport: "Quick Export",
            .commandSettings: "Settings",
            .commandNegaflowHelp: "Quick Start",
            .commandKeyboardShortcuts: "Keyboard Shortcuts",
            .commandDiagnostics: "Diagnostics",
            .commandWorkspaceOptions: "Workspace Options",
            .diagnosticsEmpty: "No diagnostics available",
            .diagnosticsRecentProblemsTitle: "Recent problems",
            .diagnosticsClearProblems: "Clear",
            .diagnosticsNoProblems: "No problems",
            .diagnosticsReportProblemsSection: "Recent problems",
            .diagnosticsReportEventsSection: "Recent failure events",
            .diagnosticsReportLibrarySection: "Library status",
            .diagnosticsReportScannerSection: "Scanner",
            .diagnosticsStatFrames: "Frames",
            .diagnosticsStatUnsaved: "Unsaved changes",
            .diagnosticsStatLifecycle: "Lifecycle",
            .diagnosticsStatSaveError: "Save error",
            .diagnosticsValueYes: "Yes",
            .diagnosticsValueNo: "No",
            .diagnosticsGeneratedAt: "Generated",
            .diagnosticsScannerBackend: "Backend",
            .diagnosticsScannerPlugins: "Plug-ins",
            .settingsGeneralTab: "General",
            .settingsInterfaceTab: "Interface",
            .settingsLanguageTab: "Language",
            .settingsWorkflowTab: "Workflow",
            .settingsExportTab: "Export",
            .settingsShortcutsTab: "Shortcuts",
            .settingsLegalTab: "Legal",
            .legalLicenseTitle: "Open Source License",
            .legalLicenseBody: "Negaflow source code is distributed under the Apache License 2.0. That license covers this project's code; it does not grant rights to third-party trademarks, film names, scanner names, product names, published datasheets, reference scans, logos, packaging, or proprietary scanner software.",
            .legalTrademarkTitle: "Trademark Use",
            .legalTrademarkBody: "Negaflow is an independent open-source film scanning and color profiling tool. Film, scanner, minilab, process, and target names are used only to identify physical film stocks, scanner models, laboratory target systems, or profile families that Negaflow approximates, measures, or interoperates with.",
            .legalNamesTitle: "Names Referenced",
            .legalNamesBody: "Referenced names may include Kodak, Kodak Professional, Portra, Ektar, Gold, UltraMax, Pro Image, ColorPlus, Vision3, Ektachrome, Fujifilm, Fuji, Fujicolor, Fujichrome, Superia, Frontier, SP-3000, Noritsu, HS-1800, CineStill, Lomography, Lomo, Harman, Phoenix, ORWO, Wolfen, and related film, scanner, minilab, or process names.",
            .legalProfilesTitle: "Profiles and Target Systems",
            .legalProfilesBody: "Bundled film and scanner profiles are compatibility metadata and measured or estimated color transforms for Negaflow. They are not official manufacturer profiles, certified color targets, replacement scanner firmware, or a copy of any manufacturer's proprietary processing software.",
            .legalAffiliationTitle: "No Affiliation or Endorsement",
            .legalAffiliationBody: "Negaflow is not affiliated with, endorsed by, sponsored by, certified by, or approved by Eastman Kodak Company, Kodak Alaris, FUJIFILM Corporation, Noritsu Koki Co., Ltd., CineStill Film, Lomographische AG/Lomography, Harman Technology Ltd, ORWO/ORWO Net, or any other trademark owner. All trademarks, service marks, trade names, logos, and product names are the property of their respective owners.",
            .settingsLanguagePicker: "Application Language",
            .settingsAppearancePicker: "Appearance",
            .settingsCanvasBackgroundPicker: "Canvas Background",
            .settingsQuickExportFormat: "Quick Export Format",
            .settingsQuickExportDPI: "Quick Export DPI",
            .settingsQuickExportFolder: "Quick Export Folder",
            .settingsSourceDPI: "Source DPI",
            .shortcutKeyField: "Key",
            .shortcutReset: "Reset",
            .shortcutResetAll: "Reset All Shortcuts",
            .shortcutInvalidOrConflict: "Shortcut is unavailable or already used.",
            .shortcutClickToRecord: "Click, then press keys",
            .shortcutRecordingPrompt: "Press shortcut",
            .shortcutModifierCommand: "Command",
            .shortcutModifierShift: "Shift",
            .shortcutModifierOption: "Option",
            .shortcutModifierControl: "Control",
            .appearanceSystem: "System",
            .appearanceDark: "Dark",
            .appearanceLight: "Light",
            .canvasBackgroundBlack: "Black",
            .canvasBackgroundGray: "Gray",
            .canvasBackgroundWhite: "White",
            .exportFormatLabel: "Format",
            .exportColorLabel: "Color",
            .exportSoftProofLabel: "Soft Proof",
            .exportProofLabel: "Proof",
            .exportDPILabel: "DPI",
            .exportSizeLabel: "Size",
            .exportFullSize: "Full",
            .exportLongEdgeSuffix: "px (long edge)",
            .exportMainFlatMasterHelp: "Save an unadjusted MAIN master beside the adjusted export as -main-flat.",
            .exportOriginalRawHelp: "Save the original scan TIFF beside the adjusted export as -original.",
            .exportSidecarHelp: "Save develop parameters as <name>.negaflow.json and <name>.xmp.",
            .exportSourceLabel: "Source",
            .exportFolderLabel: "Folder",
            .exportChangeFolder: "Change",
            .libraryAmbiguousExportRecoveryTitle: "Export Recovery Required",
            .libraryAmbiguousExportRecoveryMessage: "Negaflow could not safely close this export. Keeping the current files and continuing is the safest choice.",
            .libraryAmbiguousExportTransaction: "Transaction",
            .libraryAmbiguousExportKeepFiles: "Keep Files and Continue",
            .libraryAmbiguousExportDeleteFiles: "Delete Owned Files",
            .libraryAmbiguousExportDeleteConfirmationTitle: "Delete These Export Files?",
            .libraryAmbiguousExportDeleteConfirmationMessage: "Only files whose ownership and contents still match this export will be deleted. This cannot be undone.",
            .libraryAmbiguousExportRecoveryFailed: "Couldn’t Complete Export Recovery",
            .colorManagementSection: "Color Management",
            .colorScannerInputReason: "No scanner-emulation look is selected.",
            .colorSoftProofOffReason: "Soft Proof is off.",
            .colorGamutUnavailableReason: "The selected output profile does not support ColorSync gamut checking.",
            .colorSamplerUnavailableReason: "Pixel sampler/readout is not available in this build.",
            .colorUnavailable: "Unavailable",
            .colorUnassigned: "Unassigned",
            .colorSystemDisplayProfile: "System ColorSync display profile",
            .colorOff: "Off",
            .scanPhaseIdle: "Idle",
            .scanPhaseConnecting: "Connecting",
            .scanPhaseWarmingLamp: "Warming lamp",
            .scanPhaseReady: "Ready",
            .scanPhasePreviewScanning: "Preview scan",
            .scanPhaseWaitingForFilmHolder: "Waiting for film holder",
            .scanPhaseScanningRGB: "Scanning",
            .scanPhaseScanningIR: "IR scan",
            .scanPhaseProcessingNegative: "Processing negative",
            .scanPhaseRenderingLook: "Rendering develop",
            .scanPhaseExporting: "Exporting",
            .scanPhaseComplete: "Complete",
            .scanPhaseScannerBusy: "Scanner busy",
            .scanPhaseDisconnected: "Disconnected",
            .scanPhaseError: "Error",
            .scanPhaseBackendFallbackActive: "Fallback backend",
            .sidebarLibrary: "Library",
            .sidebarFiles: "Files",
            .sidebarVersions: "Versions",
            .sidebarPresets: "Presets",
            .sidebarFilm: "Film",
            .sidebarOutput: "Output",
            .noFrame: "No Frame",
            .noExportFrame: "No frame to export",
            .importSection: "Import",
            .importImages: "Import Photos",
            .importHint: "Choose multiple files or drag images into the window.",
            .loadScanner: "Load Scanner",
            .developDefaults: "Develop",
            .noLook: "None",
            .autoFilmMatch: "Auto (film match)",
            .emptyCanvasTitle: "Import photos",
            .emptyCanvasDescription: "Drag files into the window or use Import in Library.\nLoad a scanner from Library to scan film.",
            .exportSection: "Export",
            .quickExportSection: "Quick Export",
            .printLayoutSection: "Print Layout",
            .printLayoutMode: "Layout",
            .printSingleImage: "Single Image",
            .printContactSheet: "Contact Sheet",
            .printPicturePackage: "Picture Package",
            .printCustomPackage: "Custom Package",
            .printPaperSize: "Paper Size",
            .printOrientation: "Orientation",
            .printOrientationAutomatic: "Auto",
            .printOrientationPortrait: "Portrait",
            .printOrientationLandscape: "Landscape",
            .printMargin: "Margin",
            .printRows: "Rows",
            .printColumns: "Columns",
            .printHorizontalSpacing: "Horizontal Spacing",
            .printVerticalSpacing: "Vertical Spacing",
            .printImageFit: "Image Fit",
            .printFit: "Fit",
            .printFill: "Fill Cell",
            .printRotateToFit: "Rotate 90° to Fit",
            .printRepeatOnePhoto: "Repeat One Photo",
            .printPictureTemplate: "Package Layout",
            .printOneLargeTwoSmall: "1 Large + 2 Small",
            .printTwoUp: "2-Up",
            .printFourUp: "4-Up",
            .printCaption: "Caption",
            .printCaptionFileName: "File Name",
            .printCaptionFrameNumber: "Frame Number",
            .printCaptionRating: "Rating",
            .printCropMarks: "Crop Marks",
            .printTemplates: "Layout Templates",
            .printTemplateName: "Template Name",
            .printTemplateUpdateFailed: "Template changes could not be saved.",
            .printPackagePageLimit: "A print package can contain up to 32 pages.",
            .printAddCell: "Add Cell",
            .printDuplicateCell: "Duplicate Cell",
            .printDeleteCell: "Delete Cell",
            .printCell: "Cell",
            .printSourcePhoto: "Photo",
            .printPage: "Page",
            .printPreviousPage: "Previous Page",
            .printNextPage: "Next Page",
            .printPositionX: "Horizontal Position",
            .printPositionY: "Vertical Position",
            .printWidth: "Width",
            .printHeight: "Height",
            .printFilmSimulation: "Film Print Simulation",
            .printPaperSimulation: "Print Paper Simulation",
            .printOutputProfile: "Printer Output Profile",
            .printPerforationSimulation: "Film Perforation Simulation",
    ]
}
