[CmdletBinding()]
param(
    [string]$GoldenDirectory = (Join-Path (Split-Path -Parent (Split-Path -Parent $PSScriptRoot)) 'docs\verification\macos-golden\vibrance'),
    [string]$OutputPath = (Join-Path (Split-Path -Parent $PSScriptRoot) 'src\Native\imaging\muted_scene_vibrance_table.cpp')
)

$ErrorActionPreference = 'Stop'

# ColorModel slider and scanner-profile grade need the negative branch as well as the old
# muted-scene positive range.  The negative response has one measured slope over the supplied
# anchors, so -0.05 is sufficient for the clamped low endpoint; 0.60/0.80 close the slider's
# high end without duplicating every 0.05 positive plane.
$planes = @(
    [pscustomobject]@{ Amount = -0.05; File = 'civibrance33-am0.050-256x141.f32' },
    [pscustomobject]@{ Amount =  0.05; File = 'civibrance33-a0.050-256x141.f32' },
    [pscustomobject]@{ Amount =  0.25; File = 'civibrance33-a0.250-256x141.f32' },
    [pscustomobject]@{ Amount =  0.50; File = 'civibrance33-a0.500-256x141.f32' },
    [pscustomobject]@{ Amount =  0.60; File = 'civibrance33-a0.600-256x141.f32' },
    [pscustomobject]@{ Amount =  0.80; File = 'civibrance33-a0.800-256x141.f32' }
)
$sampleCount = 33 * 33 * 33
$bytesPerPixel = 16
$quantum = 3.8182479871e-5
$inputPath = Join-Path $GoldenDirectory 'civibrance33-input-256x141.f32'
$input = [System.IO.File]::ReadAllBytes($inputPath)
if ($input.Length -lt $sampleCount * $bytesPerPixel) {
    throw "Unexpected CIVibrance input length: $($input.Length)."
}

$values = [System.Collections.Generic.List[UInt16]]::new($sampleCount * $planes.Count)
foreach ($plane in $planes) {
    $goldenOutputPath = Join-Path $GoldenDirectory $plane.File
    $output = [System.IO.File]::ReadAllBytes($goldenOutputPath)
    if ($output.Length -ne $input.Length) {
        throw "Unexpected CIVibrance output length for $($plane.File): $($output.Length)."
    }
    for ($index = 0; $index -lt $sampleCount; ++$index) {
        $offset = $index * $bytesPerPixel
        $red = [double][BitConverter]::ToSingle($input, $offset)
        $green = [double][BitConverter]::ToSingle($input, $offset + 4)
        $blue = [double][BitConverter]::ToSingle($input, $offset + 8)
        $anchor = ($red + $green + $blue) / 3.0
        $dr = $red - $anchor
        $dg = $green - $anchor
        $db = $blue - $anchor
        $denominator = ($dr * $dr) + ($dg * $dg) + ($db * $db)
        $slope = 0.0
        if ($denominator -gt 1.0e-12) {
            $outRed = [double][BitConverter]::ToSingle($output, $offset)
            $outGreen = [double][BitConverter]::ToSingle($output, $offset + 4)
            $outBlue = [double][BitConverter]::ToSingle($output, $offset + 8)
            $scale = 1.0 + ((($outRed - $red) * $dr) +
                (($outGreen - $green) * $dg) + (($outBlue - $blue) * $db)) / $denominator
            $slope = ($scale - 1.0) / [double]$plane.Amount
        }
        $encoded = [Math]::Round($slope / $quantum, [MidpointRounding]::AwayFromZero)
        if ($encoded -lt 0 -or $encoded -gt [UInt16]::MaxValue) {
            throw "CIVibrance slope is outside UInt16 range at amount $($plane.Amount), sample $index."
        }
        [void]$values.Add([UInt16]$encoded)
    }
}

$amounts = '-0.05F, 0.05F, 0.25F, 0.50F, 0.60F, 0.80F'
$builder = [System.Text.StringBuilder]::new()
[void]$builder.Append(@"
// Generated by scripts/generate-civibrance-table.ps1. Do not edit by hand.
//
// macOS CIVibrance has no public kernel. This table stores the measured 33^3 RGBAf,
// linear-sRGB mapping from docs/verification/macos-golden/vibrance/ as
//   out = A + (in - A) * (1 + amount * g), A = (R + G + B) / 3.
// The six planes cover the full ColorModel range: the measured negative slope, the
// muted-scene range, and the 0.80 slider endpoint. The source golden hashes are in
// docs/verification/macos-golden/vibrance/README.md.
#include "negaflow/imaging/muted_scene_vibrance_table.h"

namespace negaflow::imaging::detail {

const float vibrance_table_amounts[vibrance_table_plane_count] = {$amounts};
const float vibrance_table_quantum = 3.8182479871e-05F;

const std::uint16_t vibrance_table_g[vibrance_table_entry_count] = {
"@)
for ($index = 0; $index -lt $values.Count; ++$index) {
    if (($index % 24) -eq 0) {
        [void]$builder.Append('    ')
    }
    [void]$builder.Append($values[$index])
    if ($index + 1 -lt $values.Count) {
        [void]$builder.Append(',')
    }
    if (($index % 24) -eq 23 -or $index + 1 -eq $values.Count) {
        [void]$builder.Append("`n")
    }
}
[void]$builder.Append("};`n`n}  // namespace negaflow::imaging::detail`n")
[System.IO.File]::WriteAllText(
    $OutputPath,
    $builder.ToString(),
    [System.Text.UTF8Encoding]::new($false))
